// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e4fc90c95afaebc0 "Das Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
 * badge?: string // Badge
 * title?: string // Title
 * text?: string // Text
 * buttonTitle?: string // Button Title
 * buttonLink?: string // Button Link
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-UVSWH3FI.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-IYUBPT6N.js";
import "./chunks/chunk-I6BBA4QK.js";
import { stdin_default } from "./chunks/chunk-GHRXF5NR.js";
import "./chunks/chunk-EANZ46VA.js";
import "./chunks/chunk-7CFDZMPZ.js";
import { className, css, fonts } from "./chunks/chunk-B5JEBSFU.js";
import { routes } from "./chunks/chunk-BAX4IDEL.js";

// virtual:cta
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/KAEc6c5b0053LzotdgkE/ys5ldPoeF4dojjNyied5/H0krZCBg3.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var BadgeFonts = getFonts(stdin_default);
var ButtonFonts = getFonts(stdin_default2);
var cycleOrder = ["JmRXywUF9", "Ln6pDInWw", "LW_oCQVVz"];
var serializationHash = "framer-bQ9Nf";
var variantClassNames = {
	JmRXywUF9: "framer-v-1p6rioh",
	Ln6pDInWw: "framer-v-1if4peq",
	LW_oCQVVz: "framer-v-tsrt27",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "JmRXywUF9",
	Phone: "LW_oCQVVz",
	Tablet: "Ln6pDInWw",
};
var getProps = ({
	badge,
	buttonLink,
	buttonTitle,
	height,
	id,
	text,
	title,
	width,
	...props
}) => {
	return {
		...props,
		afuAQNdTo:
			text ??
			props.afuAQNdTo ??
			"Work with a team that brings clarity, care, and creativity to every project.",
		lVTJGlCJ2: buttonLink ?? props.lVTJGlCJ2,
		rKl92LRcr: buttonTitle ?? props.rKl92LRcr ?? "Book a call",
		U6lk6b9Bf: badge ?? props.U6lk6b9Bf ?? "Free 20-min intro call",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "JmRXywUF9",
		xUw8cLcuc: title ?? props.xUw8cLcuc ?? "Tell us what you're building",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		U6lk6b9Bf: U6lk6b9Bf2,
		xUw8cLcuc: xUw8cLcuc2,
		afuAQNdTo: afuAQNdTo2,
		rKl92LRcr: rKl92LRcr2,
		lVTJGlCJ2: lVTJGlCJ22,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "JmRXywUF9",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.section
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1p6rioh",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"JmRXywUF9"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								Ln6pDInWw: {
									"data-framer-name": "Tablet",
								},
								LW_oCQVVz: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1m269d0"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"VomoPGo6p"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-16ud8ug"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"mDhXyv4Kj"}
							>
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={28}
									y={
										(componentViewport?.y || 0) +
										90 +
										(((componentViewport?.height || 480.5) - 180 - 456.9) / 2 +
											0 +
											0) +
										0 +
										0 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											Ln6pDInWw: {
												y:
													(componentViewport?.y || 0) +
													70 +
													(((componentViewport?.height || 495.5) -
														140 -
														456.9) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													0,
											},
											LW_oCQVVz: {
												y:
													(componentViewport?.y || 0) +
													60 +
													(((componentViewport?.height || 530.5) -
														120 -
														456.9) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-1o8dzrx-container"}
										layoutDependency={layoutDependency}
										layoutId={"RQqsJffch-container"}
										nodeId={"RQqsJffch"}
										rendersWithMotion={true}
										scopeId={"H0krZCBg3"}
									>
										{_jsx(stdin_default, {
											suppressHydrationWarning: true,
											height: "100%",
											id: "RQqsJffch",
											layoutId: "RQqsJffch",
											Q9pPRx4wJ: U6lk6b9Bf2,
											Wg_ILYJAw: "",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-s4bo76"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"U769FBiq0"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={xUw8cLcuc2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-gwzd60"}
											data-styles-preset={"nzncKCFi1"}
											dir={"auto"}
											style={{
												"--framer-text-alignment": "center",
											}}
										>
											{"Tell us what you're building"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-hwpi76"}
									data-framer-name={"Description"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"S9sebsFfJ"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(10, 10, 10))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={afuAQNdTo2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-26kq2w"}
											data-styles-preset={"zuIVYXLhn"}
											dir={"auto"}
											style={{
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(10, 10, 10)))",
											}}
										>
											{
												"Work with a team that brings clarity, care, and creativity to every project."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<ComponentViewportProvider
								suppressHydrationWarning={true}
								height={44}
								y={
									(componentViewport?.y || 0) +
									90 +
									(((componentViewport?.height || 480.5) - 180 - 456.9) / 2 +
										0 +
										0) +
									0 +
									412.9
								}
								{...addPropertyOverrides(
									{
										Ln6pDInWw: {
											y:
												(componentViewport?.y || 0) +
												70 +
												(((componentViewport?.height || 495.5) - 140 - 456.9) /
													2 +
													0 +
													0) +
												0 +
												412.9,
										},
										LW_oCQVVz: {
											y:
												(componentViewport?.y || 0) +
												60 +
												(((componentViewport?.height || 530.5) - 120 - 456.9) /
													2 +
													0 +
													0) +
												0 +
												412.9,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-2ob7sf-container"}
									layoutDependency={layoutDependency}
									layoutId={"WsNxiE3Iu-container"}
									nodeId={"WsNxiE3Iu"}
									rendersWithMotion={true}
									scopeId={"H0krZCBg3"}
								>
									{_jsx(stdin_default2, {
										suppressHydrationWarning: true,
										Ge1cwLZdF: true,
										height: "100%",
										id: "WsNxiE3Iu",
										IQJfIgKUA: lVTJGlCJ22,
										kUCdcilHJ: rKl92LRcr2,
										layoutId: "WsNxiE3Iu",
										variant: matchVariant("qIg3fad0d"),
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-bQ9Nf.framer-1nl961e, .framer-bQ9Nf .framer-1nl961e { display: block; }",
	".framer-bQ9Nf.framer-1p6rioh { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 90px 0px 90px 0px; position: relative; width: 1120px; }",
	".framer-bQ9Nf .framer-1m269d0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; max-width: 600px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-bQ9Nf .framer-16ud8ug { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-bQ9Nf .framer-1o8dzrx-container, .framer-bQ9Nf .framer-2ob7sf-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-bQ9Nf .framer-s4bo76 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-bQ9Nf .framer-hwpi76 { --framer-text-wrap-override: balance; flex: none; height: auto; max-width: 420px; position: relative; width: auto; z-index: 1; }",
	".framer-bQ9Nf.framer-v-1if4peq.framer-1p6rioh { padding: 70px 0px 70px 0px; width: 810px; }",
	".framer-bQ9Nf.framer-v-1if4peq .framer-1m269d0 { max-width: 420px; }",
	".framer-bQ9Nf.framer-v-tsrt27.framer-1p6rioh { padding: 60px 0px 60px 0px; width: 390px; }",
	".framer-bQ9Nf.framer-v-tsrt27 .framer-1m269d0 { max-width: 100%; }",
	...css2,
	...css,
];
var FramerH0krZCBg3 = withCSS(Component, css3, "framer-bQ9Nf");
var stdin_default3 = FramerH0krZCBg3;
FramerH0krZCBg3.displayName = "CTA";
FramerH0krZCBg3.defaultProps = {
	height: 480.5,
	width: 1120,
};
addPropertyControls(FramerH0krZCBg3, {
	variant: {
		options: ["JmRXywUF9", "Ln6pDInWw", "LW_oCQVVz"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	U6lk6b9Bf: {
		defaultValue: "Free 20-min intro call",
		displayTextArea: false,
		title: "Badge",
		type: ControlType.String,
	},
	xUw8cLcuc: {
		defaultValue: "Tell us what you're building",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	afuAQNdTo: {
		defaultValue:
			"Work with a team that brings clarity, care, and creativity to every project.",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	rKl92LRcr: {
		defaultValue: "Book a call",
		displayTextArea: false,
		title: "Button Title",
		type: ControlType.String,
	},
	lVTJGlCJ2: {
		title: "Button Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerH0krZCBg3,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...BadgeFonts,
		...ButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cta
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "LW_oCQVVz",
	md: "Ln6pDInWw",
	xl: "JmRXywUF9",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CtaFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var cta_default = ComponentWithRoot;
export { cta_default as default };
