// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e4fc90c95afaebc0 "Das Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * question1?: string // Question 1
 * answer1?: string // Answer 1
 * question2?: string // Question 2
 * answer2?: string // Answer 2
 * question3?: string // Question 3
 * answer3?: string // Answer 3
 * question4?: string // Question 4
 * answer4?: string // Answer 4
 * question5?: string // Question 5
 * answer5?: string // Answer 5
 * question6?: string // Question 6
 * answer6?: string // Answer 6
}} Props

 */
import { AvoidLayoutJumping } from "./chunks/chunk-C2KZ2SUB.js";
import { stdin_default } from "./chunks/chunk-TZANVANV.js";
import "./chunks/chunk-X37PU3JY.js";
import "./chunks/chunk-XWVFXG3B.js";
import "./chunks/chunk-B5JEBSFU.js";
import { routes } from "./chunks/chunk-BAX4IDEL.js";

// virtual:faq-list
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/tm6tmihaaJ4Rw4WFdxLj/bt3JvFFRcY9fVqvPUfwk/suqoqqwp5.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var LayoutJumpPreventerFonts = getFonts(AvoidLayoutJumping);
var FAQItemFonts = getFonts(stdin_default);
var serializationHash = "framer-do9x0";
var variantClassNames = {
	Mj8HVSKOQ: "framer-v-1yinxlb",
};
var transition1 = {
	delay: 0,
	duration: 0.8,
	ease: [0.35, 0, 0, 1],
	type: "tween",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	answer1,
	answer2,
	answer3,
	answer4,
	answer5,
	answer6,
	height,
	id,
	question1,
	question2,
	question3,
	question4,
	question5,
	question6,
	width,
	...props
}) => {
	return {
		...props,
		cmSszctDS:
			question2 ?? props.cmSszctDS ?? "Can you work with an existing brand?",
		hkZIwkVzh:
			question6 ??
			props.hkZIwkVzh ??
			"Can I reach out if I\u2019m not sure what I need yet?",
		jZsvRZ9Mb:
			question5 ??
			props.jZsvRZ9Mb ??
			"Do you offer free consultations or discovery calls?",
		mnGaGA29b:
			answer5 ??
			props.mnGaGA29b ??
			"Yes, we do! Once we understand a bit about your project, we\u2019ll set up a short call to explore how we can help \u2014 no pressure, no strings.",
		nwwKYNnis: question1 ?? props.nwwKYNnis ?? "Do you take on small projects?",
		RpSuEUrgB:
			answer1 ??
			props.RpSuEUrgB ??
			"We\u2019re flexible. Whether you need a complete identity or just a standout landing page, we\u2019ll tailor our process to fit your scope \u2014 without compromising quality.",
		Rpysc4jYO:
			answer2 ??
			props.Rpysc4jYO ??
			"Yes \u2014 we love working with existing brands. Whether you have a full identity system or just a logo and a color palette, we can build upon your foundation and create visuals, campaigns, or digital experiences that stay true to your brand while elevating it in fresh and strategic ways.",
		rSVTsEqWp:
			answer6 ??
			props.rSVTsEqWp ??
			"Absolutely. Whether you have a clear brief or just a loose idea, we\u2019re happy to explore it with you. No pressure \u2014 just a conversation.",
		USZwosgP7:
			answer3 ??
			props.USZwosgP7 ??
			"It depends on the size and complexity, but most projects take 2\u20136 weeks. We\u2019ll always set clear milestones before we start \u2014 no surprises.",
		veRGiAlN0:
			question3 ??
			props.veRGiAlN0 ??
			"What\u2019s your typical project timeline?",
		WvNxNIx2D:
			question4 ?? props.WvNxNIx2D ?? "What happens after I reach out?",
		Y3SmWxbpX:
			answer4 ??
			props.Y3SmWxbpX ??
			"We\u2019ll reply within a day or two to learn more about your project. If it\u2019s a good fit, we\u2019ll suggest a quick call to discuss scope, timeline, and next steps.",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		nwwKYNnis: nwwKYNnis2,
		RpSuEUrgB: RpSuEUrgB2,
		cmSszctDS: cmSszctDS2,
		Rpysc4jYO: Rpysc4jYO2,
		veRGiAlN0: veRGiAlN02,
		USZwosgP7: USZwosgP72,
		WvNxNIx2D: WvNxNIx2D2,
		Y3SmWxbpX: Y3SmWxbpX2,
		jZsvRZ9Mb: jZsvRZ9Mb2,
		mnGaGA29b: mnGaGA29b2,
		hkZIwkVzh: hkZIwkVzh2,
		rSVTsEqWp: rSVTsEqWp2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "Mj8HVSKOQ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1yinxlb",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"Mj8HVSKOQ"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider suppressHydrationWarning={true}>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-69mf3t-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"P9w6_GkK_-container"}
								nodeId={"P9w6_GkK_"}
								rendersWithMotion={true}
								scopeId={"suqoqqwp5"}
							>
								<AvoidLayoutJumping
									suppressHydrationWarning={true}
									direction={"both"}
									height={"100%"}
									id={"P9w6_GkK_"}
									layoutId={"P9w6_GkK_"}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={100}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 679) - 0 - 600) / 2 + 0 + 0)
							}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-1d91lyu-container"}
								layoutDependency={layoutDependency}
								layoutId={"p8ssdesSm-container"}
								nodeId={"p8ssdesSm"}
								rendersWithMotion={true}
								scopeId={"suqoqqwp5"}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									height: "100%",
									id: "p8ssdesSm",
									JsJqRtbJH: RpSuEUrgB2,
									layoutId: "p8ssdesSm",
									style: {
										width: "100%",
									},
									U48nWdDpe: nwwKYNnis2,
									variant: matchVariant("bkUTbbHXG"),
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={100}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 679) - 0 - 600) / 2 + 100 + 0)
							}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-10d102d-container"}
								layoutDependency={layoutDependency}
								layoutId={"qgEJ9SX21-container"}
								nodeId={"qgEJ9SX21"}
								rendersWithMotion={true}
								scopeId={"suqoqqwp5"}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									height: "100%",
									id: "qgEJ9SX21",
									JsJqRtbJH: Rpysc4jYO2,
									layoutId: "qgEJ9SX21",
									style: {
										width: "100%",
									},
									U48nWdDpe: cmSszctDS2,
									variant: matchVariant("K5BokWKEX"),
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={100}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 679) - 0 - 600) / 2 + 200 + 0)
							}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-ddyvkp-container"}
								layoutDependency={layoutDependency}
								layoutId={"jdfmF0Bqg-container"}
								nodeId={"jdfmF0Bqg"}
								rendersWithMotion={true}
								scopeId={"suqoqqwp5"}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									height: "100%",
									id: "jdfmF0Bqg",
									JsJqRtbJH: USZwosgP72,
									layoutId: "jdfmF0Bqg",
									style: {
										width: "100%",
									},
									U48nWdDpe: veRGiAlN02,
									variant: matchVariant("K5BokWKEX"),
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={100}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 679) - 0 - 600) / 2 + 300 + 0)
							}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-13nxe7u-container"}
								layoutDependency={layoutDependency}
								layoutId={"jrXyNzksj-container"}
								nodeId={"jrXyNzksj"}
								rendersWithMotion={true}
								scopeId={"suqoqqwp5"}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									height: "100%",
									id: "jrXyNzksj",
									JsJqRtbJH: Y3SmWxbpX2,
									layoutId: "jrXyNzksj",
									style: {
										width: "100%",
									},
									U48nWdDpe: WvNxNIx2D2,
									variant: matchVariant("K5BokWKEX"),
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={100}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 679) - 0 - 600) / 2 + 400 + 0)
							}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-10tin91-container"}
								layoutDependency={layoutDependency}
								layoutId={"UKkS4x6H8-container"}
								nodeId={"UKkS4x6H8"}
								rendersWithMotion={true}
								scopeId={"suqoqqwp5"}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									height: "100%",
									id: "UKkS4x6H8",
									JsJqRtbJH: mnGaGA29b2,
									layoutId: "UKkS4x6H8",
									style: {
										width: "100%",
									},
									U48nWdDpe: jZsvRZ9Mb2,
									variant: matchVariant("K5BokWKEX"),
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={100}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 679) - 0 - 600) / 2 + 500 + 0)
							}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-147aws2-container"}
								layoutDependency={layoutDependency}
								layoutId={"TGaNsX0de-container"}
								nodeId={"TGaNsX0de"}
								rendersWithMotion={true}
								scopeId={"suqoqqwp5"}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									height: "100%",
									id: "TGaNsX0de",
									JsJqRtbJH: rSVTsEqWp2,
									layoutId: "TGaNsX0de",
									style: {
										width: "100%",
									},
									U48nWdDpe: hkZIwkVzh2,
									variant: matchVariant("K5BokWKEX"),
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-do9x0.framer-72cn2v, .framer-do9x0 .framer-72cn2v { display: block; }",
	".framer-do9x0.framer-1yinxlb { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 780px; }",
	".framer-do9x0 .framer-69mf3t-container { flex: none; height: auto; left: 0px; position: absolute; top: 0px; width: auto; z-index: 1; }",
	".framer-do9x0 .framer-1d91lyu-container, .framer-do9x0 .framer-10d102d-container, .framer-do9x0 .framer-ddyvkp-container, .framer-do9x0 .framer-13nxe7u-container, .framer-do9x0 .framer-10tin91-container, .framer-do9x0 .framer-147aws2-container { flex: none; height: auto; position: relative; width: 100%; }",
];
var Framersuqoqqwp5 = withCSS(Component, css, "framer-do9x0");
var stdin_default2 = Framersuqoqqwp5;
Framersuqoqqwp5.displayName = "FAQ List";
Framersuqoqqwp5.defaultProps = {
	height: 679,
	width: 780,
};
addPropertyControls(Framersuqoqqwp5, {
	nwwKYNnis: {
		defaultValue: "Do you take on small projects?",
		displayTextArea: false,
		placeholder: "",
		title: "Question 1",
		type: ControlType.String,
	},
	RpSuEUrgB: {
		defaultValue:
			"We\u2019re flexible. Whether you need a complete identity or just a standout landing page, we\u2019ll tailor our process to fit your scope \u2014 without compromising quality.",
		placeholder: "Answer",
		title: "Answer 1",
		type: ControlType.String,
	},
	cmSszctDS: {
		defaultValue: "Can you work with an existing brand?",
		displayTextArea: false,
		placeholder: "",
		title: "Question 2",
		type: ControlType.String,
	},
	Rpysc4jYO: {
		defaultValue:
			"Yes \u2014 we love working with existing brands. Whether you have a full identity system or just a logo and a color palette, we can build upon your foundation and create visuals, campaigns, or digital experiences that stay true to your brand while elevating it in fresh and strategic ways.",
		placeholder: "Answer",
		title: "Answer 2",
		type: ControlType.String,
	},
	veRGiAlN0: {
		defaultValue: "What\u2019s your typical project timeline?",
		displayTextArea: false,
		placeholder: "",
		title: "Question 3",
		type: ControlType.String,
	},
	USZwosgP7: {
		defaultValue:
			"It depends on the size and complexity, but most projects take 2\u20136 weeks. We\u2019ll always set clear milestones before we start \u2014 no surprises.",
		placeholder: "Answer",
		title: "Answer 3",
		type: ControlType.String,
	},
	WvNxNIx2D: {
		defaultValue: "What happens after I reach out?",
		displayTextArea: false,
		placeholder: "",
		title: "Question 4",
		type: ControlType.String,
	},
	Y3SmWxbpX: {
		defaultValue:
			"We\u2019ll reply within a day or two to learn more about your project. If it\u2019s a good fit, we\u2019ll suggest a quick call to discuss scope, timeline, and next steps.",
		placeholder: "Answer",
		title: "Answer 4",
		type: ControlType.String,
	},
	jZsvRZ9Mb: {
		defaultValue: "Do you offer free consultations or discovery calls?",
		displayTextArea: false,
		placeholder: "",
		title: "Question 5",
		type: ControlType.String,
	},
	mnGaGA29b: {
		defaultValue:
			"Yes, we do! Once we understand a bit about your project, we\u2019ll set up a short call to explore how we can help \u2014 no pressure, no strings.",
		placeholder: "Answer",
		title: "Answer 5",
		type: ControlType.String,
	},
	hkZIwkVzh: {
		defaultValue: "Can I reach out if I\u2019m not sure what I need yet?",
		displayTextArea: false,
		placeholder: "",
		title: "Question 6",
		type: ControlType.String,
	},
	rSVTsEqWp: {
		defaultValue:
			"Absolutely. Whether you have a clear brief or just a loose idea, we\u2019re happy to explore it with you. No pressure \u2014 just a conversation.",
		placeholder: "Answer",
		title: "Answer 6",
		type: ControlType.String,
	},
});
addFonts(
	Framersuqoqqwp5,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...LayoutJumpPreventerFonts,
		...FAQItemFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq-list
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqListFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var faq_list_default = ComponentWithRoot;
export { faq_list_default as default };
