// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e4fc90c95afaebc0 "Das Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone - Close' | 'Phone - Open' // Variant
 * padding?: any // Padding
 * logoImage?: {src: string, srcSet?: string, alt?: string} // Logo Image
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-UVSWH3FI.js";
import { stdin_default } from "./chunks/chunk-IYUBPT6N.js";
import "./chunks/chunk-I6BBA4QK.js";
import "./chunks/chunk-7CFDZMPZ.js";
import { routes } from "./chunks/chunk-BAX4IDEL.js";

// virtual:header
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/g1R0vpHlt6EkeS19op2S/PKeVvcImo07SIj7cP3vP/HGipsdwaE.js
import { jsx as _jsx4, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls4,
	ComponentViewportProvider,
	ControlType as ControlType4,
	cx as cx3,
	getFonts,
	getFontsFromSharedStyle,
	Image,
	Link,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS as withCSS3,
	withFX,
} from "unframer";
import { LayoutGroup, motion as motion3, MotionConfigContext } from "unframer";
import * as React3 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/9ajhXMTvNHa3o84QkAph/PbD4QdXIvghwk9ZrKeou/StopScroll_Prod.js
import { jsx as _jsx, Fragment as _Fragment } from "react/jsx-runtime";
import { addPropertyControls, ControlType } from "unframer";
function StopScroll(props) {
	const { toggle } = props;
	return toggle ? (
		<style
			suppressHydrationWarning={true}
			data-frameruni-stop-scroll={true}
		>{`html,body { overflow: hidden !important; }`}</style>
	) : (
		<_Fragment />
	);
}
StopScroll.displayName = "Stop Scroll";
addPropertyControls(StopScroll, {
	toggle: {
		type: ControlType.Boolean,
		title: "Block Scroll",
		description:
			"More components at [Framer University](https://frameruni.link/cc).",
	},
});

// /:https://framerusercontent.com/modules/s9ICNln7If6dbx787s8J/bsSFrd6i3uQgWvg7HD50/gpufTpA3b.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg suppressHydrationWarning={true} {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG
			suppressHydrationWarning={true}
			{...rest}
			layoutId={layoutId}
			ref={ref}
		>
			{children}
		</MotionSVG>
	) : (
		<svg suppressHydrationWarning={true} {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 12 0 L 0 12" fill="transparent" height="12px" id="qMvRy61Gj" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(6 6)" width="12px"/><path d="M 0 0 L 12 12" fill="transparent" height="12px" id="YX0AMSC6b" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(6 6)" width="12px"/></svg>';
var getProps = ({ color, height, id, width, width1, ...props }) => {
	return {
		...props,
		JEeZYcamG: width1 ?? props.JEeZYcamG ?? 2,
		P_DcoRcrY: color ?? props.P_DcoRcrY ?? "rgb(0, 0, 0)",
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className2,
		layoutId,
		variant,
		P_DcoRcrY,
		JEeZYcamG,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("2710857035", svg);
	return (
		<SVG
			suppressHydrationWarning={true}
			{...restProps}
			className={cx("framer-RiU4T", className2)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m973uw": P_DcoRcrY,
				"--js9iwy": JEeZYcamG,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use suppressHydrationWarning={true} href={href} />
		</SVG>
	);
});
var css2 = [
	`.framer-RiU4T { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css2, "framer-RiU4T");
Icon.displayName = "X";
var stdin_default2 = Icon;
addPropertyControls2(Icon, {
	P_DcoRcrY: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType2.Color,
	},
	JEeZYcamG: {
		defaultValue: 2,
		displayStepper: true,
		hidden: false,
		max: 16,
		min: 1,
		title: "Width",
		type: ControlType2.Number,
	},
});

// /:https://framerusercontent.com/modules/YdWAYttLVsISaAnwIelp/GPAVaCIRWsTPVHGxyEJl/S6Zx0Sff5.js
import { jsx as _jsx3 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls3,
	ControlType as ControlType3,
	cx as cx2,
	motion as motion2,
	useSVGTemplate as useSVGTemplate2,
	withCSS as withCSS2,
} from "unframer";
import * as React2 from "react";
import { forwardRef as forwardRef4 } from "react";
var mask2 = "var(--framer-icon-mask)";
var Base2 = /* @__PURE__ */ forwardRef4(function (props, ref) {
	return (
		<svg suppressHydrationWarning={true} {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG2 = motion2.create(Base2);
var SVG2 = /* @__PURE__ */ forwardRef4((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG2
			suppressHydrationWarning={true}
			{...rest}
			layoutId={layoutId}
			ref={ref}
		>
			{children}
		</MotionSVG2>
	) : (
		<svg suppressHydrationWarning={true} {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg2 =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 18 0 L 0 0" fill="transparent" height="1px" id="zeemTwPt5" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(3 5)" width="18px"/><path d="M 12 0 L 0 0" fill="transparent" height="1px" id="nbkh2NJv8" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(9 12)" width="12px"/><path d="M 14 0 L 0 0" fill="transparent" height="1px" id="OmBMv8zkp" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(7 19)" width="14px"/></svg>';
var getProps2 = ({ color, height, id, width, width1, ...props }) => {
	return {
		...props,
		JEeZYcamG: width1 ?? props.JEeZYcamG ?? 2,
		P_DcoRcrY: color ?? props.P_DcoRcrY ?? "rgb(0, 0, 0)",
	};
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const {
		style,
		className: className2,
		layoutId,
		variant,
		P_DcoRcrY,
		JEeZYcamG,
		...restProps
	} = getProps2(props);
	const href = useSVGTemplate2("1002719317", svg2);
	return (
		<SVG2
			suppressHydrationWarning={true}
			{...restProps}
			className={cx2("framer-jZJj6", className2)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m973uw": P_DcoRcrY,
				"--js9iwy": JEeZYcamG,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use suppressHydrationWarning={true} href={href} />
		</SVG2>
	);
});
var css3 = [
	`.framer-jZJj6 { -webkit-mask: ${mask2}; aspect-ratio: 1; display: block; mask: ${mask2}; width: 24px; }`,
];
var Icon2 = withCSS2(Component2, css3, "framer-jZJj6");
Icon2.displayName = "Text Align End";
var stdin_default3 = Icon2;
addPropertyControls3(Icon2, {
	P_DcoRcrY: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType3.Color,
	},
	JEeZYcamG: {
		defaultValue: 2,
		displayStepper: true,
		hidden: false,
		max: 16,
		min: 1,
		title: "Width",
		type: ControlType3.Number,
	},
});

// /:https://framerusercontent.com/modules/g1R0vpHlt6EkeS19op2S/PKeVvcImo07SIj7cP3vP/HGipsdwaE.js
var StopScrollFonts = getFonts(StopScroll);
var ButtonFonts = getFonts(stdin_default);
var TextAlignEndFonts = getFonts(stdin_default3);
var XFonts = getFonts(stdin_default2);
var MotionHeaderWithFX = withFX(motion3.header);
var cycleOrder = ["yGjoK0wcr", "IIjKFVLnd", "yvOJ9Y7lM"];
var serializationHash = "framer-SNz9W";
var variantClassNames = {
	IIjKFVLnd: "framer-v-ldlxq2",
	yGjoK0wcr: "framer-v-yvx07n",
	yvOJ9Y7lM: "framer-v-jbezwi",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.6,
	ease: [0.35, 0, 0, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: -46,
};
var transition2 = {
	delay: 0,
	duration: 0.8,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var transition3 = {
	delay: 0.2,
	duration: 0.8,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var numberToPixelString = (value) => {
	if (typeof value !== "number") return value;
	if (!Number.isFinite(value)) return void 0;
	return Math.max(0, value) + "px";
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var transition4 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var transition5 = {
	damping: 60,
	delay: 0.4,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var transition6 = {
	damping: 60,
	delay: 0.46,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var transition7 = {
	damping: 60,
	delay: 0.54,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var Variants = motion3.create(React3.Fragment);
var humanReadableVariantMap = {
	"Phone - Close": "IIjKFVLnd",
	"Phone - Open": "yvOJ9Y7lM",
	Desktop: "yGjoK0wcr",
};
var getProps3 = ({ height, id, logoImage, padding, width, ...props }) => {
	return {
		...props,
		ayDn0h1rL: padding ?? props.ayDn0h1rL ?? "0px 32px 0px 32px",
		CYyMJFFMg: logoImage ?? props.CYyMJFFMg,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "yGjoK0wcr",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		ayDn0h1rL: ayDn0h1rL2,
		CYyMJFFMg: CYyMJFFMg2,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "yGjoK0wcr",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTaprlas1s = activeVariantCallback(async (...args) => {
		setVariant("IIjKFVLnd");
	});
	const onTap1ovmjfh = activeVariantCallback(async (...args) => {
		setVariant("yvOJ9Y7lM");
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx3(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "yvOJ9Y7lM") return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (["IIjKFVLnd", "yvOJ9Y7lM"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (["IIjKFVLnd", "yvOJ9Y7lM"].includes(baseVariant)) return false;
		return true;
	};
	const router = useRouter();
	const isDisplayed3 = () => {
		if (baseVariant === "IIjKFVLnd") return true;
		return false;
	};
	const isDisplayed4 = () => {
		if (baseVariant === "IIjKFVLnd") return false;
		return true;
	};
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition
					suppressHydrationWarning={true}
					value={transition2}
					{...addPropertyOverrides(
						{
							IIjKFVLnd: {
								value: transition3,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<MotionHeaderWithFX
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={false}
						__framer__scrollDirection={{
							direction: "down",
							target: animation,
						}}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx3(
							scopingClassNames,
							"framer-yvx07n",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"yGjoK0wcr"}
						ref={refBinding}
						style={{
							backdropFilter: "blur(15px)",
							background:
								"linear-gradient(180deg, rgba(255, 255, 255, 0.06) 0%, rgba(255, 255, 255, 0) 100%)",
							mask: "linear-gradient(0deg, rgba(0,0,0,0) 0%, rgba(0, 0, 0, 0.85) 20.317778716216218%, rgba(0,0,0,1) 34.1163429054054%) add",
							WebkitBackdropFilter: "blur(15px)",
							WebkitMask:
								"linear-gradient(0deg, rgba(0,0,0,0) 0%, rgba(0, 0, 0, 0.85) 20.317778716216218%, rgba(0,0,0,1) 34.1163429054054%) add",
							...style,
						}}
						variants={{
							IIjKFVLnd: {
								mask: "none",
								WebkitMask: "none",
							},
							yvOJ9Y7lM: {
								mask: "none",
								WebkitMask: "none",
							},
						}}
						{...addPropertyOverrides(
							{
								IIjKFVLnd: {
									"data-framer-name": "Phone - Close",
								},
								yvOJ9Y7lM: {
									"data-framer-name": "Phone - Open",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<ComponentViewportProvider suppressHydrationWarning={true}>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-1pubrmp-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"pQDLO9dzL-container"}
									nodeId={"pQDLO9dzL"}
									rendersWithMotion={true}
									scopeId={"HGipsdwaE"}
								>
									<StopScroll
										suppressHydrationWarning={true}
										height={"100%"}
										id={"pQDLO9dzL"}
										layoutId={"pQDLO9dzL"}
										toggle={true}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{isDisplayed1() && (
							<motion3.div
								suppressHydrationWarning={true}
								className={"framer-9v7t4b"}
								data-framer-name={"Mobile Background"}
								layoutDependency={layoutDependency}
								layoutId={"HZ6fsGH7O"}
								style={{
									backgroundColor:
										"var(--token-e2a325f5-5d1b-4d4f-b9bb-f0704bd5c816, rgb(245, 245, 245))",
								}}
								{...addPropertyOverrides(
									{
										yvOJ9Y7lM: {
											"data-highlight": true,
											onTap: onTaprlas1s,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
						<motion3.div
							suppressHydrationWarning={true}
							className={"framer-wjyq26"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"OVixzJ733"}
							style={{
								"--11tghi9": numberToPixelString(ayDn0h1rL2),
							}}
						>
							<motion3.div
								suppressHydrationWarning={true}
								className={"framer-1vpnqu3"}
								data-framer-name={"Main Container"}
								layoutDependency={layoutDependency}
								layoutId={"Zb8cptMY_"}
							>
								<Link
									suppressHydrationWarning={true}
									href={{
										webPageId: "augiA20Il",
									}}
									motionChild={true}
									nodeId={"pG6Exqw3M"}
									openInNewTab={false}
									scopeId={"HGipsdwaE"}
								>
									<motion3.a
										suppressHydrationWarning={true}
										aria-label={"Logo"}
										className={"framer-11u6g9f framer-1ezgeb6"}
										data-framer-name={"Logo Container"}
										layoutDependency={layoutDependency}
										layoutId={"pG6Exqw3M"}
									>
										<Image
											suppressHydrationWarning={true}
											as={"figure"}
											background={{
												alt: "",
												fit: "fit",
												pixelHeight: 52,
												pixelWidth: 239,
												sizes: "83px",
												...toResponsiveImage(CYyMJFFMg2),
												...{
													positionX: "left",
													positionY: "center",
												},
											}}
											className={"framer-491z6g"}
											layoutDependency={layoutDependency}
											layoutId={"BcsTjGLaE"}
											{...addPropertyOverrides(
												{
													IIjKFVLnd: {
														background: {
															alt: "",
															fit: "fit",
															pixelHeight: 52,
															pixelWidth: 239,
															sizes: "92.2222px",
															...toResponsiveImage(CYyMJFFMg2),
															...{
																positionX: "left",
																positionY: "center",
															},
														},
													},
													yvOJ9Y7lM: {
														background: {
															alt: "",
															fit: "fit",
															pixelHeight: 52,
															pixelWidth: 239,
															sizes: "92.2222px",
															...toResponsiveImage(CYyMJFFMg2),
															...{
																positionX: "left",
																positionY: "center",
															},
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</motion3.a>
								</Link>
								{isDisplayed2() && (
									<motion3.nav
										suppressHydrationWarning={true}
										className={"framer-1j12gtt"}
										data-framer-name={"Desktop Links"}
										layoutDependency={layoutDependency}
										layoutId={"i694AiaQd"}
									>
										<ResolveLinks
											suppressHydrationWarning={true}
											links={[
												{
													href: {
														webPageId: "iN6FkC809",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks) => (
												<ComponentViewportProvider
													suppressHydrationWarning={true}
													height={44}
												>
													<SmartComponentScopedContainer
														suppressHydrationWarning={true}
														className={"framer-b2oojy-container"}
														layoutDependency={layoutDependency}
														layoutId={"Eqyr8806k-container"}
														nodeId={"Eqyr8806k"}
														rendersWithMotion={true}
														scopeId={"HGipsdwaE"}
													>
														{_jsx4(stdin_default, {
															suppressHydrationWarning: true,
															Ge1cwLZdF: false,
															height: "100%",
															id: "Eqyr8806k",
															IQJfIgKUA: resolvedLinks[0],
															kUCdcilHJ: "Projects",
															layoutId: "Eqyr8806k",
															variant: matchVariant("VeSzDgRX5"),
															width: "100%",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											suppressHydrationWarning={true}
											links={[
												{
													href: {
														webPageId: "C2ssBH5Fy",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks1) => (
												<ComponentViewportProvider
													suppressHydrationWarning={true}
													height={44}
												>
													<SmartComponentScopedContainer
														suppressHydrationWarning={true}
														className={"framer-1vvq19j-container"}
														layoutDependency={layoutDependency}
														layoutId={"jpt9Zelrv-container"}
														nodeId={"jpt9Zelrv"}
														rendersWithMotion={true}
														scopeId={"HGipsdwaE"}
													>
														{_jsx4(stdin_default, {
															suppressHydrationWarning: true,
															Ge1cwLZdF: false,
															height: "100%",
															id: "jpt9Zelrv",
															IQJfIgKUA: resolvedLinks1[0],
															kUCdcilHJ: "Journal",
															layoutId: "jpt9Zelrv",
															variant: matchVariant("VeSzDgRX5"),
															width: "100%",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											suppressHydrationWarning={true}
											links={[
												{
													href: {
														webPageId: "xN0X4eqxL",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks2) => (
												<ComponentViewportProvider
													suppressHydrationWarning={true}
													height={44}
												>
													<SmartComponentScopedContainer
														suppressHydrationWarning={true}
														className={"framer-h9k5ew-container"}
														layoutDependency={layoutDependency}
														layoutId={"GkYc4P8GO-container"}
														nodeId={"GkYc4P8GO"}
														rendersWithMotion={true}
														scopeId={"HGipsdwaE"}
													>
														{_jsx4(stdin_default, {
															suppressHydrationWarning: true,
															Ge1cwLZdF: false,
															height: "100%",
															id: "GkYc4P8GO",
															IQJfIgKUA: resolvedLinks2[0],
															kUCdcilHJ: "About",
															layoutId: "GkYc4P8GO",
															variant: matchVariant("VeSzDgRX5"),
															width: "100%",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											suppressHydrationWarning={true}
											links={[
												{
													href: {
														webPageId: "enVrPLO_o",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks3) => (
												<ComponentViewportProvider
													suppressHydrationWarning={true}
													height={44}
												>
													<SmartComponentScopedContainer
														suppressHydrationWarning={true}
														className={"framer-oab47d-container"}
														layoutDependency={layoutDependency}
														layoutId={"DwcD1Jpkc-container"}
														nodeId={"DwcD1Jpkc"}
														rendersWithMotion={true}
														scopeId={"HGipsdwaE"}
													>
														{_jsx4(stdin_default, {
															suppressHydrationWarning: true,
															Ge1cwLZdF: true,
															height: "100%",
															id: "DwcD1Jpkc",
															IQJfIgKUA: resolvedLinks3[0],
															kUCdcilHJ: "Contact",
															layoutId: "DwcD1Jpkc",
															variant: matchVariant("VeSzDgRX5"),
															width: "100%",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
									</motion3.nav>
								)}
								{isDisplayed1() && (
									<motion3.div
										suppressHydrationWarning={true}
										className={"framer-1o1q3q8"}
										data-framer-name={"Mobile links"}
										layoutDependency={layoutDependency}
										layoutId={"cSNTqgYMt"}
										style={{
											opacity: 1,
										}}
										variants={{
											IIjKFVLnd: {
												opacity: 0,
											},
											yvOJ9Y7lM: {
												opacity: 1,
											},
										}}
									>
										<motion3.div
											suppressHydrationWarning={true}
											className={"framer-x8z7ct"}
											data-framer-name={"Mobile links wrapper"}
											layoutDependency={layoutDependency}
											layoutId={"eZbnrn6x_"}
										>
											<Transition
												suppressHydrationWarning={true}
												{...addPropertyOverrides(
													{
														IIjKFVLnd: {
															value: transition4,
														},
														yvOJ9Y7lM: {
															value: transition5,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<Link
													suppressHydrationWarning={true}
													href={{
														webPageId: "iN6FkC809",
													}}
													motionChild={true}
													nodeId={"vT9_6jqiw"}
													openInNewTab={false}
													scopeId={"HGipsdwaE"}
												>
													<motion3.a
														suppressHydrationWarning={true}
														className={"framer-1ixtibt framer-1ezgeb6"}
														data-framer-name={"Projects"}
														layoutDependency={layoutDependency}
														layoutId={"vT9_6jqiw"}
														{...addPropertyOverrides(
															{
																yvOJ9Y7lM: {
																	"data-highlight": true,
																	onTap: onTaprlas1s,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<RichText
															suppressHydrationWarning={true}
															__fromCanvasComponent={true}
															className={"framer-1buj0hc"}
															fonts={["Inter"]}
															layoutDependency={layoutDependency}
															layoutId={"U0j63Jkjb"}
															style={{
																"--framer-link-text-color": "rgb(0, 153, 255)",
																"--framer-link-text-decoration": "underline",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React3.Fragment>
																<motion3.h1
																	suppressHydrationWarning={true}
																	className={"framer-styles-preset-gwzd60"}
																	data-styles-preset={"nzncKCFi1"}
																>
																	{"Projects"}
																</motion3.h1>
															</React3.Fragment>
														</RichText>
													</motion3.a>
												</Link>
											</Transition>
											<Transition
												suppressHydrationWarning={true}
												{...addPropertyOverrides(
													{
														IIjKFVLnd: {
															value: transition4,
														},
														yvOJ9Y7lM: {
															value: transition5,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<Link
													suppressHydrationWarning={true}
													href={{
														webPageId: "C2ssBH5Fy",
													}}
													motionChild={true}
													nodeId={"pBHhSCQPb"}
													openInNewTab={false}
													scopeId={"HGipsdwaE"}
												>
													<motion3.a
														suppressHydrationWarning={true}
														className={"framer-2ipyd9 framer-1ezgeb6"}
														data-framer-name={"Journal"}
														layoutDependency={layoutDependency}
														layoutId={"pBHhSCQPb"}
														{...addPropertyOverrides(
															{
																yvOJ9Y7lM: {
																	"data-highlight": true,
																	onTap: onTaprlas1s,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<RichText
															suppressHydrationWarning={true}
															__fromCanvasComponent={true}
															className={"framer-bg66hu"}
															fonts={["Inter"]}
															layoutDependency={layoutDependency}
															layoutId={"gBP7NJYvM"}
															style={{
																"--framer-link-text-color": "rgb(0, 153, 255)",
																"--framer-link-text-decoration": "underline",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React3.Fragment>
																<motion3.h1
																	suppressHydrationWarning={true}
																	className={"framer-styles-preset-gwzd60"}
																	data-styles-preset={"nzncKCFi1"}
																>
																	{"Journal"}
																</motion3.h1>
															</React3.Fragment>
														</RichText>
													</motion3.a>
												</Link>
											</Transition>
											<Transition
												suppressHydrationWarning={true}
												{...addPropertyOverrides(
													{
														IIjKFVLnd: {
															value: transition4,
														},
														yvOJ9Y7lM: {
															value: transition6,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<Link
													suppressHydrationWarning={true}
													href={{
														webPageId: "xN0X4eqxL",
													}}
													motionChild={true}
													nodeId={"Re3MhGX22"}
													openInNewTab={false}
													scopeId={"HGipsdwaE"}
												>
													<motion3.a
														suppressHydrationWarning={true}
														className={"framer-yovldd framer-1ezgeb6"}
														data-framer-name={"About"}
														layoutDependency={layoutDependency}
														layoutId={"Re3MhGX22"}
														{...addPropertyOverrides(
															{
																yvOJ9Y7lM: {
																	"data-highlight": true,
																	onTap: onTaprlas1s,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<RichText
															suppressHydrationWarning={true}
															__fromCanvasComponent={true}
															className={"framer-b4xd81"}
															fonts={["Inter"]}
															layoutDependency={layoutDependency}
															layoutId={"Fre5Ej818"}
															style={{
																"--framer-link-text-color": "rgb(0, 153, 255)",
																"--framer-link-text-decoration": "underline",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React3.Fragment>
																<motion3.h1
																	suppressHydrationWarning={true}
																	className={"framer-styles-preset-gwzd60"}
																	data-styles-preset={"nzncKCFi1"}
																>
																	{"About"}
																</motion3.h1>
															</React3.Fragment>
														</RichText>
													</motion3.a>
												</Link>
											</Transition>
											<Transition
												suppressHydrationWarning={true}
												{...addPropertyOverrides(
													{
														IIjKFVLnd: {
															value: transition4,
														},
														yvOJ9Y7lM: {
															value: transition7,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<Link
													suppressHydrationWarning={true}
													href={{
														webPageId: "enVrPLO_o",
													}}
													motionChild={true}
													nodeId={"TgpcTky1c"}
													openInNewTab={false}
													scopeId={"HGipsdwaE"}
												>
													<motion3.a
														suppressHydrationWarning={true}
														className={"framer-h8pl4w framer-1ezgeb6"}
														data-framer-name={"Contact"}
														layoutDependency={layoutDependency}
														layoutId={"TgpcTky1c"}
														{...addPropertyOverrides(
															{
																yvOJ9Y7lM: {
																	"data-highlight": true,
																	onTap: onTaprlas1s,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<RichText
															suppressHydrationWarning={true}
															__fromCanvasComponent={true}
															className={"framer-tcc53d"}
															data-framer-name={"Contact"}
															fonts={["Inter"]}
															layoutDependency={layoutDependency}
															layoutId={"wFWRzfOc9"}
															style={{
																"--framer-link-text-color": "rgb(0, 153, 255)",
																"--framer-link-text-decoration": "underline",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
															{...addPropertyOverrides(
																{
																	IIjKFVLnd: {
																		children: (
																			<React3.Fragment>
																				<motion3.h1
																					suppressHydrationWarning={true}
																					className={
																						"framer-styles-preset-gwzd60"
																					}
																					data-styles-preset={"nzncKCFi1"}
																				>
																					{"Contact"}
																				</motion3.h1>
																			</React3.Fragment>
																		),
																	},
																	yvOJ9Y7lM: {
																		children: (
																			<React3.Fragment>
																				<motion3.h1
																					suppressHydrationWarning={true}
																					className={
																						"framer-styles-preset-gwzd60"
																					}
																					data-styles-preset={"nzncKCFi1"}
																				>
																					{"Contact"}
																				</motion3.h1>
																			</React3.Fragment>
																		),
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														>
															<React3.Fragment>
																<motion3.h1
																	suppressHydrationWarning={true}
																	className={"framer-styles-preset-gwzd60"}
																	data-styles-preset={"nzncKCFi1"}
																>
																	{"Get in touch"}
																</motion3.h1>
															</React3.Fragment>
														</RichText>
													</motion3.a>
												</Link>
											</Transition>
										</motion3.div>
									</motion3.div>
								)}
								{isDisplayed1() && (
									<motion3.div
										suppressHydrationWarning={true}
										className={"framer-1pb2sfx"}
										data-framer-name={"Mobile Hamburger"}
										layoutDependency={layoutDependency}
										layoutId={"ODUaDPRBN"}
										{...addPropertyOverrides(
											{
												IIjKFVLnd: {
													"data-highlight": true,
													onTap: onTap1ovmjfh,
												},
												yvOJ9Y7lM: {
													"data-highlight": true,
													onTap: onTaprlas1s,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<motion3.div
											suppressHydrationWarning={true}
											className={"framer-fhjn3h"}
											data-framer-name={"Inner Container"}
											layoutDependency={layoutDependency}
											layoutId={"nbD9QV8c3"}
										>
											<motion3.div
												suppressHydrationWarning={true}
												className={"framer-17dt1d7"}
												data-framer-name={"Hamburger wrapper"}
												layoutDependency={layoutDependency}
												layoutId={"D9CLwslMZ"}
											>
												{isDisplayed3() &&
													_jsx4(stdin_default3, {
														suppressHydrationWarning: true,
														animated: true,
														className: "framer-42a2tt",
														layoutDependency,
														layoutId: "zErz36juv",
														style: {
															"--1m973uw":
																"var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(10, 10, 10))",
															"--js9iwy": 2.5,
														},
													})}
												{isDisplayed4() &&
													_jsx4(stdin_default2, {
														suppressHydrationWarning: true,
														animated: true,
														className: "framer-1tx8yvr",
														layoutDependency,
														layoutId: "oMUNPMaNg",
														style: {
															"--1m973uw":
																"var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(10, 10, 10))",
															"--js9iwy": 2.5,
														},
													})}
											</motion3.div>
										</motion3.div>
									</motion3.div>
								)}
							</motion3.div>
						</motion3.div>
					</MotionHeaderWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-SNz9W.framer-1ezgeb6, .framer-SNz9W .framer-1ezgeb6 { display: block; }",
	".framer-SNz9W.framer-yvx07n { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 12px 0px 12px 0px; position: relative; width: 1200px; }",
	".framer-SNz9W .framer-1pubrmp-container { flex: none; height: auto; left: -5px; position: absolute; top: -5px; width: auto; z-index: 1; }",
	".framer-SNz9W .framer-9v7t4b { flex: none; height: calc(var(--framer-viewport-height, 100vh) * 0.5); left: 0px; overflow: visible; position: absolute; top: -600px; width: 100%; z-index: 0; }",
	".framer-SNz9W .framer-wjyq26 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; max-width: 1520px; overflow: visible; padding: var(--11tghi9); position: relative; width: 100%; }",
	".framer-SNz9W .framer-1vpnqu3 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 1px; z-index: 1; }",
	".framer-SNz9W .framer-11u6g9f { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-SNz9W .framer-491z6g { aspect-ratio: 4.611111111111111 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 18px); overflow: visible; position: relative; width: 83px; }",
	".framer-SNz9W .framer-1j12gtt { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-SNz9W .framer-b2oojy-container, .framer-SNz9W .framer-1vvq19j-container, .framer-SNz9W .framer-h9k5ew-container, .framer-SNz9W .framer-oab47d-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-SNz9W .framer-1o1q3q8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: calc(var(--framer-viewport-height, 100vh) * 1); justify-content: center; overflow: visible; padding: 0px; position: absolute; right: -400px; top: 0px; width: 100%; z-index: 1; }",
	".framer-SNz9W .framer-x8z7ct { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: 100%; justify-content: center; padding: 0px; position: relative; width: 1px; }",
	".framer-SNz9W .framer-1ixtibt, .framer-SNz9W .framer-2ipyd9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-SNz9W .framer-1buj0hc, .framer-SNz9W .framer-bg66hu, .framer-SNz9W .framer-b4xd81, .framer-SNz9W .framer-tcc53d { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-SNz9W .framer-yovldd, .framer-SNz9W .framer-h8pl4w { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-SNz9W .framer-1pb2sfx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; z-index: 10; }",
	".framer-SNz9W .framer-fhjn3h { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; padding: 0px; position: relative; width: min-content; }",
	".framer-SNz9W .framer-17dt1d7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; min-height: 200px; min-width: 19px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; }",
	".framer-SNz9W .framer-42a2tt { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
	".framer-SNz9W .framer-1tx8yvr { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: absolute; right: -25px; top: 0px; width: 24px; z-index: 1; }",
	".framer-SNz9W.framer-v-ldlxq2.framer-yvx07n, .framer-SNz9W.framer-v-jbezwi.framer-yvx07n { width: 390px; }",
	".framer-SNz9W.framer-v-ldlxq2 .framer-9v7t4b { height: 100%; pointer-events: none; top: -200px; }",
	".framer-SNz9W.framer-v-ldlxq2 .framer-wjyq26, .framer-SNz9W.framer-v-jbezwi .framer-wjyq26 { max-width: 100%; }",
	".framer-SNz9W.framer-v-ldlxq2 .framer-11u6g9f { z-index: 2; }",
	".framer-SNz9W.framer-v-ldlxq2 .framer-491z6g, .framer-SNz9W.framer-v-jbezwi .framer-491z6g { height: var(--framer-aspect-ratio-supported, 20px); width: 92px; }",
	".framer-SNz9W.framer-v-ldlxq2 .framer-1o1q3q8 { height: min-content; left: 0px; pointer-events: none; right: unset; top: -600px; }",
	".framer-SNz9W.framer-v-ldlxq2 .framer-x8z7ct { height: min-content; order: 0; pointer-events: none; z-index: 10; }",
	".framer-SNz9W.framer-v-ldlxq2 .framer-1pb2sfx, .framer-SNz9W.framer-v-jbezwi .framer-2ipyd9, .framer-SNz9W.framer-v-jbezwi .framer-yovldd, .framer-SNz9W.framer-v-jbezwi .framer-h8pl4w, .framer-SNz9W.framer-v-jbezwi .framer-1pb2sfx { cursor: pointer; }",
	".framer-SNz9W.framer-v-ldlxq2 .framer-17dt1d7, .framer-SNz9W.framer-v-jbezwi .framer-17dt1d7 { min-height: unset; min-width: unset; order: 0; }",
	".framer-SNz9W.framer-v-jbezwi .framer-9v7t4b { cursor: pointer; height: calc(var(--framer-viewport-height, 100vh) * 1); pointer-events: auto; top: 0px; }",
	".framer-SNz9W.framer-v-jbezwi .framer-1o1q3q8 { height: min-content; left: 0px; pointer-events: auto; right: unset; top: 100px; }",
	".framer-SNz9W.framer-v-jbezwi .framer-x8z7ct { height: min-content; order: 0; pointer-events: auto; z-index: 10; }",
	".framer-SNz9W.framer-v-jbezwi .framer-1ixtibt { cursor: pointer; flex-direction: column; }",
	".framer-SNz9W.framer-v-jbezwi .framer-1tx8yvr { position: relative; right: unset; top: unset; }",
	...css,
];
var FramerHGipsdwaE = withCSS3(Component3, css4, "framer-SNz9W");
var stdin_default4 = FramerHGipsdwaE;
FramerHGipsdwaE.displayName = "Header";
FramerHGipsdwaE.defaultProps = {
	height: 44,
	width: 1200,
};
addPropertyControls4(FramerHGipsdwaE, {
	variant: {
		options: ["yGjoK0wcr", "IIjKFVLnd", "yvOJ9Y7lM"],
		optionTitles: ["Desktop", "Phone - Close", "Phone - Open"],
		title: "Variant",
		type: ControlType4.Enum,
	},
	ayDn0h1rL: {
		defaultValue: "0px 32px 0px 32px",
		title: "Padding",
		type: ControlType4.Padding,
	},
	CYyMJFFMg: {
		title: "Logo Image",
		type: ControlType4.ResponsiveImage,
	},
});
addFonts(
	FramerHGipsdwaE,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...StopScrollFonts,
		...ButtonFonts,
		...TextAlignEndFonts,
		...XFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:header
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "IIjKFVLnd",
	xl: "yGjoK0wcr",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeaderFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var header_default = ComponentWithRoot;
export { header_default as default };
