// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e4fc90c95afaebc0 "Das Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Horizontal' // Variant
 * hasStars?: boolean // Has Stars
 * title?: string // Title
 * text?: string // Text
 * hasButton?: boolean // Has Button
 * buttonTitle?: string // Button Title
 * buttonLink?: string // Button Link
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-EZ24G2IO.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-4VNGL5SF.js";
import { stdin_default } from "./chunks/chunk-IYUBPT6N.js";
import "./chunks/chunk-I6BBA4QK.js";
import "./chunks/chunk-7CFDZMPZ.js";
import { className, css, fonts } from "./chunks/chunk-B5JEBSFU.js";
import { routes } from "./chunks/chunk-BAX4IDEL.js";

// virtual:info-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8xMfrDCsegeQyLNEntLZ/nXUk914wnsR9R7zurqoU/GPYS2Gy7Z.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var StarsFonts = getFonts(stdin_default2);
var ButtonFonts = getFonts(stdin_default);
var cycleOrder = ["hLi_wicOR", "RJb3qbWRv"];
var serializationHash = "framer-gdbKZ";
var variantClassNames = {
	hLi_wicOR: "framer-v-aswrdx",
	RJb3qbWRv: "framer-v-14d4ay8",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "hLi_wicOR",
	Horizontal: "RJb3qbWRv",
};
var getProps = ({
	buttonLink,
	buttonTitle,
	hasButton,
	hasStars,
	height,
	id,
	text,
	title,
	width,
	...props
}) => {
	return {
		...props,
		Ir3I983Le: hasStars ?? props.Ir3I983Le,
		K3jqM1vq5: buttonTitle ?? props.K3jqM1vq5 ?? "All services",
		QgBlvPuVS:
			text ??
			props.QgBlvPuVS ??
			"Reach out anytime. We're happy to answer any questions before you commit to working together.",
		V3Zj_duJ2: title ?? props.V3Zj_duJ2 ?? "Not finding what you need? ",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "hLi_wicOR",
		YYDGQoKHR: hasButton ?? props.YYDGQoKHR ?? true,
		ZEvii8LH6: buttonLink ?? props.ZEvii8LH6,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		Ir3I983Le: Ir3I983Le2,
		V3Zj_duJ2: V3Zj_duJ22,
		QgBlvPuVS: QgBlvPuVS2,
		YYDGQoKHR: YYDGQoKHR2,
		K3jqM1vq5: K3jqM1vq52,
		ZEvii8LH6: ZEvii8LH62,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "hLi_wicOR",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const visible = isSet(V3Zj_duJ22);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-aswrdx",
							className3,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"hLi_wicOR"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								RJb3qbWRv: {
									"data-framer-name": "Horizontal",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1s33spl"}
							data-framer-name={"Titles"}
							layoutDependency={layoutDependency}
							layoutId={"igdXRWskl"}
						>
							{Ir3I983Le2 !== false && (
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={200}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 200) - 0 - 58.4) / 2 +
											0 +
											0) +
										0 +
										18
									}
									{...addPropertyOverrides(
										{
											RJb3qbWRv: {
												y:
													(componentViewport?.y || 0) +
													0 +
													((componentViewport?.height || 200) - 0 - 58.4) +
													0 +
													18,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-aa7fky-container"}
										layoutDependency={layoutDependency}
										layoutId={"WWc1whEaR-container"}
										nodeId={"WWc1whEaR"}
										rendersWithMotion={true}
										scopeId={"GPYS2Gy7Z"}
									>
										{_jsx(stdin_default2, {
											suppressHydrationWarning: true,
											height: "100%",
											id: "WWc1whEaR",
											layoutId: "WWc1whEaR",
											variant: matchVariant("ZZvUJpjX4"),
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
							{visible !== false && (
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-d6eig2"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"vPgTqDG6Z"}
									style={{
										"--extracted-1w1cjl5":
											"var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(10, 10, 10))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={V3Zj_duJ22}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h6
											suppressHydrationWarning={true}
											className={"framer-styles-preset-9d6j7p"}
											data-styles-preset={"Mk5Vgse8Z"}
											style={{
												"--framer-text-color":
													"var(--extracted-1w1cjl5, var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(10, 10, 10)))",
											}}
										>
											{"Not finding what you need? "}
										</motion.h6>
									</React.Fragment>
								</RichText>
							)}
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-hx16k"}
								data-framer-name={"Description"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"VlE_KGSfY"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={QgBlvPuVS2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										suppressHydrationWarning={true}
										className={"framer-styles-preset-26kq2w"}
										data-styles-preset={"zuIVYXLhn"}
										dir={"auto"}
									>
										{
											"Reach out anytime. We're happy to answer any questions before you commit to working together."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						{YYDGQoKHR2 !== false && (
							<ComponentViewportProvider
								suppressHydrationWarning={true}
								height={200}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 200) - 0 - 58.4) / 2 +
										58.4 +
										24)
								}
								{...addPropertyOverrides(
									{
										RJb3qbWRv: {
											y:
												(componentViewport?.y || 0) +
												0 +
												((componentViewport?.height || 200) - 0 - 200),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-166igec-container"}
									layoutDependency={layoutDependency}
									layoutId={"Aj4XPFTGA-container"}
									nodeId={"Aj4XPFTGA"}
									rendersWithMotion={true}
									scopeId={"GPYS2Gy7Z"}
								>
									{_jsx(stdin_default, {
										suppressHydrationWarning: true,
										Ge1cwLZdF: true,
										height: "100%",
										id: "Aj4XPFTGA",
										IQJfIgKUA: ZEvii8LH62,
										kUCdcilHJ: K3jqM1vq52,
										layoutId: "Aj4XPFTGA",
										variant: matchVariant("qIg3fad0d"),
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-gdbKZ.framer-1kqmc1b, .framer-gdbKZ .framer-1kqmc1b { display: block; }",
	".framer-gdbKZ.framer-aswrdx { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 369px; }",
	".framer-gdbKZ .framer-1s33spl { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-gdbKZ .framer-aa7fky-container, .framer-gdbKZ .framer-166igec-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-gdbKZ .framer-d6eig2 { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
	".framer-gdbKZ .framer-hx16k { --framer-text-wrap-override: balance; flex: none; height: auto; max-width: 300px; position: relative; width: auto; z-index: 1; }",
	".framer-gdbKZ.framer-v-14d4ay8.framer-aswrdx { align-content: flex-end; align-items: flex-end; flex-direction: row; width: 877px; }",
	".framer-gdbKZ.framer-v-14d4ay8 .framer-1s33spl { flex: 1 0 0px; width: 1px; }",
	...css2,
	...css,
];
var FramerGPYS2Gy7Z = withCSS(Component, css3, "framer-gdbKZ");
var stdin_default3 = FramerGPYS2Gy7Z;
FramerGPYS2Gy7Z.displayName = "Info Card";
FramerGPYS2Gy7Z.defaultProps = {
	height: 187,
	width: 369,
};
addPropertyControls(FramerGPYS2Gy7Z, {
	variant: {
		options: ["hLi_wicOR", "RJb3qbWRv"],
		optionTitles: ["Default", "Horizontal"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Ir3I983Le: {
		defaultValue: false,
		title: "Has Stars",
		type: ControlType.Boolean,
	},
	V3Zj_duJ2: {
		defaultValue: "Not finding what you need? ",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	QgBlvPuVS: {
		defaultValue:
			"Reach out anytime. We're happy to answer any questions before you commit to working together.",
		displayTextArea: true,
		title: "Text",
		type: ControlType.String,
	},
	YYDGQoKHR: {
		defaultValue: true,
		title: "Has Button",
		type: ControlType.Boolean,
	},
	K3jqM1vq5: {
		defaultValue: "All services",
		displayTextArea: false,
		title: "Button Title",
		type: ControlType.String,
	},
	ZEvii8LH6: {
		title: "Button Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerGPYS2Gy7Z,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...StarsFonts,
		...ButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:info-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "RJb3qbWRv",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders InfoCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var info_card_default = ComponentWithRoot;
export { info_card_default as default };
