// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e4fc90c95afaebc0 "Das Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * hasBadge?: boolean // Has Badge
 * badge?: string // Badge
 * title?: string // Title
 * text?: string // Text
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-UVSWH3FI.js";
import { stdin_default } from "./chunks/chunk-GHRXF5NR.js";
import "./chunks/chunk-EANZ46VA.js";
import "./chunks/chunk-7CFDZMPZ.js";
import { className, css, fonts } from "./chunks/chunk-B5JEBSFU.js";
import { routes } from "./chunks/chunk-BAX4IDEL.js";

// virtual:journal-header
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/lgLjhgHJit4oMNFr243y/41w55f0OLFkzGkhpWIkm/FHiW2mJr3.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var BadgeFonts = getFonts(stdin_default);
var serializationHash = "framer-YzGE6";
var variantClassNames = {
	PwTxsQv03: "framer-v-127hl5u",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	badge,
	hasBadge,
	height,
	id,
	text,
	title,
	width,
	...props
}) => {
	return {
		...props,
		Ae7hp2qP5: badge ?? props.Ae7hp2qP5 ?? "Who we are",
		Dbl5KbMB6: hasBadge ?? props.Dbl5KbMB6 ?? true,
		ltby7Y5nE:
			text ??
			props.ltby7Y5nE ??
			"We're a creative agency focused on clarity and meaning. We build timeless foundations.",
		Tb0wSzZ9C: title ?? props.Tb0wSzZ9C ?? "The Team",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		Dbl5KbMB6: Dbl5KbMB62,
		Ae7hp2qP5: Ae7hp2qP52,
		Tb0wSzZ9C: Tb0wSzZ9C2,
		ltby7Y5nE: ltby7Y5nE2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "PwTxsQv03",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const visible = isSet(ltby7Y5nE2);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-127hl5u",
							className3,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"PwTxsQv03"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						{Dbl5KbMB62 !== false && (
							<ComponentViewportProvider
								suppressHydrationWarning={true}
								height={28}
								y={(componentViewport?.y || 0) + 0 + 0}
							>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-sp6pr2-container"}
									layoutDependency={layoutDependency}
									layoutId={"AgWuEUo3e-container"}
									nodeId={"AgWuEUo3e"}
									rendersWithMotion={true}
									scopeId={"FHiW2mJr3"}
								>
									{_jsx(stdin_default, {
										suppressHydrationWarning: true,
										height: "100%",
										id: "AgWuEUo3e",
										layoutId: "AgWuEUo3e",
										Q9pPRx4wJ: Ae7hp2qP52,
										variant: matchVariant("ItvvHWsJf"),
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-rnvu9s"}
							data-framer-name={"Titles"}
							layoutDependency={layoutDependency}
							layoutId={"XHd8aptXM"}
						>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-16vin5w"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"wXJYykj6I"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={Tb0wSzZ9C2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h1
										suppressHydrationWarning={true}
										className={"framer-styles-preset-gwzd60"}
										data-styles-preset={"nzncKCFi1"}
									>
										{"The Team"}
									</motion.h1>
								</React.Fragment>
							</RichText>
							{visible !== false && (
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-1hlzohy"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"lEETSXf5c"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.6))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={ltby7Y5nE2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-26kq2w"}
											data-styles-preset={"zuIVYXLhn"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.6)))",
											}}
										>
											{
												"We're a creative agency focused on clarity and meaning. We build timeless foundations."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-YzGE6.framer-11b2tsk, .framer-YzGE6 .framer-11b2tsk { display: block; }",
	".framer-YzGE6.framer-127hl5u { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 700px; }",
	".framer-YzGE6 .framer-sp6pr2-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-YzGE6 .framer-rnvu9s { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-YzGE6 .framer-16vin5w { --framer-text-wrap-override: none; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-YzGE6 .framer-1hlzohy { --framer-text-wrap-override: none; flex: none; height: auto; max-width: 90%; position: relative; width: 100%; }",
	...css2,
	...css,
];
var FramerFHiW2mJr3 = withCSS(Component, css3, "framer-YzGE6");
var stdin_default2 = FramerFHiW2mJr3;
FramerFHiW2mJr3.displayName = "Journal Header";
FramerFHiW2mJr3.defaultProps = {
	height: 168,
	width: 700,
};
addPropertyControls(FramerFHiW2mJr3, {
	Dbl5KbMB6: {
		defaultValue: true,
		title: "Has Badge",
		type: ControlType.Boolean,
	},
	Ae7hp2qP5: {
		defaultValue: "Who we are",
		displayTextArea: false,
		title: "Badge",
		type: ControlType.String,
	},
	Tb0wSzZ9C: {
		defaultValue: "The Team",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	ltby7Y5nE: {
		defaultValue:
			"We're a creative agency focused on clarity and meaning. We build timeless foundations.",
		displayTextArea: true,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerFHiW2mJr3,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...BadgeFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:journal-header
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders JournalHeaderFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var journal_header_default = ComponentWithRoot;
export { journal_header_default as default };
