// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e4fc90c95afaebc0 "Das Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Shorter' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * minRead?: string // Min read
 * title?: string // Title
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-WNPLVTAM.js";
import "./chunks/chunk-ENY5TG7Y.js";
import "./chunks/chunk-OYMYRKFS.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-XTMKCPSV.js";
import { stdin_default } from "./chunks/chunk-I6BBA4QK.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-7CFDZMPZ.js";
import { className, css, fonts } from "./chunks/chunk-XWVFXG3B.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-B5JEBSFU.js";
import { routes } from "./chunks/chunk-BAX4IDEL.js";

// virtual:journal-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/31mn4EgLDIkEbE9zUtsd/hzCDVhhU5MixpLLylBUo/cSIxbKqxg.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var VisualFonts = getFonts(stdin_default2);
var ArrowUpRightFonts = getFonts(stdin_default);
var DividerFonts = getFonts(stdin_default3);
var enabledGestures = {
	rV9wIeiLZ: {
		hover: true,
	},
	vUEbBqWFj: {
		hover: true,
	},
};
var cycleOrder = ["rV9wIeiLZ", "vUEbBqWFj"];
var serializationHash = "framer-RF75i";
var variantClassNames = {
	rV9wIeiLZ: "framer-v-n7ychx",
	vUEbBqWFj: "framer-v-1vvxkk",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.8,
	ease: [0.35, 0, 0, 1],
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Default: "rV9wIeiLZ",
	Shorter: "vUEbBqWFj",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, image, minRead, title, width, ...props }) => {
	return {
		...props,
		K_I4Bp8Q0: minRead ?? props.K_I4Bp8Q0 ?? "5 min read",
		pLX_TeASp: title ?? props.pLX_TeASp ?? "Crafting a Timeless Brand Identity",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "rV9wIeiLZ",
		x3hiz0aCu: image ?? props.x3hiz0aCu,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		x3hiz0aCu: x3hiz0aCu2,
		K_I4Bp8Q0: K_I4Bp8Q02,
		pLX_TeASp: pLX_TeASp2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "rV9wIeiLZ",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className3, className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (gestureVariant === "vUEbBqWFj-hover") return false;
		if (baseVariant === "vUEbBqWFj") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (gestureVariant === "vUEbBqWFj-hover") return true;
		if (baseVariant === "vUEbBqWFj") return true;
		return false;
	};
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-n7ychx",
							className4,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"rV9wIeiLZ"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								"rV9wIeiLZ-hover": {
									"data-framer-name": void 0,
								},
								"vUEbBqWFj-hover": {
									"data-framer-name": void 0,
								},
								vUEbBqWFj: {
									"data-framer-name": "Shorter",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-5sm6kk"}
							data-framer-name={"Visual"}
							layoutDependency={layoutDependency}
							layoutId={"XzCGV6z4F"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-l7y408"}
								data-framer-name={"Visual Container"}
								layoutDependency={layoutDependency}
								layoutId={"Lmq9umnXg"}
								style={{
									borderBottomLeftRadius: 10,
									borderBottomRightRadius: 10,
									borderTopLeftRadius: 10,
									borderTopRightRadius: 10,
								}}
							>
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={289}
									width={`max(${componentViewport?.width || "100vw"}, 1px)`}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 459) - 0 - 568.4) / 2 +
											0 +
											0) +
										0 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											vUEbBqWFj: {
												height: 318,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 416) - 0 - 561.4) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-zyztee-container"}
										layoutDependency={layoutDependency}
										layoutId={"okTQjR444-container"}
										nodeId={"okTQjR444"}
										rendersWithMotion={true}
										scopeId={"cSIxbKqxg"}
										style={{
											scale: 1,
										}}
										variants={{
											"rV9wIeiLZ-hover": {
												scale: 1.2,
											},
											"vUEbBqWFj-hover": {
												scale: 1.2,
											},
										}}
									>
										{_jsx(stdin_default2, {
											suppressHydrationWarning: true,
											Evc3NlKBm: "",
											height: "100%",
											id: "okTQjR444",
											layoutId: "okTQjR444",
											qr_eL5_qQ: toResponsiveImage(x3hiz0aCu2),
											style: {
												height: "100%",
												width: "100%",
											},
											tRQiAbNTk: false,
											variant: matchVariant("txJ9749K_"),
											width: "100%",
											...addPropertyOverrides(
												{
													"rV9wIeiLZ-hover": {
														variant: matchVariant("qMTjbBZ5g"),
													},
													"vUEbBqWFj-hover": {
														variant: matchVariant("qMTjbBZ5g"),
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-lkcz20"}
									data-framer-name={"Hover View"}
									layoutDependency={layoutDependency}
									layoutId={"zlqXHXjb0"}
									style={{
										backdropFilter: "blur(5px)",
										borderBottomLeftRadius: 12,
										borderBottomRightRadius: 12,
										borderTopLeftRadius: 12,
										borderTopRightRadius: 12,
										opacity: 0,
										WebkitBackdropFilter: "blur(5px)",
									}}
									variants={{
										"rV9wIeiLZ-hover": {
											opacity: 1,
										},
										"vUEbBqWFj-hover": {
											opacity: 1,
										},
									}}
								>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-et6s4v"}
										data-framer-name={"Icon Container"}
										layoutDependency={layoutDependency}
										layoutId={"rbhTe0bHe"}
										style={{
											backgroundColor:
												"var(--token-1ad0dd99-5aec-4e1d-804a-3c603649eb34, rgb(255, 255, 255))",
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
										}}
									>
										{_jsx(stdin_default, {
											suppressHydrationWarning: true,
											animated: true,
											className: "framer-w5hu2g",
											layoutDependency,
											layoutId: "CG2m7CppB",
											style: {
												"--1m973uw": "rgb(0, 0, 0)",
												"--js9iwy": 2.5,
											},
										})}
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.div>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-11t10lx"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"Jct0uSz0l"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-v16074"}
								data-framer-name={"Titles"}
								layoutDependency={layoutDependency}
								layoutId={"LOu9roJDo"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-144y6nv"}
									data-framer-name={"Wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"OnZ3zLFCZ"}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-wril8z"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"C391BVdVH"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgb(82, 81, 81))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={K_I4Bp8Q02}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-26kq2w"}
												data-styles-preset={"zuIVYXLhn"}
												dir={"auto"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgb(82, 81, 81)))",
												}}
											>
												{"5 min read"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-g9ki3u"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"qHDsy8xWm"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={pLX_TeASp2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-bgskcq"}
												data-styles-preset={"jjVH7JKxN"}
												dir={"auto"}
											>
												{"Crafting a Timeless Brand Identity"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							{isDisplayed() && (
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={1}
									width={componentViewport?.width || "100vw"}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 459) - 0 - 568.4) / 2 +
											289 +
											0) +
										12 +
										230.4
									}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-102zs3o-container"}
										layoutDependency={layoutDependency}
										layoutId={"dBtKNOvAP-container"}
										nodeId={"dBtKNOvAP"}
										rendersWithMotion={true}
										scopeId={"cSIxbKqxg"}
									>
										{_jsx(stdin_default3, {
											suppressHydrationWarning: true,
											height: "100%",
											id: "dBtKNOvAP",
											layoutId: "dBtKNOvAP",
											style: {
												height: "100%",
												width: "100%",
											},
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-7xd3tu"}
								data-framer-name={"Button"}
								layoutDependency={layoutDependency}
								layoutId={"fzX7x_1PX"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-2yrmvb"}
									data-framer-name={"Text Container"}
									layoutDependency={layoutDependency}
									layoutId={"GZfSJ30mO"}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1aoczys"}
										data-framer-name={"Text Default"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"UpoMNhF5C"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-t7dvh9"}
												data-styles-preset={"vkgsOTgUD"}
												dir={"auto"}
											>
												{"Read article"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-11gn2at"}
										data-framer-name={"Text Hover"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"SjoZQE648"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-t7dvh9"}
												data-styles-preset={"vkgsOTgUD"}
												dir={"auto"}
											>
												{"Read article"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1uusdk3"}
									data-framer-name={"Icon Container"}
									layoutDependency={layoutDependency}
									layoutId={"oU_hWeNvb"}
								>
									{_jsx(stdin_default, {
										suppressHydrationWarning: true,
										animated: true,
										className: "framer-zoa3hp",
										layoutDependency,
										layoutId: "wIu8x9pfo",
										style: {
											"--1m973uw":
												"var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(10, 10, 10))",
											"--js9iwy": 2,
										},
									})}
									{_jsx(stdin_default, {
										suppressHydrationWarning: true,
										animated: true,
										className: "framer-4d0xj4",
										layoutDependency,
										layoutId: "BxDktAh9q",
										style: {
											"--1m973uw":
												"var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(10, 10, 10))",
											"--js9iwy": 2,
										},
									})}
								</motion.div>
							</motion.div>
						</motion.div>
						{isDisplayed1() && (
							<ComponentViewportProvider
								suppressHydrationWarning={true}
								{...addPropertyOverrides(
									{
										vUEbBqWFj: {
											height: 1,
											width: componentViewport?.width || "100vw",
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 416) - 0 - 561.4) / 2 +
													560.4 +
													0),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-1cvi7fd-container"}
									layoutDependency={layoutDependency}
									layoutId={"REiXC_XDu-container"}
									nodeId={"REiXC_XDu"}
									rendersWithMotion={true}
									scopeId={"cSIxbKqxg"}
								>
									{_jsx(stdin_default3, {
										suppressHydrationWarning: true,
										height: "100%",
										id: "REiXC_XDu",
										layoutId: "REiXC_XDu",
										style: {
											height: "100%",
											width: "100%",
										},
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-RF75i.framer-1h23f4e, .framer-RF75i .framer-1h23f4e { display: block; }",
	".framer-RF75i.framer-n7ychx { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 397px; }",
	".framer-RF75i .framer-5sm6kk { align-content: center; align-items: center; aspect-ratio: 1.3737024221453287 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 289px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-RF75i .framer-l7y408 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); z-index: 0; }",
	".framer-RF75i .framer-zyztee-container { flex: 1 0 0px; height: 100%; position: relative; width: 1px; }",
	".framer-RF75i .framer-lkcz20 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; left: 0px; overflow: hidden; padding: 0px; pointer-events: none; position: absolute; top: 0px; width: 100%; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-RF75i .framer-et6s4v { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: var(--framer-aspect-ratio-supported, 100px); justify-content: center; overflow: visible; padding: 30px; position: relative; width: 100px; }",
	".framer-RF75i .framer-w5hu2g { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
	".framer-RF75i .framer-11t10lx { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 12px 0px 0px 0px; position: relative; width: 100%; z-index: 3; }",
	".framer-RF75i .framer-v16074 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-RF75i .framer-144y6nv { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-RF75i .framer-wril8z { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: auto; }",
	".framer-RF75i .framer-g9ki3u { --framer-text-wrap-override: balance; flex: none; height: auto; max-width: 320px; position: relative; width: 100%; }",
	".framer-RF75i .framer-102zs3o-container, .framer-RF75i .framer-1cvi7fd-container { flex: none; height: 1px; position: relative; width: 100%; }",
	".framer-RF75i .framer-7xd3tu { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-RF75i .framer-2yrmvb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 3px 0px 3px 0px; position: relative; width: min-content; }",
	".framer-RF75i .framer-1aoczys { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-RF75i .framer-11gn2at { bottom: -20px; flex: none; height: auto; left: 0px; position: absolute; white-space: pre; width: auto; z-index: 1; }",
	".framer-RF75i .framer-1uusdk3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; }",
	".framer-RF75i .framer-zoa3hp { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 20px); position: relative; width: 20px; }",
	".framer-RF75i .framer-4d0xj4 { aspect-ratio: 1 / 1; bottom: -20px; flex: none; height: var(--framer-aspect-ratio-supported, 20px); left: -20px; position: absolute; width: 20px; z-index: 1; }",
	".framer-RF75i.framer-v-1vvxkk.framer-n7ychx { width: 689px; }",
	".framer-RF75i.framer-v-1vvxkk .framer-5sm6kk { aspect-ratio: 2.1666666666666665 / 1; height: var(--framer-aspect-ratio-supported, 318px); }",
	".framer-RF75i.framer-v-1vvxkk .framer-11t10lx { align-content: flex-end; align-items: flex-end; flex-direction: row; padding: 12px 0px 16px 0px; }",
	".framer-RF75i.framer-v-1vvxkk .framer-v16074 { flex: 1 0 0px; order: 0; width: 1px; }",
	".framer-RF75i.framer-v-1vvxkk .framer-g9ki3u { max-width: 600px; }",
	".framer-RF75i.framer-v-1vvxkk .framer-7xd3tu { order: 1; }",
	".framer-RF75i.framer-v-n7ychx.hover .framer-1aoczys, .framer-RF75i.framer-v-1vvxkk.hover .framer-1aoczys { left: 0px; position: absolute; top: -20px; z-index: 1; }",
	".framer-RF75i.framer-v-n7ychx.hover .framer-11gn2at, .framer-RF75i.framer-v-n7ychx.hover .framer-4d0xj4, .framer-RF75i.framer-v-1vvxkk.hover .framer-11gn2at { bottom: unset; left: unset; position: relative; }",
	".framer-RF75i.framer-v-n7ychx.hover .framer-zoa3hp { position: absolute; right: -20px; top: -20px; z-index: 1; }",
	...css3,
	...css,
	...css2,
];
var FramercSIxbKqxg = withCSS(Component, css4, "framer-RF75i");
var stdin_default4 = FramercSIxbKqxg;
FramercSIxbKqxg.displayName = "Journal Card";
FramercSIxbKqxg.defaultProps = {
	height: 459,
	width: 397,
};
addPropertyControls(FramercSIxbKqxg, {
	variant: {
		options: ["rV9wIeiLZ", "vUEbBqWFj"],
		optionTitles: ["Default", "Shorter"],
		title: "Variant",
		type: ControlType.Enum,
	},
	x3hiz0aCu: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	K_I4Bp8Q0: {
		defaultValue: "5 min read",
		displayTextArea: false,
		title: "Min read",
		type: ControlType.String,
	},
	pLX_TeASp: {
		defaultValue: "Crafting a Timeless Brand Identity",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(
	FramercSIxbKqxg,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...VisualFonts,
		...ArrowUpRightFonts,
		...DividerFonts,
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:journal-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "rV9wIeiLZ",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders JournalCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var journal_card_default = ComponentWithRoot;
export { journal_card_default as default };
