// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e4fc90c95afaebc0 "Das Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Fill' | 'Default Phone' | 'Fill Phone' // Variant
 * title?: string // Title
 * onXOBbmp2IFCHange?: any // onXOBbmp2IFCHange
 * badge?: string // Badge
 * onudoQH5ozICHange?: any // onudoQH5ozICHange
 * text?: string // Text
 * onkKrFMHjQChange?: any // onkKrFMHjQChange
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-7CFDZMPZ.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-B5JEBSFU.js";
import { routes } from "./chunks/chunk-BAX4IDEL.js";

// virtual:main-header
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/vdJWaBzrZ5nwJODaT0P2/GxrmCCwNh5HHZb4OzPsm/gUkWEqa_3.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/GdPylpFev9ZdI28olAfJ/75r7i1tOSMJ5qpbgghSx/rJ1aj4bkv.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"Inter-Medium",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-MediumItalic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/UjlFhCnUjxhNfep4oYBPqnEssyo.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/khkJkwSL66WFg8SX6Wa726c.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/0E7IMbDzcGABpBwwqNEt60wU0w.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/NTJ0nQgIF0gcDelS14zQ9NR9Q.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/QrcNhgEPfRl0LS8qz5Ln8olanl8.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JEXmejW8mXOYMtt0hyRg811kHac.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/Bo5CNzBv77CafbxOtKIkpw9egw.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/uy9s0iWuxiNnVt8EpTI3gzohpwo.woff2",
				weight: "500",
			},
		],
	},
];
var css3 = [
	'.framer-a93Ym .framer-styles-preset-qb2ial:not(.rich-text-wrapper), .framer-a93Ym .framer-styles-preset-qb2ial.rich-text-wrapper h1 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 90px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -7px; --framer-line-height: 0.8em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, #1d2029); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-a93Ym .framer-styles-preset-qb2ial:not(.rich-text-wrapper), .framer-a93Ym .framer-styles-preset-qb2ial.rich-text-wrapper h1 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 80px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -7px; --framer-line-height: 0.8em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, #1d2029); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-a93Ym .framer-styles-preset-qb2ial:not(.rich-text-wrapper), .framer-a93Ym .framer-styles-preset-qb2ial.rich-text-wrapper h1 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 60px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -7px; --framer-line-height: 0.8em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, #1d2029); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }',
];
var className3 = "framer-a93Ym";

// /:https://framerusercontent.com/modules/vdJWaBzrZ5nwJODaT0P2/GxrmCCwNh5HHZb4OzPsm/gUkWEqa_3.js
var cycleOrder = ["IbFVTWHct", "pWTVcnNL5", "EzSc94HC_", "Kbtj2Eyx0"];
var serializationHash = "framer-PETbl";
var variantClassNames = {
	EzSc94HC_: "framer-v-12oomg5",
	IbFVTWHct: "framer-v-1nhpeq5",
	Kbtj2Eyx0: "framer-v-1vclxdp",
	pWTVcnNL5: "framer-v-67dpja",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Default Phone": "EzSc94HC_",
	"Fill Phone": "Kbtj2Eyx0",
	Default: "IbFVTWHct",
	Fill: "pWTVcnNL5",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ badge, height, id, text, title, width, ...props }) => {
	return {
		...props,
		kKrFMhj_q:
			text ??
			props.kKrFMhj_q ??
			"We turn bold ideas into intuitive experiences. We are a creative design studio. ",
		udoQH5ozI: badge ?? props.udoQH5ozI ?? "(6)",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "IbFVTWHct",
		XObbmp2IF: title ?? props.XObbmp2IF ?? "Works",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		XObbmp2IF: XObbmp2IF2,
		udoQH5ozI: udoQH5ozI2,
		kKrFMhj_q: kKrFMhj_q2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "IbFVTWHct",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className3, className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const visible = isSet(udoQH5ozI2);
	const isDisplayed = (value) => {
		if (["pWTVcnNL5", "Kbtj2Eyx0"].includes(baseVariant)) return false;
		return value;
	};
	const visible1 = isSet(kKrFMhj_q2);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1nhpeq5",
							className4,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"IbFVTWHct"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								EzSc94HC_: {
									"data-framer-name": "Default Phone",
								},
								Kbtj2Eyx0: {
									"data-framer-name": "Fill Phone",
								},
								pWTVcnNL5: {
									"data-framer-name": "Fill",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-qnkvjo"}
							data-framer-name={"Inner Container"}
							layoutDependency={layoutDependency}
							layoutId={"xTIa1yZBE"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-c5x99a"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"vO3QgHDpS"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-1s8l1d5"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"Jxg6lX4Kt"}
									text={XObbmp2IF2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h1
											suppressHydrationWarning={true}
											className={"framer-styles-preset-qb2ial"}
											data-styles-preset={"rJ1aj4bkv"}
											dir={"auto"}
										>
											{"Works"}
										</motion.h1>
									</React.Fragment>
								</RichText>
								{isDisplayed(visible !== false) && (
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1n8avdr"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"GxolN3OJx"}
										text={udoQH5ozI2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-t7dvh9"}
												data-styles-preset={"vkgsOTgUD"}
												style={{
													"--framer-text-alignment": "right",
												}}
											>
												{"(6)"}
											</motion.p>
										</React.Fragment>
									</RichText>
								)}
							</motion.div>
							{visible1 !== false && (
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-10es345"}
									data-framer-name={"Text Block"}
									layoutDependency={layoutDependency}
									layoutId={"NUzsXPhkI"}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1wsgg7l"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"YMlNfge_9"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={kKrFMhj_q2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-26kq2w"}
												data-styles-preset={"zuIVYXLhn"}
												dir={"auto"}
												style={{
													"--framer-text-alignment": "left",
												}}
											>
												{
													"We turn bold ideas into intuitive experiences. We are a creative design studio. "
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-PETbl.framer-10uxmr4, .framer-PETbl .framer-10uxmr4 { display: block; }",
	".framer-PETbl.framer-1nhpeq5 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1120px; }",
	".framer-PETbl .framer-qnkvjo { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-PETbl .framer-c5x99a { align-content: flex-start; align-items: flex-start; display: flex; flex: 3 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-PETbl .framer-1s8l1d5, .framer-PETbl .framer-1n8avdr { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-PETbl .framer-10es345 { align-content: flex-start; align-items: flex-start; align-self: stretch; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 15px 32px; height: auto; justify-content: flex-end; max-width: 230px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; }",
	".framer-PETbl .framer-1wsgg7l { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-PETbl.framer-v-67dpja .framer-c5x99a { gap: 0px; }",
	".framer-PETbl.framer-v-67dpja .framer-1s8l1d5 { flex: 1 0 0px; max-width: 1000px; order: 0; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-PETbl.framer-v-12oomg5.framer-1nhpeq5, .framer-PETbl.framer-v-1vclxdp.framer-1nhpeq5 { width: 563px; }",
	".framer-PETbl.framer-v-12oomg5 .framer-qnkvjo, .framer-PETbl.framer-v-1vclxdp .framer-qnkvjo { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 35px 8px; }",
	".framer-PETbl.framer-v-12oomg5 .framer-c5x99a { flex: none; width: 100%; }",
	".framer-PETbl.framer-v-12oomg5 .framer-10es345 { align-self: unset; flex: none; height: min-content; max-width: 321px; width: 100%; }",
	".framer-PETbl.framer-v-12oomg5 .framer-1wsgg7l, .framer-PETbl.framer-v-1vclxdp .framer-1wsgg7l { --framer-text-wrap-override: balance; }",
	".framer-PETbl.framer-v-1vclxdp .framer-c5x99a { flex: none; gap: 0px; width: 100%; }",
	".framer-PETbl.framer-v-1vclxdp .framer-1s8l1d5 { flex: 1 0 0px; max-width: 100%; order: 0; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-PETbl.framer-v-1vclxdp .framer-10es345 { align-self: unset; flex: none; height: min-content; max-width: 320px; width: 100%; }",
	...css3,
	...css,
	...css2,
];
var FramergUkWEqa_3 = withCSS(Component, css4, "framer-PETbl");
var stdin_default = FramergUkWEqa_3;
FramergUkWEqa_3.displayName = "Main Header";
FramergUkWEqa_3.defaultProps = {
	height: 112,
	width: 1120,
};
addPropertyControls(FramergUkWEqa_3, {
	variant: {
		options: ["IbFVTWHct", "pWTVcnNL5", "EzSc94HC_", "Kbtj2Eyx0"],
		optionTitles: ["Default", "Fill", "Default Phone", "Fill Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	XObbmp2IF: {
		defaultValue: "Works",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	onXObbmp2IFChange: {
		changes: "XObbmp2IF",
		type: ControlType.ChangeHandler,
	},
	udoQH5ozI: {
		defaultValue: "(6)",
		displayTextArea: false,
		title: "Badge",
		type: ControlType.String,
	},
	onudoQH5ozIChange: {
		changes: "udoQH5ozI",
		type: ControlType.ChangeHandler,
	},
	kKrFMhj_q: {
		defaultValue:
			"We turn bold ideas into intuitive experiences. We are a creative design studio. ",
		displayTextArea: true,
		title: "Text",
		type: ControlType.String,
	},
	onkKrFMhj_qChange: {
		changes: "kKrFMhj_q",
		type: ControlType.ChangeHandler,
	},
});
addFonts(
	FramergUkWEqa_3,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:main-header
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "EzSc94HC_",
	xl: "IbFVTWHct",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MainHeaderFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var main_header_default = ComponentWithRoot;
export { main_header_default as default };
