// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e4fc90c95afaebc0 "Das Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * onuWFF4fRsVCHange?: any // onuWFF4fRsVCHange
 * text?: string // Text
 * onr6WTJJPh_Change?: any // onr6WTJJPh_Change
 * price?: number // Price
 * onBtN8rx9eyChange?: any // onBtN8rx9eyChange
 * priceSuffix?: string // Price Suffix
 * onrKBBIwmhOCHange?: any // onrKBBIwmhOCHange
 * listItem1?: string // List Item 1
 * onbbuykez0kChange?: any // onbbuykez0kChange
 * listItem2?: string // List Item 2
 * oneATCXEUAWChange?: any // oneATCXEUAWChange
 * listItem3?: string // List Item 3
 * onxURWGV9TiChange?: any // onxURWGV9TiChange
 * listItem4?: string // List Item 4
 * onGQFFAIpetChange?: any // onGQFFAIpetChange
 * isPopularChoice?: boolean // Is Popular Choice
 * onvhP3GqdvVCHange?: any // onvhP3GqdvVCHange
 * buttonTitle?: string // Button Title
 * onTE7ukYkwlChange?: any // onTE7ukYkwlChange
 * buttonLink?: string // Button Link
 * hasLimitedAvailability?: boolean // Has Limited Availability
 * onSrvr4fPohChange?: any // onSrvr4fPohChange
}} Props

 */
import { PulseEffect } from "./chunks/chunk-SVLQG5EG.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-CQUJRBEV.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-UE3C3KIZ.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-IYUBPT6N.js";
import "./chunks/chunk-I6BBA4QK.js";
import { stdin_default } from "./chunks/chunk-GHRXF5NR.js";
import "./chunks/chunk-EANZ46VA.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-46Q3S57O.js";
import "./chunks/chunk-7CFDZMPZ.js";
import { className, css, fonts } from "./chunks/chunk-B5JEBSFU.js";
import { routes } from "./chunks/chunk-BAX4IDEL.js";

// virtual:pricing-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/cNpibvFbm5AtaDbRkaU4/XA6rtLCbtmBLS0oSfwse/z2ohEzTkn.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleCode,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/60ruPaq91QOU6ZSQnQjt/mAyygrMTPdW8DMCisLzg/sfgiQXU3_.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg suppressHydrationWarning={true} {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG
			suppressHydrationWarning={true}
			{...rest}
			layoutId={layoutId}
			ref={ref}
		>
			{children}
		</MotionSVG>
	) : (
		<svg suppressHydrationWarning={true} {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 10 C 0 4.477 4.477 0 10 0 C 15.523 0 20 4.477 20 10 C 20 15.523 15.523 20 10 20 C 4.477 20 0 15.523 0 10 Z" fill="transparent" height="20px" id="DCz_eKU1_" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(2 2)" width="20px"/><path d="M 0 2 L 2 4 L 6 0" fill="transparent" height="4px" id="UefoekZNv" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(9 10)" width="6px"/></svg>';
var getProps = ({ color, height, id, width, width1, ...props }) => {
	return {
		...props,
		JEeZYcamG: width1 ?? props.JEeZYcamG ?? 2,
		P_DcoRcrY: color ?? props.P_DcoRcrY ?? "rgb(0, 0, 0)",
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className5,
		layoutId,
		variant,
		P_DcoRcrY,
		JEeZYcamG,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("2994208654", svg);
	return (
		<SVG
			suppressHydrationWarning={true}
			{...restProps}
			className={cx("framer-E6ihB", className5)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m973uw": P_DcoRcrY,
				"--js9iwy": JEeZYcamG,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use suppressHydrationWarning={true} href={href} />
		</SVG>
	);
});
var css5 = [
	`.framer-E6ihB { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css5, "framer-E6ihB");
Icon.displayName = "Circle Check";
var stdin_default3 = Icon;
addPropertyControls(Icon, {
	P_DcoRcrY: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	JEeZYcamG: {
		defaultValue: 2,
		displayStepper: true,
		hidden: false,
		max: 16,
		min: 1,
		title: "Width",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/cNpibvFbm5AtaDbRkaU4/XA6rtLCbtmBLS0oSfwse/z2ohEzTkn.js
var BadgeFonts = getFonts(stdin_default);
var PulseFonts = getFonts(PulseEffect);
var CircleCheckFonts = getFonts(stdin_default3);
var ButtonFonts = getFonts(stdin_default2);
var serializationHash = "framer-6YTOT";
var variantClassNames = {
	F0B9Ktlv2: "framer-v-1b2n7p5",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var numberToString = (value, options = {}, activeLocale) => {
	const fallbackLocale = "en-US";
	const locale = options.locale || activeLocale || fallbackLocale;
	const {
		useGrouping,
		notation,
		compactDisplay,
		style,
		currency,
		currencyDisplay,
		unit,
		unitDisplay,
		minimumFractionDigits,
		maximumFractionDigits,
		minimumIntegerDigits,
	} = options;
	const formatOptions = {
		useGrouping,
		notation,
		compactDisplay,
		style,
		currency,
		currencyDisplay,
		unit,
		unitDisplay,
		minimumFractionDigits,
		maximumFractionDigits,
		minimumIntegerDigits,
	};
	const number = Number(value);
	try {
		return number.toLocaleString(locale, formatOptions);
	} catch {
		try {
			return number.toLocaleString(fallbackLocale, formatOptions);
		} catch {
			return number.toLocaleString();
		}
	}
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var getProps2 = ({
	buttonLink,
	buttonTitle,
	hasLimitedAvailability,
	height,
	id,
	isPopularChoice,
	listItem1,
	listItem2,
	listItem3,
	listItem4,
	price,
	priceSuffix,
	text,
	title,
	width,
	...props
}) => {
	return {
		...props,
		bbuykez0k: listItem1 ?? props.bbuykez0k ?? "Web design & development",
		BtN8rx9ey: price ?? props.BtN8rx9ey,
		eATCxEUAw: listItem2 ?? props.eATCxEUAw ?? "2 active projects at a time",
		GQFFAipet:
			listItem4 ?? props.GQFFAipet ?? "Brand identity design & refinement",
		r6WTJJph_:
			text ??
			props.r6WTJJph_ ??
			"Ideal for brands that need regular creative, design, or dev work.",
		rKBbIwmhO: priceSuffix ?? props.rKBbIwmhO ?? "/month",
		Srvr4fPoh: hasLimitedAvailability ?? props.Srvr4fPoh ?? true,
		TE7ukYkwl: buttonTitle ?? props.TE7ukYkwl ?? "Start Montly Plan",
		uWFf4fRsV: title ?? props.uWFf4fRsV ?? "Executive",
		vhP3GqdvV: isPopularChoice ?? props.vhP3GqdvV,
		w6gtQGcXr: buttonLink ?? props.w6gtQGcXr,
		xURWGv9Ti:
			listItem3 ?? props.xURWGv9Ti ?? "Brand identity design & refinement",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		uWFf4fRsV: uWFf4fRsV2,
		r6WTJJph_: r6WTJJph_2,
		BtN8rx9ey: BtN8rx9ey2,
		rKBbIwmhO: rKBbIwmhO2,
		bbuykez0k: bbuykez0k2,
		eATCxEUAw: eATCxEUAw2,
		xURWGv9Ti: xURWGv9Ti2,
		GQFFAipet: GQFFAipet2,
		vhP3GqdvV: vhP3GqdvV2,
		TE7ukYkwl: TE7ukYkwl2,
		w6gtQGcXr: w6gtQGcXr2,
		Srvr4fPoh: Srvr4fPoh2,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "F0B9Ktlv2",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className4, className3, className, className2];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	const activeLocaleCode = useLocaleCode();
	const textContent = numberToString(
		BtN8rx9ey2,
		{
			compactDisplay: "short",
			currency: "USD",
			currencyDisplay: "symbol",
			locale: "",
			notation: "compact",
			style: "currency",
		},
		activeLocaleCode,
	);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion2.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1b2n7p5",
							className5,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"F0B9Ktlv2"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-e2a325f5-5d1b-4d4f-b9bb-f0704bd5c816, rgb(245, 245, 245))",
							borderBottomLeftRadius: 10,
							borderBottomRightRadius: 10,
							borderTopLeftRadius: 10,
							borderTopRightRadius: 10,
							...style,
						}}
					>
						<motion2.div
							suppressHydrationWarning={true}
							className={"framer-1aigwww"}
							data-framer-name={"Inner Container"}
							layoutDependency={layoutDependency}
							layoutId={"dXtZMmwWD"}
							style={{
								borderBottomLeftRadius: 10,
								borderBottomRightRadius: 10,
								borderTopLeftRadius: 10,
								borderTopRightRadius: 10,
							}}
						>
							{vhP3GqdvV2 !== false && (
								<motion2.div
									suppressHydrationWarning={true}
									className={"framer-1p1hc0r"}
									data-framer-name={"Badge Container"}
									layoutDependency={layoutDependency}
									layoutId={"tM1FtYkdg"}
									style={{
										backgroundColor:
											"var(--token-e2a325f5-5d1b-4d4f-b9bb-f0704bd5c816, rgb(245, 245, 245))",
										borderBottomLeftRadius: 10,
										borderBottomRightRadius: 10,
										borderTopLeftRadius: 10,
										borderTopRightRadius: 10,
									}}
								>
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={28}
										y={(componentViewport?.y || 0) + 0 + 0 + 20 + 8}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-rsfk47-container"}
											layoutDependency={layoutDependency}
											layoutId={"oMJiLHD7k-container"}
											nodeId={"oMJiLHD7k"}
											rendersWithMotion={true}
											scopeId={"z2ohEzTkn"}
										>
											{_jsx2(stdin_default, {
												suppressHydrationWarning: true,
												height: "100%",
												id: "oMJiLHD7k",
												layoutId: "oMJiLHD7k",
												Q9pPRx4wJ: "",
												Wg_ILYJAw: "Popular",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion2.div>
							)}
							<motion2.div
								suppressHydrationWarning={true}
								className={"framer-1t1g1fe"}
								data-framer-name={"Header"}
								layoutDependency={layoutDependency}
								layoutId={"hTxWXogLr"}
							>
								<motion2.div
									suppressHydrationWarning={true}
									className={"framer-1il8p2o"}
									data-framer-name={"Title"}
									layoutDependency={layoutDependency}
									layoutId={"qwIoE0pyc"}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1v6wskg"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"uvvNi0l_Y"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={uWFf4fRsV2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.h4
												suppressHydrationWarning={true}
												className={"framer-styles-preset-1key48k"}
												data-styles-preset={"dMiBmbIPR"}
												dir={"auto"}
											>
												{"Executive"}
											</motion2.h4>
										</React2.Fragment>
									</RichText>
									{Srvr4fPoh2 !== false && (
										<motion2.div
											suppressHydrationWarning={true}
											className={"framer-170ncck"}
											data-framer-name={"Limited"}
											layoutDependency={layoutDependency}
											layoutId={"l9jIQYPvI"}
										>
											<ComponentViewportProvider
												suppressHydrationWarning={true}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-vbcoee-container"}
													isAuthoredByUser={true}
													layoutDependency={layoutDependency}
													layoutId={"SZbwYtRRc-container"}
													nodeId={"SZbwYtRRc"}
													rendersWithMotion={true}
													scopeId={"z2ohEzTkn"}
												>
													<PulseEffect
														suppressHydrationWarning={true}
														borderWidth={5}
														color={
															"var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(10, 10, 10))"
														}
														delay={1}
														direction={"out"}
														height={"100%"}
														id={"SZbwYtRRc"}
														layoutId={"SZbwYtRRc"}
														pulseOpacity={0.76}
														pulseSize={6}
														radiusType={"full"}
														radiusValue={20}
														style={"solid"}
														transition={{
															damping: 60,
															delay: 0,
															mass: 1,
															stiffness: 150,
															type: "spring",
														}}
														width={"100%"}
													/>
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-mu7jsc"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"FCPXIYMWe"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-33bebx"}
														data-styles-preset={"Wm4ZNpeAE"}
														dir={"auto"}
													>
														{"Limited availability"}
													</motion2.p>
												</React2.Fragment>
											</RichText>
										</motion2.div>
									)}
								</motion2.div>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-6ura5p"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"L6HdZpcIU"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={r6WTJJph_2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-26kq2w"}
											data-styles-preset={"zuIVYXLhn"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7)))",
											}}
										>
											{
												"Ideal for brands that need regular creative, design, or dev work."
											}
										</motion2.p>
									</React2.Fragment>
								</RichText>
							</motion2.div>
							<motion2.div
								suppressHydrationWarning={true}
								className={"framer-1moc1qf"}
								data-framer-name={"Details"}
								layoutDependency={layoutDependency}
								layoutId={"vCu8aaoXT"}
							>
								<motion2.div
									suppressHydrationWarning={true}
									className={"framer-1l5s5uo"}
									data-framer-name={"Details Container"}
									layoutDependency={layoutDependency}
									layoutId={"kNN7GO7IP"}
								>
									<motion2.div
										suppressHydrationWarning={true}
										className={"framer-13fgx28"}
										data-framer-name={"Price"}
										layoutDependency={layoutDependency}
										layoutId={"newGIexyT"}
									>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-sxblun"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"RTUplxZZC"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={textContent}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.h2
													suppressHydrationWarning={true}
													className={"framer-styles-preset-1ybindd"}
													data-styles-preset={"YOHgFrSaY"}
												>
													{"$NaN"}
												</motion2.h2>
											</React2.Fragment>
										</RichText>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-pwj3sh"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"yoQG8DcST"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={rKBbIwmhO2}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-26kq2w"}
													data-styles-preset={"zuIVYXLhn"}
												>
													{"/month"}
												</motion2.p>
											</React2.Fragment>
										</RichText>
									</motion2.div>
									<motion2.div
										suppressHydrationWarning={true}
										className={"framer-1a1cmvu"}
										data-framer-name={"List"}
										layoutDependency={layoutDependency}
										layoutId={"T7H5shXm2"}
									>
										<motion2.div
											suppressHydrationWarning={true}
											className={"framer-11maapv"}
											data-framer-name={"List Item 1"}
											layoutDependency={layoutDependency}
											layoutId={"wmnixtzRq"}
										>
											{_jsx2(stdin_default3, {
												suppressHydrationWarning: true,
												animated: true,
												className: "framer-1fhhic1",
												layoutDependency,
												layoutId: "ghIuRxhXA",
												style: {
													"--1m973uw":
														"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7))",
													"--js9iwy": 2,
												},
											})}
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-1ctecvi"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"NSgODCcEB"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7))",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												text={bbuykez0k2}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-26kq2w"}
														data-styles-preset={"zuIVYXLhn"}
														dir={"auto"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7)))",
														}}
													>
														{"Web design & development"}
													</motion2.p>
												</React2.Fragment>
											</RichText>
										</motion2.div>
										<motion2.div
											suppressHydrationWarning={true}
											className={"framer-t0y4ql"}
											data-framer-name={"List Item 2"}
											layoutDependency={layoutDependency}
											layoutId={"G9ymvecV0"}
										>
											{_jsx2(stdin_default3, {
												suppressHydrationWarning: true,
												animated: true,
												className: "framer-1n9f3",
												layoutDependency,
												layoutId: "KU8si64rm",
												style: {
													"--1m973uw":
														"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7))",
													"--js9iwy": 2,
												},
											})}
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-2t07i"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"f2l9x6WoJ"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7))",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												text={eATCxEUAw2}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-26kq2w"}
														data-styles-preset={"zuIVYXLhn"}
														dir={"auto"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7)))",
														}}
													>
														{"2 active projects at a time"}
													</motion2.p>
												</React2.Fragment>
											</RichText>
										</motion2.div>
										<motion2.div
											suppressHydrationWarning={true}
											className={"framer-sc8lq0"}
											data-framer-name={"List Item 3"}
											layoutDependency={layoutDependency}
											layoutId={"KqVU9_Jb_"}
										>
											{_jsx2(stdin_default3, {
												suppressHydrationWarning: true,
												animated: true,
												className: "framer-u4kro1",
												layoutDependency,
												layoutId: "CzTdCld7S",
												style: {
													"--1m973uw":
														"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7))",
													"--js9iwy": 2,
												},
											})}
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-eb5kod"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"zRChp0g8x"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7))",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												text={xURWGv9Ti2}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-26kq2w"}
														data-styles-preset={"zuIVYXLhn"}
														dir={"auto"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7)))",
														}}
													>
														{"Brand identity design & refinement"}
													</motion2.p>
												</React2.Fragment>
											</RichText>
										</motion2.div>
										<motion2.div
											suppressHydrationWarning={true}
											className={"framer-dk97pz"}
											data-framer-name={"List Item 4"}
											layoutDependency={layoutDependency}
											layoutId={"JwIWRr46V"}
										>
											{_jsx2(stdin_default3, {
												suppressHydrationWarning: true,
												animated: true,
												className: "framer-4kqbwp",
												layoutDependency,
												layoutId: "OabAVf2rv",
												style: {
													"--1m973uw":
														"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7))",
													"--js9iwy": 2,
												},
											})}
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-vnnlud"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"Su52zbZp0"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7))",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												text={GQFFAipet2}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-26kq2w"}
														data-styles-preset={"zuIVYXLhn"}
														dir={"auto"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7)))",
														}}
													>
														{"Brand identity design & refinement"}
													</motion2.p>
												</React2.Fragment>
											</RichText>
										</motion2.div>
									</motion2.div>
								</motion2.div>
							</motion2.div>
							<ComponentViewportProvider
								suppressHydrationWarning={true}
								height={44}
								width={`calc(${componentViewport?.width || "100vw"} - 80px)`}
								y={(componentViewport?.y || 0) + 0 + 0 + 50 + 832.2}
							>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-1og49pz-container"}
									layoutDependency={layoutDependency}
									layoutId={"fKXBESI1s-container"}
									nodeId={"fKXBESI1s"}
									rendersWithMotion={true}
									scopeId={"z2ohEzTkn"}
								>
									{_jsx2(stdin_default2, {
										suppressHydrationWarning: true,
										Ge1cwLZdF: true,
										height: "100%",
										id: "fKXBESI1s",
										IQJfIgKUA: w6gtQGcXr2,
										kUCdcilHJ: TE7ukYkwl2,
										layoutId: "fKXBESI1s",
										style: {
											width: "100%",
										},
										variant: matchVariant("qIg3fad0d"),
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion2.div>
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-6YTOT.framer-27bdm2, .framer-6YTOT .framer-27bdm2 { display: block; }",
	".framer-6YTOT.framer-1b2n7p5 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 469px; }",
	".framer-6YTOT .framer-1aigwww { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 56px; height: min-content; justify-content: center; overflow: hidden; padding: 50px 40px 30px 40px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-6YTOT .framer-1p1hc0r { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 8px 12px 8px 12px; position: absolute; right: 20px; top: 20px; width: min-content; }",
	".framer-6YTOT .framer-rsfk47-container { flex: none; height: auto; position: relative; width: auto; z-index: 1; }",
	".framer-6YTOT .framer-1t1g1fe { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-6YTOT .framer-1il8p2o { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-6YTOT .framer-1v6wskg, .framer-6YTOT .framer-sxblun, .framer-6YTOT .framer-pwj3sh { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-6YTOT .framer-170ncck { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: 16px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 141px; }",
	".framer-6YTOT .framer-vbcoee-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 10px); position: relative; width: 10px; }",
	".framer-6YTOT .framer-mu7jsc, .framer-6YTOT .framer-1ctecvi, .framer-6YTOT .framer-2t07i, .framer-6YTOT .framer-eb5kod, .framer-6YTOT .framer-vnnlud { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-6YTOT .framer-6ura5p { flex: none; height: auto; max-width: 360px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-6YTOT .framer-1moc1qf { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-6YTOT .framer-1l5s5uo { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-6YTOT .framer-13fgx28 { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-6YTOT .framer-1a1cmvu { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-6YTOT .framer-11maapv, .framer-6YTOT .framer-t0y4ql, .framer-6YTOT .framer-sc8lq0, .framer-6YTOT .framer-dk97pz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-6YTOT .framer-1fhhic1, .framer-6YTOT .framer-1n9f3, .framer-6YTOT .framer-u4kro1, .framer-6YTOT .framer-4kqbwp { flex: none; height: var(--framer-aspect-ratio-supported, 17px); position: relative; width: 18px; }",
	".framer-6YTOT .framer-1og49pz-container { flex: none; height: auto; position: relative; width: 100%; }",
	...css4,
	...css3,
	...css,
	...css2,
];
var Framerz2ohEzTkn = withCSS2(Component2, css6, "framer-6YTOT");
var stdin_default4 = Framerz2ohEzTkn;
Framerz2ohEzTkn.displayName = "Pricing Card";
Framerz2ohEzTkn.defaultProps = {
	height: 530.5,
	width: 469,
};
addPropertyControls2(Framerz2ohEzTkn, {
	uWFf4fRsV: {
		defaultValue: "Executive",
		displayTextArea: false,
		title: "Title",
		type: ControlType2.String,
	},
	onuWFf4fRsVChange: {
		changes: "uWFf4fRsV",
		type: ControlType2.ChangeHandler,
	},
	r6WTJJph_: {
		defaultValue:
			"Ideal for brands that need regular creative, design, or dev work.",
		displayTextArea: true,
		title: "Text",
		type: ControlType2.String,
	},
	onr6WTJJph_Change: {
		changes: "r6WTJJph_",
		type: ControlType2.ChangeHandler,
	},
	BtN8rx9ey: {
		defaultValue: 0,
		title: "Price",
		type: ControlType2.Number,
	},
	onBtN8rx9eyChange: {
		changes: "BtN8rx9ey",
		type: ControlType2.ChangeHandler,
	},
	rKBbIwmhO: {
		defaultValue: "/month",
		displayTextArea: false,
		title: "Price Suffix",
		type: ControlType2.String,
	},
	onrKBbIwmhOChange: {
		changes: "rKBbIwmhO",
		type: ControlType2.ChangeHandler,
	},
	bbuykez0k: {
		defaultValue: "Web design & development",
		displayTextArea: false,
		title: "List Item 1",
		type: ControlType2.String,
	},
	onbbuykez0kChange: {
		changes: "bbuykez0k",
		type: ControlType2.ChangeHandler,
	},
	eATCxEUAw: {
		defaultValue: "2 active projects at a time",
		displayTextArea: false,
		title: "List Item 2",
		type: ControlType2.String,
	},
	oneATCxEUAwChange: {
		changes: "eATCxEUAw",
		type: ControlType2.ChangeHandler,
	},
	xURWGv9Ti: {
		defaultValue: "Brand identity design & refinement",
		displayTextArea: false,
		title: "List Item 3",
		type: ControlType2.String,
	},
	onxURWGv9TiChange: {
		changes: "xURWGv9Ti",
		type: ControlType2.ChangeHandler,
	},
	GQFFAipet: {
		defaultValue: "Brand identity design & refinement",
		displayTextArea: false,
		title: "List Item 4",
		type: ControlType2.String,
	},
	onGQFFAipetChange: {
		changes: "GQFFAipet",
		type: ControlType2.ChangeHandler,
	},
	vhP3GqdvV: {
		defaultValue: false,
		title: "Is Popular Choice",
		type: ControlType2.Boolean,
	},
	onvhP3GqdvVChange: {
		changes: "vhP3GqdvV",
		type: ControlType2.ChangeHandler,
	},
	TE7ukYkwl: {
		defaultValue: "Start Montly Plan",
		displayTextArea: false,
		title: "Button Title",
		type: ControlType2.String,
	},
	onTE7ukYkwlChange: {
		changes: "TE7ukYkwl",
		type: ControlType2.ChangeHandler,
	},
	w6gtQGcXr: {
		title: "Button Link",
		type: ControlType2.Link,
	},
	Srvr4fPoh: {
		defaultValue: true,
		title: "Has Limited Availability",
		type: ControlType2.Boolean,
	},
	onSrvr4fPohChange: {
		changes: "Srvr4fPoh",
		type: ControlType2.ChangeHandler,
	},
});
addFonts(
	Framerz2ohEzTkn,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...BadgeFonts,
		...PulseFonts,
		...CircleCheckFonts,
		...ButtonFonts,
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
Framerz2ohEzTkn.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default, {}, context),
			forwardLoader(stdin_default2, {}, context),
		]);
	},
};

// virtual:pricing-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PricingCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var pricing_card_default = ComponentWithRoot;
export { pricing_card_default as default };
