// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e4fc90c95afaebc0 "Das Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * text?: string // Text
 * progressVariant?: '25%' | '50%' | '75%' | '100%' // Progress Variant
 * hasImage?: boolean // Has Image
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-E4CW6ZGR.js";
import { stdin_default } from "./chunks/chunk-WNPLVTAM.js";
import "./chunks/chunk-ENY5TG7Y.js";
import "./chunks/chunk-OYMYRKFS.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-CQUJRBEV.js";
import "./chunks/chunk-7CFDZMPZ.js";
import { className, css, fonts } from "./chunks/chunk-B5JEBSFU.js";
import { routes } from "./chunks/chunk-BAX4IDEL.js";

// virtual:progress-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/JGv5AfjqvUzCKEYWRJIc/cuDlp9xiq70ADXUBe94v/avNJhzBiB.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getPropertyControls,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var VisualFonts = getFonts(stdin_default);
var ProgressBarFonts = getFonts(stdin_default2);
var ProgressBarControls = getPropertyControls(stdin_default2);
var serializationHash = "framer-kAJku";
var variantClassNames = {
	Y4U5YZzDb: "framer-v-1e3bzlh",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableEnumMap = {
	"100%": "dDpT82QBQ",
	"25%": "e8gOpf8Sh",
	"50%": "xQUMEpFhc",
	"75%": "rz0YCR2Hu",
};
var getProps = ({
	hasImage,
	height,
	id,
	image,
	progressVariant,
	text,
	title,
	width,
	...props
}) => {
	return {
		...props,
		ibjygwyMt: title ?? props.ibjygwyMt ?? "Discover",
		NbjSn3U2A:
			humanReadableEnumMap[progressVariant] ??
			progressVariant ??
			props.NbjSn3U2A ??
			"e8gOpf8Sh",
		ObwGwualD: image ??
			props.ObwGwualD ?? {
				pixelHeight: 2400,
				pixelWidth: 1808,
				src: "https://framerusercontent.com/images/D8h98KOCGKp13nuqhuv2w27gLg.png?width=1808&height=2400",
				srcSet:
					"https://framerusercontent.com/images/D8h98KOCGKp13nuqhuv2w27gLg.png?scale-down-to=1024&width=1808&height=2400 771w,https://framerusercontent.com/images/D8h98KOCGKp13nuqhuv2w27gLg.png?scale-down-to=2048&width=1808&height=2400 1542w,https://framerusercontent.com/images/D8h98KOCGKp13nuqhuv2w27gLg.png?width=1808&height=2400 1808w",
			},
		SJmBgdPmN: hasImage ?? props.SJmBgdPmN,
		VfkhGWHX4:
			text ??
			props.VfkhGWHX4 ??
			"We take time to explore your goals, context, audience, and constraints.",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		ibjygwyMt: ibjygwyMt2,
		VfkhGWHX4: VfkhGWHX42,
		NbjSn3U2A: NbjSn3U2A2,
		SJmBgdPmN: SJmBgdPmN2,
		ObwGwualD: ObwGwualD2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "Y4U5YZzDb",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1e3bzlh",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"Y4U5YZzDb"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-apmw76"}
							data-framer-name={"Inner Container"}
							layoutDependency={layoutDependency}
							layoutId={"u2ExiipHX"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1mb7a3l"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"rvalQD8Hg"}
							>
								{SJmBgdPmN2 !== false && (
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={124}
										width={"124px"}
										y={(componentViewport?.y || 0) + 0 + 0 + 0 + 0 + 0}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-1yt60wo-container"}
											layoutDependency={layoutDependency}
											layoutId={"e393PJzrF-container"}
											nodeId={"e393PJzrF"}
											rendersWithMotion={true}
											scopeId={"avNJhzBiB"}
										>
											{_jsx(stdin_default, {
												suppressHydrationWarning: true,
												Evc3NlKBm: "",
												height: "100%",
												id: "e393PJzrF",
												layoutId: "e393PJzrF",
												lEbR2_Enm: "",
												MEksf0gGs: "",
												mZ8YIOhfH: false,
												qr_eL5_qQ: toResponsiveImage(ObwGwualD2),
												style: {
													height: "100%",
													width: "100%",
												},
												tRQiAbNTk: false,
												width: "100%",
												XfrnL5PUK: "",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-vijjbr"}
									data-framer-name={"Titles"}
									layoutDependency={layoutDependency}
									layoutId={"QUcUkX2y1"}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-wyv7aq"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"LuQAE6Kmp"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={ibjygwyMt2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.h4
												suppressHydrationWarning={true}
												className={"framer-styles-preset-1key48k"}
												data-styles-preset={"dMiBmbIPR"}
											>
												{"Discover"}
											</motion.h4>
										</React.Fragment>
									</RichText>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-182vjo9"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"lT9hVyP_O"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgb(73, 80, 93))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={VfkhGWHX42}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-26kq2w"}
												data-styles-preset={"zuIVYXLhn"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgb(73, 80, 93)))",
												}}
											>
												{
													"We take time to explore your goals, context, audience, and constraints."
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<ComponentViewportProvider
								suppressHydrationWarning={true}
								height={200}
								width={`max(${componentViewport?.width || "100vw"}, 1px)`}
								y={(componentViewport?.y || 0) + 0 + 0 + 243}
							>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-ey86qt-container"}
									layoutDependency={layoutDependency}
									layoutId={"uq2Dlfq7j-container"}
									nodeId={"uq2Dlfq7j"}
									rendersWithMotion={true}
									scopeId={"avNJhzBiB"}
								>
									{_jsx(stdin_default2, {
										suppressHydrationWarning: true,
										height: "100%",
										id: "uq2Dlfq7j",
										layoutId: "uq2Dlfq7j",
										style: {
											width: "100%",
										},
										variant: matchVariant(NbjSn3U2A2),
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-kAJku.framer-1oh62uj, .framer-kAJku .framer-1oh62uj { display: block; }",
	".framer-kAJku.framer-1e3bzlh { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 237px; }",
	".framer-kAJku .framer-apmw76 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 90px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-kAJku .framer-1mb7a3l { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-kAJku .framer-1yt60wo-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 124px); position: relative; width: 124px; z-index: 1; }",
	".framer-kAJku .framer-vijjbr { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-kAJku .framer-wyv7aq, .framer-kAJku .framer-182vjo9 { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-kAJku .framer-ey86qt-container { flex: none; height: auto; position: relative; width: 100%; }",
	...css2,
	...css,
];
var FrameravNJhzBiB = withCSS(Component, css3, "framer-kAJku");
var stdin_default3 = FrameravNJhzBiB;
FrameravNJhzBiB.displayName = "Progress Card";
FrameravNJhzBiB.defaultProps = {
	height: 200,
	width: 237,
};
addPropertyControls(FrameravNJhzBiB, {
	ibjygwyMt: {
		defaultValue: "Discover",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	VfkhGWHX4: {
		defaultValue:
			"We take time to explore your goals, context, audience, and constraints.",
		displayTextArea: true,
		title: "Text",
		type: ControlType.String,
	},
	NbjSn3U2A: ProgressBarControls?.["variant"] && {
		...ProgressBarControls["variant"],
		defaultValue: "e8gOpf8Sh",
		description: void 0,
		hidden: void 0,
		title: "Progress Variant",
	},
	SJmBgdPmN: {
		defaultValue: false,
		title: "Has Image",
		type: ControlType.Boolean,
	},
	ObwGwualD: {
		__defaultAssetReference:
			"data:framer/asset-reference,D8h98KOCGKp13nuqhuv2w27gLg.png?originalFilename=Abstract+Gradient+Grid.png&width=1808&height=2400",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FrameravNJhzBiB,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...VisualFonts,
		...ProgressBarFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:progress-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProgressCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var progress_card_default = ComponentWithRoot;
export { progress_card_default as default };
