// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e4fc90c95afaebc0 "Das Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * badge?: string // Badge
 * title?: string // Title
 * showVideo?: boolean // Show Video
 * videoPoster?: {src: string, srcSet?: string, alt?: string} // Video Poster
 * videoFile?: string // Video File
 * tag?: string // Tag
}} Props

 */
import { stdin_default } from "./chunks/chunk-WNPLVTAM.js";
import "./chunks/chunk-ENY5TG7Y.js";
import "./chunks/chunk-OYMYRKFS.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-XTMKCPSV.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-CQUJRBEV.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-EANZ46VA.js";
import "./chunks/chunk-7CFDZMPZ.js";
import { className, css, fonts } from "./chunks/chunk-B5JEBSFU.js";
import { routes } from "./chunks/chunk-BAX4IDEL.js";

// virtual:project-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/tgnY20cd8QttaWYctxJ0/B8BJywEudnSjrCbrkcCn/noyINUR4K.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getPropertyControls,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var VisualFonts = getFonts(stdin_default);
var DividerFonts = getFonts(stdin_default2);
var VisualControls = getPropertyControls(stdin_default);
var enabledGestures = {
	iSzjMYKQX: {
		hover: true,
	},
};
var serializationHash = "framer-uxMuV";
var variantClassNames = {
	iSzjMYKQX: "framer-v-5oqp77",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.8,
	ease: [0.35, 0, 0, 1],
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	badge,
	height,
	id,
	image,
	showVideo,
	tag,
	title,
	videoFile,
	videoPoster,
	width,
	...props
}) => {
	return {
		...props,
		HRCziaW63: tag ?? props.HRCziaW63 ?? "Logo design",
		I4q9Y4gZc: badge ?? props.I4q9Y4gZc ?? "1 month",
		kgsK6qbet: showVideo ?? props.kgsK6qbet,
		nZ3OH7Ate: videoPoster ?? props.nZ3OH7Ate,
		vcduz5nii: image ?? props.vcduz5nii,
		VDspHbYah: videoFile ?? props.VDspHbYah,
		Xw9L8pbDy: title ?? props.Xw9L8pbDy ?? "Waterline\xA9",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		vcduz5nii: vcduz5nii2,
		I4q9Y4gZc: I4q9Y4gZc2,
		Xw9L8pbDy: Xw9L8pbDy2,
		kgsK6qbet: kgsK6qbet2,
		nZ3OH7Ate: nZ3OH7Ate2,
		VDspHbYah: VDspHbYah2,
		HRCziaW63: HRCziaW632,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "iSzjMYKQX",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className, className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-5oqp77",
							className4,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"iSzjMYKQX"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								"iSzjMYKQX-hover": {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1clq48c"}
							data-framer-name={"Visual Container"}
							layoutDependency={layoutDependency}
							layoutId={"CNQjUDbJC"}
							style={{
								borderBottomLeftRadius: 10,
								borderBottomRightRadius: 10,
								borderTopLeftRadius: 10,
								borderTopRightRadius: 10,
							}}
						>
							<ComponentViewportProvider
								suppressHydrationWarning={true}
								height={193}
								width={`max(${componentViewport?.width || "100vw"}, 1px)`}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 485.5) - 0 - 285.4) / 2 +
										0 +
										0) +
									0
								}
								{...addPropertyOverrides(
									{
										"iSzjMYKQX-hover": {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 200) - 0 - 285.4) / 2 +
													0 +
													0) +
												0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-6pkskz-container"}
									layoutDependency={layoutDependency}
									layoutId={"WAkKxh_3E-container"}
									nodeId={"WAkKxh_3E"}
									rendersWithMotion={true}
									scopeId={"noyINUR4K"}
									style={{
										scale: 1,
									}}
									variants={{
										"iSzjMYKQX-hover": {
											scale: 1.2,
										},
									}}
								>
									{_jsx(stdin_default, {
										suppressHydrationWarning: true,
										b1yLCVmjE: toResponsiveImage(nZ3OH7Ate2),
										bH2vzTj9R: VDspHbYah2,
										Evc3NlKBm: HRCziaW632,
										height: "100%",
										id: "WAkKxh_3E",
										layoutId: "WAkKxh_3E",
										qr_eL5_qQ: toResponsiveImage(vcduz5nii2),
										style: {
											height: "100%",
											width: "100%",
										},
										tRQiAbNTk: kgsK6qbet2,
										variant: matchVariant("txJ9749K_"),
										width: "100%",
										...addPropertyOverrides(
											{
												"iSzjMYKQX-hover": {
													variant: matchVariant("qMTjbBZ5g"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1cj1mlb"}
								data-framer-name={"Hover View"}
								layoutDependency={layoutDependency}
								layoutId={"LGhCZvMHt"}
								style={{
									backdropFilter: "blur(5px)",
									borderBottomLeftRadius: 12,
									borderBottomRightRadius: 12,
									borderTopLeftRadius: 12,
									borderTopRightRadius: 12,
									opacity: 0,
									WebkitBackdropFilter: "blur(5px)",
								}}
								variants={{
									"iSzjMYKQX-hover": {
										opacity: 1,
									},
								}}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1knpd8k"}
									data-framer-name={"Icon Container"}
									layoutDependency={layoutDependency}
									layoutId={"bVr3hsgVB"}
									style={{
										backgroundColor:
											"var(--token-1ad0dd99-5aec-4e1d-804a-3c603649eb34, rgb(255, 255, 255))",
										borderBottomLeftRadius: 100,
										borderBottomRightRadius: 100,
										borderTopLeftRadius: 100,
										borderTopRightRadius: 100,
									}}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-shzvry"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"ZvXyrz0tI"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-1myea0i"}
												data-styles-preset={"fYtfz6Zub"}
												dir={"auto"}
											>
												{"View"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
						</motion.div>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-fwaqlz"}
							data-framer-name={"Titles"}
							layoutDependency={layoutDependency}
							layoutId={"r9r4eAKYD"}
						>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-8ob7ro"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"UotWJbN0U"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.6))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={I4q9Y4gZc2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										suppressHydrationWarning={true}
										className={"framer-styles-preset-26kq2w"}
										data-styles-preset={"zuIVYXLhn"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.6)))",
										}}
									>
										{"Art Direction & Web"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-23r0lk"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"aj5ROkFYi"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-1vmkas2"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"CMKyhlqsp"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={Xw9L8pbDy2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h4
											suppressHydrationWarning={true}
											className={"framer-styles-preset-1key48k"}
											data-styles-preset={"dMiBmbIPR"}
										>
											{"waterline\xA9"}
										</motion.h4>
									</React.Fragment>
								</RichText>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-107y1jb"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"pnAxW6YOD"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={Xw9L8pbDy2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h4
											suppressHydrationWarning={true}
											className={"framer-styles-preset-1key48k"}
											data-styles-preset={"dMiBmbIPR"}
											dir={"auto"}
										>
											{"waterline\xA9"}
										</motion.h4>
									</React.Fragment>
								</RichText>
							</motion.div>
							<ComponentViewportProvider
								suppressHydrationWarning={true}
								height={1}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 485.5) - 0 - 285.4) / 2 +
										193 +
										0) +
									12 +
									79.4
								}
								{...addPropertyOverrides(
									{
										"iSzjMYKQX-hover": {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 200) - 0 - 285.4) / 2 +
													193 +
													0) +
												12 +
												79.4,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-7l80kt-container"}
									layoutDependency={layoutDependency}
									layoutId={"X7rZ6KAP8-container"}
									nodeId={"X7rZ6KAP8"}
									rendersWithMotion={true}
									scopeId={"noyINUR4K"}
								>
									{_jsx(stdin_default2, {
										suppressHydrationWarning: true,
										height: "100%",
										id: "X7rZ6KAP8",
										layoutId: "X7rZ6KAP8",
										style: {
											height: "100%",
											width: "100%",
										},
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-uxMuV.framer-ew6cpa, .framer-uxMuV .framer-ew6cpa { display: block; }",
	".framer-uxMuV.framer-5oqp77 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 554px; }",
	".framer-uxMuV .framer-1clq48c { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-uxMuV .framer-6pkskz-container { aspect-ratio: 1.4093264248704662 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 393px); position: relative; width: 1px; }",
	".framer-uxMuV .framer-1cj1mlb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; left: 0px; overflow: hidden; padding: 0px; pointer-events: none; position: absolute; top: 0px; width: 100%; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-uxMuV .framer-1knpd8k { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: var(--framer-aspect-ratio-supported, 100px); justify-content: center; overflow: visible; padding: 30px; position: relative; width: 100px; }",
	".framer-uxMuV .framer-shzvry, .framer-uxMuV .framer-8ob7ro { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-uxMuV .framer-fwaqlz { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 12px 0px 0px 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-uxMuV .framer-23r0lk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-uxMuV .framer-1vmkas2 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-uxMuV .framer-107y1jb { bottom: -40px; flex: none; height: auto; left: 0px; position: absolute; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-uxMuV .framer-7l80kt-container { flex: none; height: 1px; position: relative; width: 100%; }",
	".framer-uxMuV.framer-v-5oqp77.hover .framer-6pkskz-container { height: var(--framer-aspect-ratio-supported, 142px); }",
	".framer-uxMuV.framer-v-5oqp77.hover .framer-1vmkas2 { left: 0px; position: absolute; top: -40px; z-index: 1; }",
	".framer-uxMuV.framer-v-5oqp77.hover .framer-107y1jb { bottom: unset; left: unset; position: relative; }",
	...css2,
	...css,
	...css3,
];
var FramernoyINUR4K = withCSS(Component, css4, "framer-uxMuV");
var stdin_default3 = FramernoyINUR4K;
FramernoyINUR4K.displayName = "Project Card";
FramernoyINUR4K.defaultProps = {
	height: 485.5,
	width: 554,
};
addPropertyControls(FramernoyINUR4K, {
	vcduz5nii: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	I4q9Y4gZc: {
		defaultValue: "1 month",
		title: "Badge",
		type: ControlType.String,
	},
	Xw9L8pbDy: {
		defaultValue: "Waterline\xA9",
		title: "Title",
		type: ControlType.String,
	},
	kgsK6qbet: {
		defaultValue: false,
		title: "Show Video",
		type: ControlType.Boolean,
	},
	nZ3OH7Ate: {
		title: "Video Poster",
		type: ControlType.ResponsiveImage,
	},
	VDspHbYah: VisualControls?.["bH2vzTj9R"] && {
		...VisualControls["bH2vzTj9R"],
		__defaultAssetReference: "",
		description: void 0,
		hidden: void 0,
		title: "Video File",
	},
	HRCziaW63: {
		defaultValue: "Logo design",
		displayTextArea: false,
		title: "Tag",
		type: ControlType.String,
	},
});
addFonts(
	FramernoyINUR4K,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...VisualFonts,
		...DividerFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:project-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProjectCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var project_card_default = ComponentWithRoot;
export { project_card_default as default };
