// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e4fc90c95afaebc0 "Das Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' // Variant
 * row1Title?: string // Row 1 Title
 * row1ListItem1?: string // Row 1  List Item 1
 * row1ListItem2?: string // Row 1 List Item 2
 * row1ListItem3?: string // Row 1 List Item 3
 * row1Text?: string // Row 1 Text
 * row2Title?: string // Row 2 Title
 * row2ListItem1?: string // Row 2 List Item 1
 * row2ListItem2?: string // Row 2 List Item 2
 * row2ListItem3?: string // Row 2 List Item 3
 * row2Text?: string // Row 2 Text
 * row3Title?: string // Row 3 Title
 * row3ListItem1?: string // Row 3 List Item 1
 * row3ListItem2?: string // Row 3 List Item 2
 * row3ListItem3?: string // Row 3 List Item 3
 * row3Text?: string // Row 3 Text
 * row4Title?: string // Row 4 Title
 * row4ListItem1?: string // Row 4 List Item 1
 * row4ListItem2?: string // Row 4 List Item 2
 * row4ListItem3?: string // Row 4 List Item 3
 * row4Text?: string // Row 4 Text
 * row5Title?: string // Row 5 Title
 * row5ListItem1?: string // Row 5 List Item 1
 * row5ListItem2?: string // Row 5 List Item 2
 * row5ListItem3?: string // Row 5 List Item 3
 * row5Text?: string // Row 5 Text
}} Props

 */
import { stdin_default } from "./chunks/chunk-26F2U24H.js";
import "./chunks/chunk-GHRXF5NR.js";
import "./chunks/chunk-EANZ46VA.js";
import "./chunks/chunk-7CFDZMPZ.js";
import { AvoidLayoutJumping } from "./chunks/chunk-C2KZ2SUB.js";
import "./chunks/chunk-X37PU3JY.js";
import "./chunks/chunk-B5JEBSFU.js";
import { routes } from "./chunks/chunk-BAX4IDEL.js";

// virtual:services
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/y44Uc7NdQO3flkmrgMOc/c1w0gnbzcmTuEjwJUcpD/xwXSZ8qQb.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var LayoutJumpPreventerFonts = getFonts(AvoidLayoutJumping);
var ServiceCardFonts = getFonts(stdin_default);
var cycleOrder = ["LxVSm_KyN", "ENG0MA2Dg"];
var serializationHash = "framer-OQwWb";
var variantClassNames = {
	ENG0MA2Dg: "framer-v-dpxm2z",
	LxVSm_KyN: "framer-v-1grd38t",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.8,
	ease: [0.35, 0, 0, 1],
	type: "tween",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "LxVSm_KyN",
	Phone: "ENG0MA2Dg",
};
var getProps = ({
	height,
	id,
	row1ListItem1,
	row1ListItem2,
	row1ListItem3,
	row1Text,
	row1Title,
	row2ListItem1,
	row2ListItem2,
	row2ListItem3,
	row2Text,
	row2Title,
	row3ListItem1,
	row3ListItem2,
	row3ListItem3,
	row3Text,
	row3Title,
	row4ListItem1,
	row4ListItem2,
	row4ListItem3,
	row4Text,
	row4Title,
	row5ListItem1,
	row5ListItem2,
	row5ListItem3,
	row5Text,
	row5Title,
	width,
	...props
}) => {
	return {
		...props,
		bDNfihW8A: row5ListItem1 ?? props.bDNfihW8A ?? "Article layouts",
		bKlMyQ0RK: row2ListItem3 ?? props.bKlMyQ0RK ?? "Simple guidelines",
		cQNuvJPM6: row1Title ?? props.cQNuvJPM6 ?? "ART DIRECTION",
		DdgpNOGjh: row5Title ?? props.DdgpNOGjh ?? "EDITORIAL",
		GRiRZy3LL: row1ListItem1 ?? props.GRiRZy3LL ?? "Visual direction",
		hdUKn8chc: row3ListItem3 ?? props.hdUKn8chc ?? "Content templates",
		jeLXirADh: row4Title ?? props.jeLXirADh ?? "WEB DEVELOPMENT",
		k_aVbDoMT: row4ListItem2 ?? props.k_aVbDoMT ?? "Clean code",
		kaZiziRVA: row1ListItem3 ?? props.kaZiziRVA ?? "Layout system",
		LT_wyzs3J:
			row4Text ??
			props.LT_wyzs3J ??
			"We design and build websites that are fast, responsive, and straightforward to maintain. We focus on structure first, then details\u2014so the site works well now and still works well later.",
		LvsvUJH15: row2ListItem2 ?? props.LvsvUJH15 ?? "Visual system",
		MA69sQCkz:
			row3Text ??
			props.MA69sQCkz ??
			"We design marketing assets that communicate quickly and look consistent across channels. This can include campaign concepts, landing pages, social content, and a repeatable system for your team.",
		N4MWW2Y3V: row3ListItem1 ?? props.N4MWW2Y3V ?? "Campaign assets",
		nlJVgmMM5: row2Title ?? props.nlJVgmMM5 ?? "BRANDING",
		Nr6zVMQsz:
			row1Text ??
			props.Nr6zVMQsz ??
			"We set the visual direction for a brand or a project. That includes references, layout rules, typography choices, and the overall look and feel\u2014so every page and asset follows the same logic.",
		O_N3wUG6r:
			row2Text ??
			props.O_N3wUG6r ??
			"We build or refine your brand identity so it\u2019s clear, consistent, and practical. You get the essentials done properly: foundations, usage rules, and a system that can grow with your needs.",
		P8SRlafoK: row1ListItem2 ?? props.P8SRlafoK ?? "Type rules",
		PeaJQaXAx: row3ListItem2 ?? props.PeaJQaXAx ?? "Landing pages",
		S5vHIj4se: row5ListItem2 ?? props.S5vHIj4se ?? "Clear hierarchy",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "LxVSm_KyN",
		wCSwZxhTm: row3Title ?? props.wCSwZxhTm ?? "MARKETING",
		wghuVBvO4: row4ListItem1 ?? props.wghuVBvO4 ?? "Responsive build",
		WxE925M3D: row5ListItem3 ?? props.WxE925M3D ?? "Reading rhythm",
		XhduP6ypy:
			row5Text ??
			props.XhduP6ypy ??
			"We create editorial layouts for content-heavy pages like journals, case studies, and guides. We focus on readability, hierarchy, and rhythm\u2014so content feels organized and easy to scan.",
		xMiZDp9_7: row4ListItem3 ?? props.xMiZDp9_7 ?? "Fast loading",
		zv5M6R3ye: row2ListItem1 ?? props.zv5M6R3ye ?? "Brand basics",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		cQNuvJPM6: cQNuvJPM62,
		GRiRZy3LL: GRiRZy3LL2,
		P8SRlafoK: P8SRlafoK2,
		kaZiziRVA: kaZiziRVA2,
		Nr6zVMQsz: Nr6zVMQsz2,
		nlJVgmMM5: nlJVgmMM52,
		zv5M6R3ye: zv5M6R3ye2,
		LvsvUJH15: LvsvUJH152,
		bKlMyQ0RK: bKlMyQ0RK2,
		O_N3wUG6r: O_N3wUG6r2,
		wCSwZxhTm: wCSwZxhTm2,
		N4MWW2Y3V: N4MWW2Y3V2,
		PeaJQaXAx: PeaJQaXAx2,
		hdUKn8chc: hdUKn8chc2,
		MA69sQCkz: MA69sQCkz2,
		jeLXirADh: jeLXirADh2,
		wghuVBvO4: wghuVBvO42,
		k_aVbDoMT: k_aVbDoMT2,
		xMiZDp9_7: xMiZDp9_72,
		LT_wyzs3J: LT_wyzs3J2,
		DdgpNOGjh: DdgpNOGjh2,
		bDNfihW8A: bDNfihW8A2,
		S5vHIj4se: S5vHIj4se2,
		WxE925M3D: WxE925M3D2,
		XhduP6ypy: XhduP6ypy2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "LxVSm_KyN",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1grd38t",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"LxVSm_KyN"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								ENG0MA2Dg: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider suppressHydrationWarning={true}>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-a3577r-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"GJpnXPSZr-container"}
								nodeId={"GJpnXPSZr"}
								rendersWithMotion={true}
								scopeId={"xwXSZ8qQb"}
							>
								<AvoidLayoutJumping
									suppressHydrationWarning={true}
									direction={"both"}
									height={"100%"}
									id={"GJpnXPSZr"}
									layoutId={"GJpnXPSZr"}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={88}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 643) - 0 - 472) / 2 + 0 + 0)
							}
							{...addPropertyOverrides(
								{
									ENG0MA2Dg: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 978) - 0 - 472) / 2 +
												0 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-eq6nyx-container"}
								layoutDependency={layoutDependency}
								layoutId={"Vg6nDS1nv-container"}
								nodeId={"Vg6nDS1nv"}
								rendersWithMotion={true}
								scopeId={"xwXSZ8qQb"}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									b7nOzidpu: cQNuvJPM62,
									d0yycjRhh: GRiRZy3LL2,
									height: "100%",
									id: "Vg6nDS1nv",
									jpGSdGfHF: Nr6zVMQsz2,
									Kat2WlRaM: kaZiziRVA2,
									L81Y_l118: P8SRlafoK2,
									layoutId: "Vg6nDS1nv",
									style: {
										width: "100%",
									},
									tiKfb7xcS: "01",
									variant: matchVariant("naqrRPRsv"),
									width: "100%",
									...addPropertyOverrides(
										{
											ENG0MA2Dg: {
												variant: matchVariant("QCZn3xwCY"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={88}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 643) - 0 - 472) / 2 + 88 + 8)
							}
							{...addPropertyOverrides(
								{
									ENG0MA2Dg: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 978) - 0 - 472) / 2 +
												88 +
												8),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-118fox8-container"}
								layoutDependency={layoutDependency}
								layoutId={"hdhr9hxdr-container"}
								nodeId={"hdhr9hxdr"}
								rendersWithMotion={true}
								scopeId={"xwXSZ8qQb"}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									b7nOzidpu: nlJVgmMM52,
									d0yycjRhh: zv5M6R3ye2,
									height: "100%",
									id: "hdhr9hxdr",
									jpGSdGfHF: O_N3wUG6r2,
									Kat2WlRaM: bKlMyQ0RK2,
									L81Y_l118: LvsvUJH152,
									layoutId: "hdhr9hxdr",
									style: {
										width: "100%",
									},
									tiKfb7xcS: "02",
									variant: matchVariant("fOGxxBr1Y"),
									width: "100%",
									...addPropertyOverrides(
										{
											ENG0MA2Dg: {
												variant: matchVariant("UGhTgEge3"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={88}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 643) - 0 - 472) / 2 + 176 + 16)
							}
							{...addPropertyOverrides(
								{
									ENG0MA2Dg: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 978) - 0 - 472) / 2 +
												176 +
												16),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-18sf3xd-container"}
								layoutDependency={layoutDependency}
								layoutId={"maLFsQCzT-container"}
								nodeId={"maLFsQCzT"}
								rendersWithMotion={true}
								scopeId={"xwXSZ8qQb"}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									b7nOzidpu: wCSwZxhTm2,
									d0yycjRhh: N4MWW2Y3V2,
									height: "100%",
									id: "maLFsQCzT",
									jpGSdGfHF: MA69sQCkz2,
									Kat2WlRaM: hdUKn8chc2,
									L81Y_l118: PeaJQaXAx2,
									layoutId: "maLFsQCzT",
									style: {
										width: "100%",
									},
									tiKfb7xcS: "03",
									variant: matchVariant("fOGxxBr1Y"),
									width: "100%",
									...addPropertyOverrides(
										{
											ENG0MA2Dg: {
												variant: matchVariant("UGhTgEge3"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={88}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 643) - 0 - 472) / 2 + 264 + 24)
							}
							{...addPropertyOverrides(
								{
									ENG0MA2Dg: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 978) - 0 - 472) / 2 +
												264 +
												24),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-16h1y7f-container"}
								layoutDependency={layoutDependency}
								layoutId={"LMDaR_GNV-container"}
								nodeId={"LMDaR_GNV"}
								rendersWithMotion={true}
								scopeId={"xwXSZ8qQb"}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									b7nOzidpu: jeLXirADh2,
									d0yycjRhh: wghuVBvO42,
									height: "100%",
									id: "LMDaR_GNV",
									jpGSdGfHF: LT_wyzs3J2,
									Kat2WlRaM: xMiZDp9_72,
									L81Y_l118: k_aVbDoMT2,
									layoutId: "LMDaR_GNV",
									style: {
										width: "100%",
									},
									tiKfb7xcS: "04",
									variant: matchVariant("fOGxxBr1Y"),
									width: "100%",
									...addPropertyOverrides(
										{
											ENG0MA2Dg: {
												variant: matchVariant("UGhTgEge3"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={88}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 643) - 0 - 472) / 2 + 352 + 32)
							}
							{...addPropertyOverrides(
								{
									ENG0MA2Dg: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 978) - 0 - 472) / 2 +
												352 +
												32),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-1h5d1y9-container"}
								layoutDependency={layoutDependency}
								layoutId={"yGU0KX2Jm-container"}
								nodeId={"yGU0KX2Jm"}
								rendersWithMotion={true}
								scopeId={"xwXSZ8qQb"}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									b7nOzidpu: DdgpNOGjh2,
									d0yycjRhh: bDNfihW8A2,
									height: "100%",
									id: "yGU0KX2Jm",
									jpGSdGfHF: XhduP6ypy2,
									Kat2WlRaM: WxE925M3D2,
									L81Y_l118: S5vHIj4se2,
									layoutId: "yGU0KX2Jm",
									style: {
										width: "100%",
									},
									tiKfb7xcS: "05",
									variant: matchVariant("fOGxxBr1Y"),
									width: "100%",
									...addPropertyOverrides(
										{
											ENG0MA2Dg: {
												variant: matchVariant("UGhTgEge3"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-OQwWb.framer-4sjk7l, .framer-OQwWb .framer-4sjk7l { display: block; }",
	".framer-OQwWb.framer-1grd38t { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1120px; }",
	".framer-OQwWb .framer-a3577r-container { flex: none; height: auto; left: 0px; position: absolute; top: 0px; width: auto; z-index: 1; }",
	".framer-OQwWb .framer-eq6nyx-container, .framer-OQwWb .framer-118fox8-container, .framer-OQwWb .framer-18sf3xd-container, .framer-OQwWb .framer-16h1y7f-container, .framer-OQwWb .framer-1h5d1y9-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-OQwWb.framer-v-dpxm2z.framer-1grd38t { width: 390px; }",
];
var FramerxwXSZ8qQb = withCSS(Component, css, "framer-OQwWb");
var stdin_default2 = FramerxwXSZ8qQb;
FramerxwXSZ8qQb.displayName = "Services";
FramerxwXSZ8qQb.defaultProps = {
	height: 643,
	width: 1120,
};
addPropertyControls(FramerxwXSZ8qQb, {
	variant: {
		options: ["LxVSm_KyN", "ENG0MA2Dg"],
		optionTitles: ["Desktop", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	cQNuvJPM6: {
		defaultValue: "ART DIRECTION",
		title: "Row 1 Title",
		type: ControlType.String,
	},
	GRiRZy3LL: {
		defaultValue: "Visual direction",
		displayTextArea: false,
		title: "Row 1  List Item 1",
		type: ControlType.String,
	},
	P8SRlafoK: {
		defaultValue: "Type rules",
		displayTextArea: false,
		title: "Row 1 List Item 2",
		type: ControlType.String,
	},
	kaZiziRVA: {
		defaultValue: "Layout system",
		displayTextArea: false,
		title: "Row 1 List Item 3",
		type: ControlType.String,
	},
	Nr6zVMQsz: {
		defaultValue:
			"We set the visual direction for a brand or a project. That includes references, layout rules, typography choices, and the overall look and feel\u2014so every page and asset follows the same logic.",
		displayTextArea: true,
		title: "Row 1 Text",
		type: ControlType.String,
	},
	nlJVgmMM5: {
		defaultValue: "BRANDING",
		title: "Row 2 Title",
		type: ControlType.String,
	},
	zv5M6R3ye: {
		defaultValue: "Brand basics",
		displayTextArea: false,
		title: "Row 2 List Item 1",
		type: ControlType.String,
	},
	LvsvUJH15: {
		defaultValue: "Visual system",
		displayTextArea: false,
		title: "Row 2 List Item 2",
		type: ControlType.String,
	},
	bKlMyQ0RK: {
		defaultValue: "Simple guidelines",
		displayTextArea: false,
		title: "Row 2 List Item 3",
		type: ControlType.String,
	},
	O_N3wUG6r: {
		defaultValue:
			"We build or refine your brand identity so it\u2019s clear, consistent, and practical. You get the essentials done properly: foundations, usage rules, and a system that can grow with your needs.",
		displayTextArea: true,
		title: "Row 2 Text",
		type: ControlType.String,
	},
	wCSwZxhTm: {
		defaultValue: "MARKETING",
		title: "Row 3 Title",
		type: ControlType.String,
	},
	N4MWW2Y3V: {
		defaultValue: "Campaign assets",
		displayTextArea: false,
		title: "Row 3 List Item 1",
		type: ControlType.String,
	},
	PeaJQaXAx: {
		defaultValue: "Landing pages",
		displayTextArea: false,
		title: "Row 3 List Item 2",
		type: ControlType.String,
	},
	hdUKn8chc: {
		defaultValue: "Content templates",
		displayTextArea: false,
		title: "Row 3 List Item 3",
		type: ControlType.String,
	},
	MA69sQCkz: {
		defaultValue:
			"We design marketing assets that communicate quickly and look consistent across channels. This can include campaign concepts, landing pages, social content, and a repeatable system for your team.",
		displayTextArea: true,
		title: "Row 3 Text",
		type: ControlType.String,
	},
	jeLXirADh: {
		defaultValue: "WEB DEVELOPMENT",
		title: "Row 4 Title",
		type: ControlType.String,
	},
	wghuVBvO4: {
		defaultValue: "Responsive build",
		displayTextArea: false,
		title: "Row 4 List Item 1",
		type: ControlType.String,
	},
	k_aVbDoMT: {
		defaultValue: "Clean code",
		displayTextArea: false,
		title: "Row 4 List Item 2",
		type: ControlType.String,
	},
	xMiZDp9_7: {
		defaultValue: "Fast loading",
		displayTextArea: false,
		title: "Row 4 List Item 3",
		type: ControlType.String,
	},
	LT_wyzs3J: {
		defaultValue:
			"We design and build websites that are fast, responsive, and straightforward to maintain. We focus on structure first, then details\u2014so the site works well now and still works well later.",
		displayTextArea: true,
		title: "Row 4 Text",
		type: ControlType.String,
	},
	DdgpNOGjh: {
		defaultValue: "EDITORIAL",
		title: "Row 5 Title",
		type: ControlType.String,
	},
	bDNfihW8A: {
		defaultValue: "Article layouts",
		displayTextArea: false,
		title: "Row 5 List Item 1",
		type: ControlType.String,
	},
	S5vHIj4se: {
		defaultValue: "Clear hierarchy",
		displayTextArea: false,
		title: "Row 5 List Item 2",
		type: ControlType.String,
	},
	WxE925M3D: {
		defaultValue: "Reading rhythm",
		displayTextArea: false,
		title: "Row 5 List Item 3",
		type: ControlType.String,
	},
	XhduP6ypy: {
		defaultValue:
			"We create editorial layouts for content-heavy pages like journals, case studies, and guides. We focus on readability, hierarchy, and rhythm\u2014so content feels organized and easy to scan.",
		displayTextArea: true,
		title: "Row 5 Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerxwXSZ8qQb,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...LayoutJumpPreventerFonts,
		...ServiceCardFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:services
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "ENG0MA2Dg",
	xl: "LxVSm_KyN",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ServicesFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var services_default = ComponentWithRoot;
export { services_default as default };
