// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e4fc90c95afaebc0 "Das Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * shareOption?: 'X (Twitter)' | 'LinkedIn' | 'Facebook' | 'Native Share' // Share Option
 * borderRadius?: number // Border Radius
 * backgroundColor?: string // Background Color
 * textColor?: string // Text Color
 * padding?: number // Padding
 * iconSize?: number // Icon Size
}} Props

 */
import { routes } from "./chunks/chunk-BAX4IDEL.js";

// virtual:share-button
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/t2FwPuqW9e0p4lKaFVbe/eTtIMqLKgB3oUzBua6pO/ShareButton.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, startTransition } from "react";
import { addPropertyControls, ControlType } from "unframer";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
var __unframerNavigator =
	typeof __unframerWindow !== "undefined" ? navigator : void 0;
function ShareButton(props) {
	const {
		shareOption = "native",
		borderRadius = 8,
		backgroundColor = "#000000",
		textColor = "#FFFFFF",
		font,
		padding = 12,
		iconSize = 16,
	} = props;
	const [isHovered, setIsHovered] = useState(false);
	const handleShare = async () => {
		if (typeof __unframerWindow === "undefined") return;
		const url = __unframerWindow.location.href;
		const title = document.title;
		switch (shareOption) {
			case "x":
				__unframerWindow.open(
					`https://twitter.com/intent/tweet?url=${encodeURIComponent(url)}&text=${encodeURIComponent(title)}`,
					"_blank",
				);
				break;
			case "linkedin":
				__unframerWindow.open(
					`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`,
					"_blank",
				);
				break;
			case "facebook":
				__unframerWindow.open(
					`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`,
					"_blank",
				);
				break;
			case "native":
				if (__unframerNavigator.share) {
					try {
						await __unframerNavigator.share({
							title,
							url,
						});
					} catch (err) {
						console.log("Error sharing:", err);
					}
				} else {
					__unframerNavigator.clipboard.writeText(url);
					alert("Link copied to clipboard!");
				}
				break;
		}
	};
	const getIcon = () => {
		const iconColor = textColor;
		switch (shareOption) {
			case "x":
				return (
					<svg
						suppressHydrationWarning={true}
						width={iconSize}
						height={iconSize}
						viewBox={"0 0 24 24"}
						fill={iconColor}
					>
						<path
							suppressHydrationWarning={true}
							d={
								"M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"
							}
						/>
					</svg>
				);
			case "linkedin":
				return (
					<svg
						suppressHydrationWarning={true}
						width={iconSize}
						height={iconSize}
						viewBox={"0 0 24 24"}
						fill={iconColor}
					>
						<path
							suppressHydrationWarning={true}
							d={
								"M20.5 2h-17A1.5 1.5 0 002 3.5v17A1.5 1.5 0 003.5 22h17a1.5 1.5 0 001.5-1.5v-17A1.5 1.5 0 0020.5 2zM8 19H5v-9h3zM6.5 8.25A1.75 1.75 0 118.3 6.5a1.78 1.78 0 01-1.8 1.75zM19 19h-3v-4.74c0-1.42-.6-1.93-1.38-1.93A1.74 1.74 0 0013 14.19a.66.66 0 000 .14V19h-3v-9h2.9v1.3a3.11 3.11 0 012.7-1.4c1.55 0 3.36.86 3.36 3.66z"
							}
						/>
					</svg>
				);
			case "facebook":
				return (
					<svg
						suppressHydrationWarning={true}
						width={iconSize}
						height={iconSize}
						viewBox={"0 0 24 24"}
						fill={iconColor}
					>
						<path
							suppressHydrationWarning={true}
							d={
								"M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"
							}
						/>
					</svg>
				);
			case "native":
				return (
					<svg
						suppressHydrationWarning={true}
						width={iconSize}
						height={iconSize}
						viewBox={"0 0 256 256"}
						fill={"none"}
					>
						<path
							suppressHydrationWarning={true}
							d={
								"M180,104h20a8,8,0,0,1,8,8v96a8,8,0,0,1-8,8H56a8,8,0,0,1-8-8V112a8,8,0,0,1,8-8H76"
							}
							fill={"none"}
							stroke={iconColor}
							strokeLinecap={"round"}
							strokeLinejoin={"round"}
							strokeWidth={"24"}
						/>
						<polyline
							suppressHydrationWarning={true}
							points={"88 64 128 24 168 64"}
							fill={"none"}
							stroke={iconColor}
							strokeLinecap={"round"}
							strokeLinejoin={"round"}
							strokeWidth={"24"}
						/>
						<line
							suppressHydrationWarning={true}
							x1={"128"}
							y1={"24"}
							x2={"128"}
							y2={"136"}
							fill={"none"}
							stroke={iconColor}
							strokeLinecap={"round"}
							strokeLinejoin={"round"}
							strokeWidth={"24"}
						/>
					</svg>
				);
		}
	};
	const getLabel = () => {
		switch (shareOption) {
			case "x":
				return "Share on X";
			case "linkedin":
				return "Share on LinkedIn";
			case "facebook":
				return "Share on Facebook";
			case "native":
				return "Share";
		}
	};
	return (
		<button
			suppressHydrationWarning={true}
			onClick={handleShare}
			onMouseEnter={() => startTransition(() => setIsHovered(true))}
			onMouseLeave={() => startTransition(() => setIsHovered(false))}
			style={{
				display: "flex",
				alignItems: "center",
				gap: 8,
				padding,
				backgroundColor,
				color: textColor,
				border: "none",
				borderRadius,
				cursor: "pointer",
				transition: "all 0.2s ease",
				opacity: isHovered ? 0.8 : 1,
				transform: isHovered ? "translateY(-1px)" : "translateY(0)",
				...font,
				minWidth: "max-content",
			}}
		>
			{getIcon()}
		</button>
	);
}
addPropertyControls(ShareButton, {
	shareOption: {
		type: ControlType.Enum,
		title: "Share Option",
		options: ["x", "linkedin", "facebook", "native"],
		optionTitles: ["X (Twitter)", "LinkedIn", "Facebook", "Native Share"],
		defaultValue: "native",
		displaySegmentedControl: false,
	},
	borderRadius: {
		type: ControlType.Number,
		title: "Border Radius",
		defaultValue: 8,
		min: 0,
		max: 32,
		step: 1,
		unit: "px",
	},
	backgroundColor: {
		type: ControlType.Color,
		title: "Background Color",
		defaultValue: "#000000",
	},
	textColor: {
		type: ControlType.Color,
		title: "Text Color",
		defaultValue: "#FFFFFF",
	},
	padding: {
		type: ControlType.Number,
		title: "Padding",
		defaultValue: 12,
		min: 0,
		max: 32,
		step: 1,
		unit: "px",
	},
	iconSize: {
		type: ControlType.Number,
		title: "Icon Size",
		defaultValue: 16,
		min: 8,
		max: 48,
		step: 1,
		unit: "px",
	},
});

// virtual:share-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<ShareButton suppressHydrationWarning={true} {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ShareButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={ShareButton}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, ShareButton);
var share_button_default = ComponentWithRoot;
export { share_button_default as default };
