// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e4fc90c95afaebc0 "Das Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * name?: string // Name
 * role?: string // Role
 * behanceLink?: string // Behance Link
 * instagramLink?: string // Instagram Link
 * xLink?: string // X Link
}} Props

 */
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-EZ24G2IO.js";
import {
	stdin_default as stdin_default2,
	stdin_default2 as stdin_default3,
} from "./chunks/chunk-NAPP6YCM.js";
import {
	stdin_default,
	stdin_default2 as stdin_default4,
} from "./chunks/chunk-NBYVXD6V.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-46Q3S57O.js";
import { className, css, fonts } from "./chunks/chunk-7CFDZMPZ.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-B5JEBSFU.js";
import { routes } from "./chunks/chunk-BAX4IDEL.js";

// virtual:team-row
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/NXVeVxbKuS3CdnqIQ3ce/JlQh4M7MDnuuy6rZc917/vcg9tNQW_.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var SocialButtonFonts = getFonts(stdin_default4);
var cycleOrder = ["wbZEuhaRj", "QOTRRDlBZ"];
var serializationHash = "framer-oKzvO";
var variantClassNames = {
	QOTRRDlBZ: "framer-v-72igpp",
	wbZEuhaRj: "framer-v-1ppvcsj",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "wbZEuhaRj",
	Phone: "QOTRRDlBZ",
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	behanceLink,
	height,
	id,
	image,
	instagramLink,
	name1,
	role,
	width,
	xLink,
	...props
}) => {
	return {
		...props,
		Aiw_7yw5S: behanceLink ?? props.Aiw_7yw5S,
		CGQWd6Nof: name1 ?? props.CGQWd6Nof ?? "Ava Thiery",
		IGwwsmMR9: role ?? props.IGwwsmMR9 ?? "Founder",
		kuh5027FJ: image ?? props.kuh5027FJ,
		Pvy1MHlAQ: instagramLink ?? props.Pvy1MHlAQ,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "wbZEuhaRj",
		WG2It9KCI: xLink ?? props.WG2It9KCI,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		kuh5027FJ: kuh5027FJ2,
		CGQWd6Nof: CGQWd6Nof2,
		IGwwsmMR9: IGwwsmMR92,
		Aiw_7yw5S: Aiw_7yw5S2,
		Pvy1MHlAQ: Pvy1MHlAQ2,
		WG2It9KCI: WG2It9KCI2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "wbZEuhaRj",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className4, className3, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "QOTRRDlBZ") return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "QOTRRDlBZ") return false;
		return true;
	};
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1ppvcsj",
							className5,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"wbZEuhaRj"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-b0855fb1-4440-4893-84c5-520cb7210ce4, rgba(90, 98, 113, 0.5))",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							...style,
						}}
						{...addPropertyOverrides(
							{
								QOTRRDlBZ: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1locatp"}
							data-framer-name={"Row"}
							layoutDependency={layoutDependency}
							layoutId={"rJgRfkqPV"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-198196v"}
								data-framer-name={"Title Container"}
								layoutDependency={layoutDependency}
								layoutId={"yt_TJv2oi"}
							>
								<Image
									suppressHydrationWarning={true}
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 84) - 24 - 60) / 2 +
													0 +
													0) +
												0 +
												0 +
												0,
										),
										pixelHeight: 1200,
										pixelWidth: 904,
										sizes: "60px",
										...toResponsiveImage(kuh5027FJ2),
									}}
									className={"framer-qi60dw"}
									layoutDependency={layoutDependency}
									layoutId={"Tl4ACqchp"}
									style={{
										borderBottomLeftRadius: 10,
										borderBottomRightRadius: 10,
										borderTopLeftRadius: 10,
										borderTopRightRadius: 10,
									}}
									{...addPropertyOverrides(
										{
											QOTRRDlBZ: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 124) - 24 - 120) /
																2 +
																0 +
																0) +
															0 +
															0 +
															0,
													),
													pixelHeight: 1200,
													pixelWidth: 904,
													sizes: "100px",
													...toResponsiveImage(kuh5027FJ2),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-ux00ow"}
									data-framer-name={"Details"}
									layoutDependency={layoutDependency}
									layoutId={"VXQ4uX2hS"}
								>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-e8q0x1"}
										data-framer-name={"Name"}
										layoutDependency={layoutDependency}
										layoutId={"TWpyAVMIH"}
									>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-jgu817"}
											data-framer-name={"Name"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"H44bXsEup"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(0, 0, 0))",
											}}
											text={CGQWd6Nof2}
											variants={{
												QOTRRDlBZ: {
													"--extracted-1w1cjl5":
														"var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(0, 0, 0))",
												},
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													QOTRRDlBZ: {
														children: (
															<React.Fragment>
																<motion.h6
																	suppressHydrationWarning={true}
																	className={"framer-styles-preset-9d6j7p"}
																	data-styles-preset={"Mk5Vgse8Z"}
																	dir={"auto"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(0, 0, 0)))",
																	}}
																>
																	{"Ava Thiery"}
																</motion.h6>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-26kq2w"}
													data-styles-preset={"zuIVYXLhn"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(0, 0, 0)))",
													}}
												>
													{"Quiet Herbarium +BR"}
												</motion.p>
											</React.Fragment>
										</RichText>
										{isDisplayed() && (
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-usz3ri"}
												data-framer-name={"Mobile Role"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"uNO4NXXcU"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7))",
												}}
												text={IGwwsmMR92}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-33bebx"}
														data-styles-preset={"Wm4ZNpeAE"}
														dir={"auto"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7)))",
														}}
													>
														{"Founder"}
													</motion.p>
												</React.Fragment>
											</RichText>
										)}
									</motion.div>
									{isDisplayed() && (
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-1i6d0gy"}
											data-framer-name={"Mobile Social Icons"}
											layoutDependency={layoutDependency}
											layoutId={"rn5hdKh0h"}
										>
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={36}
												{...addPropertyOverrides(
													{
														QOTRRDlBZ: {
															y:
																(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 124) -
																	24 -
																	120) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																10.9 +
																0 +
																62.2 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-wvr737-container"}
													data-framer-name={"Behance"}
													layoutDependency={layoutDependency}
													layoutId={"FQVmHy5q1-container"}
													name={"Behance"}
													nodeId={"FQVmHy5q1"}
													rendersWithMotion={true}
													scopeId={"vcg9tNQW_"}
												>
													{_jsx(stdin_default4, {
														suppressHydrationWarning: true,
														height: "100%",
														id: "FQVmHy5q1",
														iYO4wDcal: stdin_default,
														layoutId: "FQVmHy5q1",
														name: "Behance",
														w999g8Uw3: Aiw_7yw5S2,
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={36}
												{...addPropertyOverrides(
													{
														QOTRRDlBZ: {
															y:
																(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 124) -
																	24 -
																	120) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																10.9 +
																0 +
																62.2 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-1xk8oge-container"}
													data-framer-name={"Instagram"}
													layoutDependency={layoutDependency}
													layoutId={"DqPS5wyQW-container"}
													name={"Instagram"}
													nodeId={"DqPS5wyQW"}
													rendersWithMotion={true}
													scopeId={"vcg9tNQW_"}
												>
													{_jsx(stdin_default4, {
														suppressHydrationWarning: true,
														height: "100%",
														id: "DqPS5wyQW",
														iYO4wDcal: stdin_default3,
														layoutId: "DqPS5wyQW",
														name: "Instagram",
														w999g8Uw3: Pvy1MHlAQ2,
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={36}
												{...addPropertyOverrides(
													{
														QOTRRDlBZ: {
															y:
																(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 124) -
																	24 -
																	120) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																10.9 +
																0 +
																62.2 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-10y5ju1-container"}
													data-framer-name={"X"}
													layoutDependency={layoutDependency}
													layoutId={"MSdcFlez7-container"}
													name={"X"}
													nodeId={"MSdcFlez7"}
													rendersWithMotion={true}
													scopeId={"vcg9tNQW_"}
												>
													{_jsx(stdin_default4, {
														suppressHydrationWarning: true,
														height: "100%",
														id: "MSdcFlez7",
														iYO4wDcal: stdin_default2,
														layoutId: "MSdcFlez7",
														name: "X",
														w999g8Uw3: WG2It9KCI2,
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										</motion.div>
									)}
								</motion.div>
							</motion.div>
							{isDisplayed1() && (
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-15pmg22"}
									data-framer-name={"Badge"}
									layoutDependency={layoutDependency}
									layoutId={"JvbgcM8S2"}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-11fsdq6"}
										data-framer-name={"Role"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"XoIZcD1Xp"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(0, 0, 0))",
										}}
										text={IGwwsmMR92}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-t7dvh9"}
												data-styles-preset={"vkgsOTgUD"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(0, 0, 0)))",
												}}
											>
												{"03"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							)}
							{isDisplayed1() && (
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-m9x87o"}
									data-framer-name={"Social Icons"}
									layoutDependency={layoutDependency}
									layoutId={"DbgLyiZLT"}
								>
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={36}
										y={
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 84) - 24 - 60) / 2 +
												0 +
												0) +
											0 +
											0 +
											12
										}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-x5ghtn-container"}
											data-framer-name={"Behance"}
											layoutDependency={layoutDependency}
											layoutId={"PCX6yN_WY-container"}
											name={"Behance"}
											nodeId={"PCX6yN_WY"}
											rendersWithMotion={true}
											scopeId={"vcg9tNQW_"}
										>
											{_jsx(stdin_default4, {
												suppressHydrationWarning: true,
												height: "100%",
												id: "PCX6yN_WY",
												iYO4wDcal: stdin_default,
												layoutId: "PCX6yN_WY",
												name: "Behance",
												w999g8Uw3: Aiw_7yw5S2,
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={36}
										y={
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 84) - 24 - 60) / 2 +
												0 +
												0) +
											0 +
											0 +
											12
										}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-1v2l5v5-container"}
											data-framer-name={"Instagram"}
											layoutDependency={layoutDependency}
											layoutId={"zE9Qsuatq-container"}
											name={"Instagram"}
											nodeId={"zE9Qsuatq"}
											rendersWithMotion={true}
											scopeId={"vcg9tNQW_"}
										>
											{_jsx(stdin_default4, {
												suppressHydrationWarning: true,
												height: "100%",
												id: "zE9Qsuatq",
												iYO4wDcal: stdin_default3,
												layoutId: "zE9Qsuatq",
												name: "Instagram",
												w999g8Uw3: Pvy1MHlAQ2,
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={36}
										y={
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 84) - 24 - 60) / 2 +
												0 +
												0) +
											0 +
											0 +
											12
										}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-1stu0et-container"}
											data-framer-name={"X"}
											layoutDependency={layoutDependency}
											layoutId={"JJvtK1rZt-container"}
											name={"X"}
											nodeId={"JJvtK1rZt"}
											rendersWithMotion={true}
											scopeId={"vcg9tNQW_"}
										>
											{_jsx(stdin_default4, {
												suppressHydrationWarning: true,
												height: "100%",
												id: "JJvtK1rZt",
												iYO4wDcal: stdin_default2,
												layoutId: "JJvtK1rZt",
												name: "X",
												w999g8Uw3: WG2It9KCI2,
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-oKzvO.framer-7lismf, .framer-oKzvO .framer-7lismf { display: block; }",
	".framer-oKzvO.framer-1ppvcsj { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px 0px 24px 0px; position: relative; width: 1200px; }",
	".framer-oKzvO .framer-1locatp { display: grid; flex: none; gap: 0px 8px; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(4, minmax(50px, 1fr)); grid-template-rows: repeat(1, minmax(0, 1fr)); height: 60px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-oKzvO .framer-198196v { align-content: center; align-items: center; align-self: start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; grid-column: span 2; height: 100%; justify-content: flex-start; justify-self: start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-oKzvO .framer-qi60dw { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 60px); overflow: hidden; position: relative; width: 60px; will-change: var(--framer-will-change-override, transform); }",
	".framer-oKzvO .framer-ux00ow, .framer-oKzvO .framer-e8q0x1 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-oKzvO .framer-jgu817, .framer-oKzvO .framer-usz3ri, .framer-oKzvO .framer-11fsdq6 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-oKzvO .framer-1i6d0gy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100px; }",
	".framer-oKzvO .framer-wvr737-container, .framer-oKzvO .framer-1xk8oge-container, .framer-oKzvO .framer-10y5ju1-container, .framer-oKzvO .framer-x5ghtn-container, .framer-oKzvO .framer-1v2l5v5-container, .framer-oKzvO .framer-1stu0et-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-oKzvO .framer-15pmg22 { align-content: center; align-items: center; align-self: start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; justify-self: start; overflow: visible; padding: 0px; position: relative; width: 1fr; }",
	".framer-oKzvO .framer-m9x87o { align-content: center; align-items: center; align-self: start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: flex-end; justify-self: start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-oKzvO.framer-v-72igpp.framer-1ppvcsj { width: 390px; }",
	".framer-oKzvO.framer-v-72igpp .framer-1locatp { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; }",
	".framer-oKzvO.framer-v-72igpp .framer-198196v { align-self: unset; gap: 12px; height: min-content; }",
	".framer-oKzvO.framer-v-72igpp .framer-qi60dw { height: var(--framer-aspect-ratio-supported, 100px); width: 100px; }",
	".framer-oKzvO.framer-v-72igpp .framer-ux00ow { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 16px; justify-content: center; }",
	".framer-oKzvO.framer-v-72igpp .framer-e8q0x1 { align-content: flex-start; align-items: flex-start; flex: none; flex-direction: column; gap: 8px; padding: 0px 0px 0px 8px; width: 100%; }",
	...css2,
	...css4,
	...css3,
	...css,
	'.framer-oKzvO[data-border="true"]::after, .framer-oKzvO [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var Framervcg9tNQW_ = withCSS(Component, css5, "framer-oKzvO");
var stdin_default5 = Framervcg9tNQW_;
Framervcg9tNQW_.displayName = "Team Row";
Framervcg9tNQW_.defaultProps = {
	height: 84,
	width: 1200,
};
addPropertyControls(Framervcg9tNQW_, {
	variant: {
		options: ["wbZEuhaRj", "QOTRRDlBZ"],
		optionTitles: ["Desktop", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	kuh5027FJ: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	CGQWd6Nof: {
		defaultValue: "Ava Thiery",
		title: "Name",
		type: ControlType.String,
	},
	IGwwsmMR9: {
		defaultValue: "Founder",
		displayTextArea: false,
		title: "Role",
		type: ControlType.String,
	},
	Aiw_7yw5S: {
		title: "Behance Link",
		type: ControlType.Link,
	},
	Pvy1MHlAQ: {
		title: "Instagram Link",
		type: ControlType.Link,
	},
	WG2It9KCI: {
		title: "X Link",
		type: ControlType.Link,
	},
});
addFonts(
	Framervcg9tNQW_,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...SocialButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
Framervcg9tNQW_.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default4, {}, context)]);
	},
};

// virtual:team-row
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TeamRowFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var team_row_default = ComponentWithRoot;
export { team_row_default as default };
