// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e4fc90c95afaebc0 "Das Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Vertical' | 'Vertical Centered' | 'Horizontal Tight' // Variant
 * badge?: string // Badge
 * onNWRNXBUFCHange?: any // onNWRNXBUFCHange
 * text?: string // Text
 * onu_A8FTC1iChange?: any // onu_A8FTC1iChange
 * authorImage?: {src: string, srcSet?: string, alt?: string} // Author Image
 * authorName?: string // Author Name
 * onLMWVkAk3sChange?: any // onLMWVkAk3sChange
 * authorRole?: string // Author Role
 * ontXwOZQTGHCHange?: any // ontXwOZQTGHCHange
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-4VNGL5SF.js";
import { stdin_default } from "./chunks/chunk-K3E6XJWX.js";
import "./chunks/chunk-46Q3S57O.js";
import { className, css, fonts } from "./chunks/chunk-7CFDZMPZ.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-B5JEBSFU.js";
import { routes } from "./chunks/chunk-BAX4IDEL.js";

// virtual:testimonial-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/gipBVpWuCL0eAWVuY8yj/tcr6OHhsMJDmhB3j6Knw/IjDxSXDqt.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var StarsFonts = getFonts(stdin_default2);
var CreatorBadgeFonts = getFonts(stdin_default);
var cycleOrder = ["c_T9RvCtV", "T7hZYLVXA", "oEg7l_gsY"];
var serializationHash = "framer-PKV4j";
var variantClassNames = {
	c_T9RvCtV: "framer-v-1m7jofx",
	oEg7l_gsY: "framer-v-1qekr1y",
	T7hZYLVXA: "framer-v-1oqbfi7",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Horizontal Tight": "oEg7l_gsY",
	"Vertical Centered": "T7hZYLVXA",
	Vertical: "c_T9RvCtV",
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	authorImage,
	authorName,
	authorRole,
	badge,
	height,
	id,
	text,
	width,
	...props
}) => {
	return {
		...props,
		AKDEKkQHv: authorImage ?? props.AKDEKkQHv,
		LMwVkAk3s: authorName ?? props.LMwVkAk3s ?? "Sophie Turner",
		NWRNX_bUF: badge ?? props.NWRNX_bUF ?? "3/9",
		tXwOZQTgH: authorRole ?? props.tXwOZQTgH ?? "Brand Strategist",
		u_A8FTC1i:
			text ??
			props.u_A8FTC1i ??
			"From early concepts to fully coded launches, we turn bright ideas into measurable results.",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "c_T9RvCtV",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		NWRNX_bUF: NWRNX_bUF2,
		u_A8FTC1i: u_A8FTC1i2,
		AKDEKkQHv: AKDEKkQHv2,
		LMwVkAk3s: LMwVkAk3s2,
		tXwOZQTgH: tXwOZQTgH2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "c_T9RvCtV",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1m7jofx",
							className3,
							classNames,
						)}
						data-framer-name={"Vertical"}
						layoutDependency={layoutDependency}
						layoutId={"c_T9RvCtV"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-e2a325f5-5d1b-4d4f-b9bb-f0704bd5c816, rgb(245, 245, 245))",
							borderBottomLeftRadius: 10,
							borderBottomRightRadius: 10,
							borderTopLeftRadius: 10,
							borderTopRightRadius: 10,
							...style,
						}}
						{...addPropertyOverrides(
							{
								oEg7l_gsY: {
									"data-framer-name": "Horizontal Tight",
								},
								T7hZYLVXA: {
									"data-framer-name": "Vertical Centered",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1fhqfvz"}
							data-framer-name={"Inner Container"}
							layoutDependency={layoutDependency}
							layoutId={"RTsyfjg5w"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-cia9kc"}
								data-framer-name={"Top Details"}
								layoutDependency={layoutDependency}
								layoutId={"Y2xgNrvPT"}
							>
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={200}
									y={
										(componentViewport?.y || 0) +
										24 +
										0 +
										0 +
										(0 +
											0 +
											((Math.max(
												0,
												((componentViewport?.height || 332) - 48 - 0) / 1,
											) *
												1 -
												0 -
												359) /
												2) *
												0) +
										0
									}
									{...addPropertyOverrides(
										{
											oEg7l_gsY: {
												y:
													(componentViewport?.y || 0) +
													24 +
													(0 +
														(((componentViewport?.height || 332) - 48) * 1 -
															0 -
															200) /
															2) +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-1b9faqp-container"}
										layoutDependency={layoutDependency}
										layoutId={"nctWRDPOJ-container"}
										nodeId={"nctWRDPOJ"}
										rendersWithMotion={true}
										scopeId={"IjDxSXDqt"}
									>
										{_jsx(stdin_default2, {
											suppressHydrationWarning: true,
											height: "100%",
											id: "nctWRDPOJ",
											layoutId: "nctWRDPOJ",
											variant: matchVariant("ZZvUJpjX4"),
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-yjypq6"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"CS2a6Xl38"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={NWRNX_bUF2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-t7dvh9"}
											data-styles-preset={"vkgsOTgUD"}
										>
											{"3/9"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-abr9fr"}
								data-framer-name={"Titles"}
								layoutDependency={layoutDependency}
								layoutId={"kzybX6kxR"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-odt34i"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"Knr8TQm67"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={u_A8FTC1i2}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											T7hZYLVXA: {
												children: (
													<React.Fragment>
														<motion.p
															suppressHydrationWarning={true}
															className={"framer-styles-preset-26kq2w"}
															data-styles-preset={"zuIVYXLhn"}
															style={{
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7)))",
															}}
														>
															{
																"From early concepts to fully coded launches, we turn bright ideas into measurable results."
															}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-26kq2w"}
											data-styles-preset={"zuIVYXLhn"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7)))",
											}}
										>
											{
												"From early concepts to fully coded launches, we turn bright ideas into measurable results."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<ComponentViewportProvider
								suppressHydrationWarning={true}
								height={47}
								width={`calc(${componentViewport?.width || "100vw"} - 48px)`}
								y={
									(componentViewport?.y || 0) +
									24 +
									0 +
									0 +
									(0 +
										312 +
										((Math.max(
											0,
											((componentViewport?.height || 332) - 48 - 0) / 1,
										) *
											1 -
											0 -
											359) /
											2) *
											2)
								}
								{...addPropertyOverrides(
									{
										oEg7l_gsY: {
											width: `max((max(${componentViewport?.width || "100vw"} - 48px, 1px) - 112px) / 3, 1px)`,
											y:
												(componentViewport?.y || 0) +
												24 +
												(0 +
													(((componentViewport?.height || 332) - 48) * 1 -
														0 -
														47) /
														2),
										},
										T7hZYLVXA: {
											width: `min(${componentViewport?.width || "100vw"} - 48px, 250px)`,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-1h3kw8n-container"}
									layoutDependency={layoutDependency}
									layoutId={"vy5Vao52w-container"}
									nodeId={"vy5Vao52w"}
									rendersWithMotion={true}
									scopeId={"IjDxSXDqt"}
								>
									{_jsx(stdin_default, {
										suppressHydrationWarning: true,
										BHmcyfiik: toResponsiveImage(AKDEKkQHv2),
										height: "100%",
										id: "vy5Vao52w",
										layoutId: "vy5Vao52w",
										Sk4JAQDYX: LMwVkAk3s2,
										style: {
											width: "100%",
										},
										width: "100%",
										x5QwiCBFj: tXwOZQTgH2,
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-PKV4j.framer-tuh76n, .framer-PKV4j .framer-tuh76n { display: block; }",
	".framer-PKV4j.framer-1m7jofx { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 18px; height: 332px; justify-content: flex-start; overflow: visible; padding: 24px; position: relative; width: 374px; }",
	".framer-PKV4j .framer-1fhqfvz { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: 1px; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-PKV4j .framer-cia9kc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-PKV4j .framer-1b9faqp-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-PKV4j .framer-yjypq6 { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: auto; }",
	".framer-PKV4j .framer-abr9fr { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-PKV4j .framer-odt34i { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-PKV4j .framer-1h3kw8n-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-PKV4j.framer-v-1oqbfi7.framer-1m7jofx { align-content: center; align-items: center; width: 331px; }",
	".framer-PKV4j.framer-v-1oqbfi7 .framer-1fhqfvz { align-content: center; align-items: center; max-width: 250px; }",
	".framer-PKV4j.framer-v-1oqbfi7 .framer-abr9fr { align-content: center; align-items: center; }",
	".framer-PKV4j.framer-v-1qekr1y.framer-1m7jofx { flex-direction: row; width: 436px; }",
	".framer-PKV4j.framer-v-1qekr1y .framer-1fhqfvz { align-content: center; align-items: center; flex-direction: row; height: 100%; width: 1px; }",
	".framer-PKV4j.framer-v-1qekr1y .framer-cia9kc, .framer-PKV4j.framer-v-1qekr1y .framer-1h3kw8n-container { flex: 1 0 0px; width: 1px; }",
	".framer-PKV4j.framer-v-1qekr1y .framer-abr9fr { flex: 1 0 0px; gap: 3px; width: 1px; }",
	...css,
	...css2,
];
var FramerIjDxSXDqt = withCSS(Component, css3, "framer-PKV4j");
var stdin_default3 = FramerIjDxSXDqt;
FramerIjDxSXDqt.displayName = "Testimonial Card";
FramerIjDxSXDqt.defaultProps = {
	height: 332,
	width: 374,
};
addPropertyControls(FramerIjDxSXDqt, {
	variant: {
		options: ["c_T9RvCtV", "T7hZYLVXA", "oEg7l_gsY"],
		optionTitles: ["Vertical", "Vertical Centered", "Horizontal Tight"],
		title: "Variant",
		type: ControlType.Enum,
	},
	NWRNX_bUF: {
		defaultValue: "3/9",
		displayTextArea: false,
		title: "Badge",
		type: ControlType.String,
	},
	onNWRNX_bUFChange: {
		changes: "NWRNX_bUF",
		type: ControlType.ChangeHandler,
	},
	u_A8FTC1i: {
		defaultValue:
			"From early concepts to fully coded launches, we turn bright ideas into measurable results.",
		displayTextArea: true,
		title: "Text",
		type: ControlType.String,
	},
	onu_A8FTC1iChange: {
		changes: "u_A8FTC1i",
		type: ControlType.ChangeHandler,
	},
	AKDEKkQHv: {
		title: "Author Image",
		type: ControlType.ResponsiveImage,
	},
	LMwVkAk3s: {
		defaultValue: "Sophie Turner",
		displayTextArea: false,
		title: "Author Name",
		type: ControlType.String,
	},
	onLMwVkAk3sChange: {
		changes: "LMwVkAk3s",
		type: ControlType.ChangeHandler,
	},
	tXwOZQTgH: {
		defaultValue: "Brand Strategist",
		displayTextArea: false,
		title: "Author Role",
		type: ControlType.String,
	},
	ontXwOZQTgHChange: {
		changes: "tXwOZQTgH",
		type: ControlType.ChangeHandler,
	},
});
addFonts(
	FramerIjDxSXDqt,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...StarsFonts,
		...CreatorBadgeFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerIjDxSXDqt.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default2, {}, context),
			forwardLoader(stdin_default, {}, context),
		]);
	},
};

// virtual:testimonial-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TestimonialCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var testimonial_card_default = ComponentWithRoot;
export { testimonial_card_default as default };
