// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e4fc90c95afaebc0 "Das Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' // Variant
 * badge?: string // Badge
 * onAJUIr1jMlChange?: any // onAJUIr1jMlChange
 * text?: string // Text
 * onB7IbrWrckChange?: any // onB7IbrWrckChange
 * badgeSecondary?: string // Badge Secondary
 * onN45wIySVJChange?: any // onN45wIySVJChange
 * hasButtons?: boolean // Has Buttons
 * onMUNZSlqu8Change?: any // onMUNZSlqu8Change
 * button1Title?: string // Button 1 Title
 * onYYDUmzVnWCHange?: any // onYYDUmzVnWCHange
 * button1Link?: string // Button 1 Link
 * button2Title?: string // Button 2 Title
 * onlWkDqT20OCHange?: any // onlWkDqT20OCHange
 * button2Link?: string // Button 2 Link
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-IYUBPT6N.js";
import "./chunks/chunk-I6BBA4QK.js";
import { stdin_default } from "./chunks/chunk-GHRXF5NR.js";
import "./chunks/chunk-EANZ46VA.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-7CFDZMPZ.js";
import { className, css, fonts } from "./chunks/chunk-XWVFXG3B.js";
import { routes } from "./chunks/chunk-BAX4IDEL.js";

// virtual:text-header
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ioWlJMgJD1ijJ8QrBJuB/U1wmWnUiBTcnp3YC52Xt/MRMICrYgF.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var BadgeFonts = getFonts(stdin_default);
var ButtonFonts = getFonts(stdin_default2);
var cycleOrder = ["Hgq2I_ypK", "S_8HTHKfF"];
var serializationHash = "framer-mb1vK";
var variantClassNames = {
	Hgq2I_ypK: "framer-v-zucodl",
	S_8HTHKfF: "framer-v-y4z647",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "Hgq2I_ypK",
	Phone: "S_8HTHKfF",
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	badge,
	badgeSecondary,
	button1Link,
	button1Title,
	button2Link,
	button2Title,
	hasButtons,
	height,
	id,
	text,
	width,
	...props
}) => {
	return {
		...props,
		AJUir1jMl: badge ?? props.AJUir1jMl ?? "Social media assets",
		B7IbrWrck:
			text ??
			props.B7IbrWrck ??
			" We help brands create clear visuals, strong websites, and consistent marketing.",
		EcHtUlg4F: button1Link ?? props.EcHtUlg4F,
		lWkDqT20O: button2Title ?? props.lWkDqT20O ?? "Our Approach",
		MUNzSlqu8: hasButtons ?? props.MUNzSlqu8 ?? true,
		N45wIySVj: badgeSecondary ?? props.N45wIySVj ?? "[01]",
		T3ETj7GH4: button2Link ?? props.T3ETj7GH4,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Hgq2I_ypK",
		YYdUmzVnW: button1Title ?? props.YYdUmzVnW ?? "Discover services",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		AJUir1jMl: AJUir1jMl2,
		B7IbrWrck: B7IbrWrck2,
		N45wIySVj: N45wIySVj2,
		MUNzSlqu8: MUNzSlqu82,
		YYdUmzVnW: YYdUmzVnW2,
		EcHtUlg4F: EcHtUlg4F2,
		lWkDqT20O: lWkDqT20O2,
		T3ETj7GH4: T3ETj7GH42,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Hgq2I_ypK",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "S_8HTHKfF") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "S_8HTHKfF") return true;
		return false;
	};
	const visible = isSet(YYdUmzVnW2);
	const visible1 = isSet(lWkDqT20O2);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-zucodl",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"Hgq2I_ypK"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								S_8HTHKfF: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-cb2k72"}
							data-framer-name={"Inner Container"}
							layoutDependency={layoutDependency}
							layoutId={"ectKFqifp"}
						>
							{isDisplayed() && (
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={28}
									width={`max((${componentViewport?.width || "100vw"} - 16px) / 4, 1px)`}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 146) - 0 - 240) / 2 +
											0 +
											0) +
										0
									}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-1xdk5dh-container"}
										layoutDependency={layoutDependency}
										layoutId={"GJBbcknQZ-container"}
										nodeId={"GJBbcknQZ"}
										rendersWithMotion={true}
										scopeId={"MRMICrYgF"}
									>
										{_jsx(stdin_default, {
											suppressHydrationWarning: true,
											height: "100%",
											id: "GJBbcknQZ",
											layoutId: "GJBbcknQZ",
											Q9pPRx4wJ: AJUir1jMl2,
											style: {
												width: "100%",
											},
											Wg_ILYJAw: "",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
							{isDisplayed1() && (
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1dm2um9"}
									data-framer-name={"Mobile Details"}
									layoutDependency={layoutDependency}
									layoutId={"gZJ0FR77s"}
								>
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={28}
										{...addPropertyOverrides(
											{
												S_8HTHKfF: {
													width: `max((${componentViewport?.width || "100vw"} - 10px) / 2, 1px)`,
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 232) - 0 - 350) /
															2 +
															0 +
															0) +
														0 +
														0 +
														21,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-zk5d1a-container"}
											layoutDependency={layoutDependency}
											layoutId={"Xi_lEnWRx-container"}
											nodeId={"Xi_lEnWRx"}
											rendersWithMotion={true}
											scopeId={"MRMICrYgF"}
										>
											{_jsx(stdin_default, {
												suppressHydrationWarning: true,
												height: "100%",
												id: "Xi_lEnWRx",
												layoutId: "Xi_lEnWRx",
												Q9pPRx4wJ: AJUir1jMl2,
												style: {
													width: "100%",
												},
												Wg_ILYJAw: "",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-18g5dpv"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"TAf14fhdl"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7))",
										}}
										text={N45wIySVj2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-t7dvh9"}
												data-styles-preset={"vkgsOTgUD"}
												dir={"auto"}
												style={{
													"--framer-text-alignment": "right",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7)))",
												}}
											>
												{"[01]"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							)}
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1je780o"}
								data-framer-name={"Text Block"}
								layoutDependency={layoutDependency}
								layoutId={"hWlJJQfdq"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1wmm6np"}
									data-framer-name={"Text Container"}
									layoutDependency={layoutDependency}
									layoutId={"JIvXXCyi1"}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1nn2y1x"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"VLz7TLPrR"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={B7IbrWrck2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-bgskcq"}
												data-styles-preset={"jjVH7JKxN"}
												style={{
													"--framer-text-alignment": "left",
												}}
											>
												{
													" We help brands create clear visuals, strong websites, and consistent marketing."
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								{MUNzSlqu82 !== false && (
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-3a5os0"}
										data-framer-name={"Buttons Container"}
										layoutDependency={layoutDependency}
										layoutId={"Mdaa2twXi"}
									>
										{visible !== false && (
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={44}
												y={
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 146) - 0 - 240) / 2 +
														0 +
														0) +
													0 +
													0 +
													156 +
													40
												}
												{...addPropertyOverrides(
													{
														S_8HTHKfF: {
															y:
																(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 232) -
																	0 -
																	350) /
																	2 +
																	0 +
																	0) +
																0 +
																110 +
																0 +
																156 +
																40,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-1e8fcke-container"}
													layoutDependency={layoutDependency}
													layoutId={"jh9QKf3Pz-container"}
													nodeId={"jh9QKf3Pz"}
													rendersWithMotion={true}
													scopeId={"MRMICrYgF"}
												>
													{_jsx(stdin_default2, {
														suppressHydrationWarning: true,
														Ge1cwLZdF: false,
														height: "100%",
														id: "jh9QKf3Pz",
														IQJfIgKUA: EcHtUlg4F2,
														kUCdcilHJ: YYdUmzVnW2,
														layoutId: "jh9QKf3Pz",
														variant: matchVariant("qIg3fad0d"),
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
										{visible1 !== false && (
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={44}
												y={
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 146) - 0 - 240) / 2 +
														0 +
														0) +
													0 +
													0 +
													156 +
													40
												}
												{...addPropertyOverrides(
													{
														S_8HTHKfF: {
															y:
																(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 232) -
																	0 -
																	350) /
																	2 +
																	0 +
																	0) +
																0 +
																110 +
																0 +
																156 +
																40,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-mzayjl-container"}
													layoutDependency={layoutDependency}
													layoutId={"yFUVaV9m1-container"}
													nodeId={"yFUVaV9m1"}
													rendersWithMotion={true}
													scopeId={"MRMICrYgF"}
												>
													{_jsx(stdin_default2, {
														suppressHydrationWarning: true,
														Ge1cwLZdF: true,
														height: "100%",
														id: "yFUVaV9m1",
														IQJfIgKUA: T3ETj7GH42,
														kUCdcilHJ: lWkDqT20O2,
														layoutId: "yFUVaV9m1",
														variant: matchVariant("VeSzDgRX5"),
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</motion.div>
								)}
							</motion.div>
							{isDisplayed() && (
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-1qai241"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"pR2bBhwQ5"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7))",
									}}
									text={N45wIySVj2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-t7dvh9"}
											data-styles-preset={"vkgsOTgUD"}
											dir={"auto"}
											style={{
												"--framer-text-alignment": "right",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-72f0347a-b5e1-4158-90fb-ae36dfb02c33, rgba(10, 10, 10, 0.7)))",
											}}
										>
											{"[01]"}
										</motion.p>
									</React.Fragment>
								</RichText>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-mb1vK.framer-1v7ruox, .framer-mb1vK .framer-1v7ruox { display: block; }",
	".framer-mb1vK.framer-zucodl { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1120px; }",
	".framer-mb1vK .framer-cb2k72 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 40px 8px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-mb1vK .framer-1xdk5dh-container, .framer-mb1vK .framer-zk5d1a-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-mb1vK .framer-1dm2um9 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-mb1vK .framer-18g5dpv, .framer-mb1vK .framer-1qai241 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-mb1vK .framer-1je780o { align-content: flex-start; align-items: flex-start; display: flex; flex: 2 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px 32px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; }",
	".framer-mb1vK .framer-1wmm6np { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-mb1vK .framer-1nn2y1x { --framer-text-wrap-override: none; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-mb1vK .framer-3a5os0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 40px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-mb1vK .framer-1e8fcke-container, .framer-mb1vK .framer-mzayjl-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-mb1vK.framer-v-y4z647.framer-zucodl { width: 390px; }",
	".framer-mb1vK.framer-v-y4z647 .framer-cb2k72 { flex-direction: column; }",
	".framer-mb1vK.framer-v-y4z647 .framer-1dm2um9 { flex: none; order: 2; width: 100%; }",
	".framer-mb1vK.framer-v-y4z647 .framer-1je780o { flex: none; order: 3; width: 100%; }",
	...css2,
	...css,
];
var FramerMRMICrYgF = withCSS(Component, css3, "framer-mb1vK");
var stdin_default3 = FramerMRMICrYgF;
FramerMRMICrYgF.displayName = "Text Header";
FramerMRMICrYgF.defaultProps = {
	height: 146,
	width: 1120,
};
addPropertyControls(FramerMRMICrYgF, {
	variant: {
		options: ["Hgq2I_ypK", "S_8HTHKfF"],
		optionTitles: ["Desktop", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	AJUir1jMl: {
		defaultValue: "Social media assets",
		displayTextArea: false,
		title: "Badge",
		type: ControlType.String,
	},
	onAJUir1jMlChange: {
		changes: "AJUir1jMl",
		type: ControlType.ChangeHandler,
	},
	B7IbrWrck: {
		defaultValue:
			" We help brands create clear visuals, strong websites, and consistent marketing.",
		displayTextArea: true,
		title: "Text",
		type: ControlType.String,
	},
	onB7IbrWrckChange: {
		changes: "B7IbrWrck",
		type: ControlType.ChangeHandler,
	},
	N45wIySVj: {
		defaultValue: "[01]",
		displayTextArea: false,
		title: "Badge Secondary",
		type: ControlType.String,
	},
	onN45wIySVjChange: {
		changes: "N45wIySVj",
		type: ControlType.ChangeHandler,
	},
	MUNzSlqu8: {
		defaultValue: true,
		title: "Has Buttons",
		type: ControlType.Boolean,
	},
	onMUNzSlqu8Change: {
		changes: "MUNzSlqu8",
		type: ControlType.ChangeHandler,
	},
	YYdUmzVnW: {
		defaultValue: "Discover services",
		displayTextArea: false,
		title: "Button 1 Title",
		type: ControlType.String,
	},
	onYYdUmzVnWChange: {
		changes: "YYdUmzVnW",
		type: ControlType.ChangeHandler,
	},
	EcHtUlg4F: {
		title: "Button 1 Link",
		type: ControlType.Link,
	},
	lWkDqT20O: {
		defaultValue: "Our Approach",
		displayTextArea: false,
		title: "Button 2 Title",
		type: ControlType.String,
	},
	onlWkDqT20OChange: {
		changes: "lWkDqT20O",
		type: ControlType.ChangeHandler,
	},
	T3ETj7GH4: {
		title: "Button 2 Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerMRMICrYgF,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...BadgeFonts,
		...ButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerMRMICrYgF.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default, {}, context),
			forwardLoader(stdin_default2, {}, context),
		]);
	},
};

// virtual:text-header
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "S_8HTHKfF",
	xl: "Hgq2I_ypK",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TextHeaderFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var text_header_default = ComponentWithRoot;
export { text_header_default as default };
