// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e4fc90c95afaebc0 "Das Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Show' | 'Pause' | 'Transition' // Variant
 * file?: string // File
 * onfrylILAN6Change?: any // onfrylILAN6Change
 * poster?: {src: string, srcSet?: string, alt?: string} // Poster
 * hasStars?: boolean // Has Stars
 * ontGBHQOifbChange?: any // ontGBHQOifbChange
 * badge?: string // Badge
 * ondZTEUFKHYCHange?: any // ondZTEUFKHYCHange
 * title?: string // Title
 * onIydcDMIQGChange?: any // onIydcDMIQGChange
 * subtitle?: string // Subtitle
 * ongA_EZ1eGOCHange?: any // ongA_EZ1eGOCHange
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-EZ24G2IO.js";
import { Video } from "./chunks/chunk-ENY5TG7Y.js";
import { stdin_default } from "./chunks/chunk-4VNGL5SF.js";
import { className, css, fonts } from "./chunks/chunk-7CFDZMPZ.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-B5JEBSFU.js";
import { routes } from "./chunks/chunk-BAX4IDEL.js";

// virtual:video-player
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/S6BWmyC3fAP3uAOOXaP4/KKajXhf0WL2j6AuTUQQe/TsqLduXf_.js
import { jsx as _jsx3, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx as cx3,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	getPropertyControls,
	Image as Image1,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS3,
} from "unframer";
import { LayoutGroup, motion as motion3, MotionConfigContext } from "unframer";
import * as React3 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/E1bKMFA2ziBkgCh12VwI/7Sdbv1jTGh3fsRf2Ly9N/ZYEPWSzpK.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg suppressHydrationWarning={true} {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG
			suppressHydrationWarning={true}
			{...rest}
			layoutId={layoutId}
			ref={ref}
		>
			{children}
		</MotionSVG>
	) : (
		<svg suppressHydrationWarning={true} {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 1 18 C 0.448 18 0 17.552 0 17 L 0 1 C 0 0.448 0.448 0 1 0 L 4 0 C 4.552 0 5 0.448 5 1 L 5 17 C 5 17.552 4.552 18 4 18 Z" fill="transparent" height="18px" id="KXXOu09B2" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(14 3)" width="5px"/><path d="M 1 18 C 0.448 18 0 17.552 0 17 L 0 1 C 0 0.448 0.448 0 1 0 L 4 0 C 4.552 0 5 0.448 5 1 L 5 17 C 5 17.552 4.552 18 4 18 Z" fill="transparent" height="18px" id="z2miuc7Ra" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(5 3)" width="5px"/></svg>';
var getProps = ({ color, height, id, width, width1, ...props }) => {
	return {
		...props,
		JEeZYcamG: width1 ?? props.JEeZYcamG ?? 2,
		P_DcoRcrY: color ?? props.P_DcoRcrY ?? "rgb(0, 0, 0)",
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className4,
		layoutId,
		variant,
		P_DcoRcrY,
		JEeZYcamG,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("1991755855", svg);
	return (
		<SVG
			suppressHydrationWarning={true}
			{...restProps}
			className={cx("framer-NJb0s", className4)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m973uw": P_DcoRcrY,
				"--js9iwy": JEeZYcamG,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use suppressHydrationWarning={true} href={href} />
		</SVG>
	);
});
var css4 = [
	`.framer-NJb0s { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css4, "framer-NJb0s");
Icon.displayName = "Pause";
var stdin_default2 = Icon;
addPropertyControls(Icon, {
	P_DcoRcrY: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	JEeZYcamG: {
		defaultValue: 2,
		displayStepper: true,
		hidden: false,
		max: 16,
		min: 1,
		title: "Width",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/HAXb8usAsbryfPorbMS4/szDG4SSfU1UCFng50IhF/nyoPQewhK.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	motion as motion2,
	useSVGTemplate as useSVGTemplate2,
	withCSS as withCSS2,
} from "unframer";
import * as React2 from "react";
import { forwardRef as forwardRef4 } from "react";
var mask2 = "var(--framer-icon-mask)";
var Base2 = /* @__PURE__ */ forwardRef4(function (props, ref) {
	return (
		<svg suppressHydrationWarning={true} {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG2 = motion2.create(Base2);
var SVG2 = /* @__PURE__ */ forwardRef4((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG2
			suppressHydrationWarning={true}
			{...rest}
			layoutId={layoutId}
			ref={ref}
		>
			{children}
		</MotionSVG2>
	) : (
		<svg suppressHydrationWarning={true} {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg2 =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 0.736 L 0 17.259 C 0.005 17.527 0.153 17.772 0.388 17.902 C 0.623 18.031 0.91 18.025 1.139 17.886 L 14.647 9.625 C 14.866 9.492 15 9.254 15 8.997 C 15 8.741 14.866 8.503 14.647 8.37 L 1.139 0.109 C 0.91 -0.03 0.623 -0.036 0.388 0.093 C 0.153 0.222 0.005 0.468 0 0.736 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="17.99464343330372px" id="aA4uwAbk9" transform="translate(6.75 3.003)" width="15.000071766041629px"/><path d="M 0 0.736 L 0 17.259 C 0.005 17.527 0.153 17.772 0.388 17.902 C 0.623 18.031 0.91 18.025 1.139 17.886 L 14.647 9.625 C 14.866 9.492 15 9.254 15 8.997 C 15 8.741 14.866 8.503 14.647 8.37 L 1.139 0.109 C 0.91 -0.03 0.623 -0.036 0.388 0.093 C 0.153 0.222 0.005 0.468 0 0.736 Z" fill="transparent" height="17.99464343330372px" id="dfZTdlcyH" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(6.75 3.003)" width="15.000071766041629px"/></svg>';
var getProps2 = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const {
		style,
		className: className4,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps2(props);
	const href = useSVGTemplate2("3492944464", svg2);
	return (
		<SVG2
			suppressHydrationWarning={true}
			{...restProps}
			className={cx2("framer-Lyd6D", className4)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use suppressHydrationWarning={true} href={href} />
		</SVG2>
	);
});
var css5 = [
	`.framer-Lyd6D { -webkit-mask: ${mask2}; aspect-ratio: 1; display: block; mask: ${mask2}; width: 24px; }`,
];
var Icon2 = withCSS2(Component2, css5, "framer-Lyd6D");
Icon2.displayName = "Play";
var stdin_default3 = Icon2;
addPropertyControls2(Icon2, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType2.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType2.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType2.Number,
	},
});

// /:https://framerusercontent.com/modules/S6BWmyC3fAP3uAOOXaP4/KKajXhf0WL2j6AuTUQQe/TsqLduXf_.js
var VideoFonts = getFonts(Video);
var StarsFonts = getFonts(stdin_default);
var PlayFonts = getFonts(stdin_default3);
var PauseFonts = getFonts(stdin_default2);
var VideoControls = getPropertyControls(Video);
var enabledGestures = {
	WcdHBaqr1: {
		hover: true,
	},
};
var cycleOrder = ["WcdHBaqr1", "jREmlOoXB", "CK5xGr26q"];
var serializationHash = "framer-eoHYw";
var variantClassNames = {
	CK5xGr26q: "framer-v-1po80ir",
	jREmlOoXB: "framer-v-hechvv",
	WcdHBaqr1: "framer-v-1p1mah1",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.8,
	ease: [0.35, 0, 0, 1],
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0.61, 0.06, 0, 0.97],
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var toImageSrc = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value.src;
	}
	return typeof value === "string" ? value : void 0;
};
var convertFromBoolean = (value, activeLocale) => {
	return value ? 1 : 0;
};
var toNumber = (value) => {
	if (typeof value === "number" && Number.isFinite(value)) return value;
	if (typeof value !== "string") return 0;
	const parsedNumber = parseFloat(value);
	return typeof parsedNumber === "number" && Number.isFinite(parsedNumber)
		? parsedNumber
		: 0;
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Pause: "jREmlOoXB",
	Show: "WcdHBaqr1",
	Transition: "CK5xGr26q",
};
var Variants = motion3.create(React3.Fragment);
var getProps3 = ({
	badge,
	file,
	hasStars,
	height,
	id,
	poster,
	subtitle,
	title,
	width,
	...props
}) => {
	return {
		...props,
		BwW1GaMTj: poster ??
			props.BwW1GaMTj ?? {
				pixelHeight: 1e3,
				pixelWidth: 1200,
				src: "https://framerusercontent.com/images/paIdzlvthcrcqUnYgfbeT6wwc54.png?width=1200&height=1000",
				srcSet:
					"https://framerusercontent.com/images/paIdzlvthcrcqUnYgfbeT6wwc54.png?scale-down-to=512&width=1200&height=1000 512w,https://framerusercontent.com/images/paIdzlvthcrcqUnYgfbeT6wwc54.png?scale-down-to=1024&width=1200&height=1000 1024w,https://framerusercontent.com/images/paIdzlvthcrcqUnYgfbeT6wwc54.png?width=1200&height=1000 1200w",
			},
		dZTeUFKhY: badge ?? props.dZTeUFKhY ?? "3/9",
		frylILaN6:
			file ??
			props.frylILaN6 ??
			"https://framerusercontent.com/assets/CgpifLwkaSzY11xQBQlmxiLJcL0.mp4",
		gA_EZ1eGO: subtitle ?? props.gA_EZ1eGO ?? "Brand Strategist at Noora",
		IydcDMIQg: title ?? props.IydcDMIQg ?? "Sophie Turner",
		tGBHqOifb: hasStars ?? props.tGBHqOifb,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "WcdHBaqr1",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		frylILaN6: frylILaN62,
		BwW1GaMTj: BwW1GaMTj2,
		tGBHqOifb: tGBHqOifb2,
		dZTeUFKhY: dZTeUFKhY2,
		IydcDMIQg: IydcDMIQg2,
		gA_EZ1eGO: gA_EZ1eGO2,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "WcdHBaqr1",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap11muv7m = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("CK5xGr26q");
	});
	const onTaps512i0 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("WcdHBaqr1");
	});
	const onTapblcuma = activeVariantCallback(async (...args) => {
		setVariant("WcdHBaqr1");
	});
	const sharedStyleClassNames = [className, className3, className2];
	const scopingClassNames = cx3(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["jREmlOoXB", "CK5xGr26q"].includes(baseVariant)) return false;
		return true;
	};
	const opacity = toNumber(convertFromBoolean(tGBHqOifb2, activeLocale));
	const isDisplayed1 = () => {
		if (["jREmlOoXB", "CK5xGr26q"].includes(baseVariant)) return true;
		return false;
	};
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition
					suppressHydrationWarning={true}
					value={transition1}
					{...addPropertyOverrides(
						{
							jREmlOoXB: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion3.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-1p1mah1",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Show"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"WcdHBaqr1"}
						onTap={onTap11muv7m}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color": "rgba(255, 255, 255, 0.1)",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backdropFilter: "blur(35px)",
							backgroundColor: "rgba(200, 182, 236, 0.05)",
							borderBottomLeftRadius: 10,
							borderBottomRightRadius: 10,
							borderTopLeftRadius: 10,
							borderTopRightRadius: 10,
							WebkitBackdropFilter: "blur(35px)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								"WcdHBaqr1-hover": {
									"data-framer-name": void 0,
								},
								CK5xGr26q: {
									"data-framer-name": "Transition",
									onTap: onTaps512i0,
								},
								jREmlOoXB: {
									"data-framer-name": "Pause",
									onTap: onTaps512i0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image1
							suppressHydrationWarning={true}
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										((componentViewport?.height || 672) * 0.5000000000000002 -
											((componentViewport?.height || 672) * 1) / 2),
								),
								pixelHeight: 1e3,
								pixelWidth: 1200,
								sizes: componentViewport?.width || "100vw",
								...toResponsiveImage(BwW1GaMTj2),
							}}
							className={"framer-1nv0vm"}
							layoutDependency={layoutDependency}
							layoutId={"wyilHJKEA"}
							style={{
								borderBottomLeftRadius: 10,
								borderBottomRightRadius: 10,
								borderTopLeftRadius: 10,
								borderTopRightRadius: 10,
								filter: "none",
								scale: 1,
								WebkitFilter: "none",
							}}
							variants={{
								"WcdHBaqr1-hover": {
									filter: "grayscale(1) blur(5px)",
									scale: 1.1,
									WebkitFilter: "grayscale(1) blur(5px)",
								},
							}}
						>
							<ComponentViewportProvider suppressHydrationWarning={true}>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-gocojw-container"}
									data-framer-name={"VideoPlay"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"S1XJKnUT0-container"}
									name={"VideoPlay"}
									nodeId={"S1XJKnUT0"}
									rendersWithMotion={true}
									scopeId={"TsqLduXf_"}
									style={{
										filter: "saturate(0) blur(30px)",
										opacity: 0.05,
										scale: 1.1,
										WebkitFilter: "saturate(0) blur(30px)",
									}}
									variants={{
										CK5xGr26q: {
											opacity: 0,
										},
										jREmlOoXB: {
											filter: "saturate(1) blur(0px)",
											opacity: 0,
											scale: 1,
											WebkitFilter: "saturate(1) blur(0px)",
										},
									}}
								>
									<Video
										suppressHydrationWarning={true}
										backgroundColor={"rgba(0, 0, 0, 0)"}
										borderRadius={0}
										bottomLeftRadius={0}
										bottomRightRadius={0}
										controls={false}
										height={"100%"}
										id={"S1XJKnUT0"}
										isMixedBorderRadius={false}
										layoutId={"S1XJKnUT0"}
										loop={true}
										muted={true}
										name={"VideoPlay"}
										objectFit={"cover"}
										playing={true}
										poster={toImageSrc(BwW1GaMTj2)}
										posterEnabled={true}
										srcFile={frylILaN62}
										srcType={"Upload"}
										srcUrl={""}
										startTime={0}
										style={{
											height: "100%",
											width: "100%",
										}}
										topLeftRadius={0}
										topRightRadius={0}
										volume={25}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider suppressHydrationWarning={true}>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-11kahjc-container"}
									data-framer-name={"VideoIdle"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"Uqgrvxapz-container"}
									name={"VideoIdle"}
									nodeId={"Uqgrvxapz"}
									rendersWithMotion={true}
									scopeId={"TsqLduXf_"}
									style={{
										filter: "none",
										opacity: 0,
										WebkitFilter: "none",
									}}
									variants={{
										"WcdHBaqr1-hover": {
											filter: "none",
											WebkitFilter: "none",
										},
										CK5xGr26q: {
											filter: "none",
											opacity: 1,
											WebkitFilter: "none",
										},
										jREmlOoXB: {
											filter: "saturate(1) blur(0px)",
											WebkitFilter: "saturate(1) blur(0px)",
										},
									}}
								>
									<Video
										suppressHydrationWarning={true}
										backgroundColor={"rgba(0, 0, 0, 0)"}
										borderRadius={0}
										bottomLeftRadius={0}
										bottomRightRadius={0}
										controls={false}
										height={"100%"}
										id={"Uqgrvxapz"}
										isMixedBorderRadius={false}
										layoutId={"Uqgrvxapz"}
										loop={true}
										muted={true}
										name={"VideoIdle"}
										objectFit={"cover"}
										playing={false}
										poster={toImageSrc(BwW1GaMTj2)}
										posterEnabled={true}
										srcFile={frylILaN62}
										srcType={"Upload"}
										srcUrl={""}
										startTime={0}
										style={{
											height: "100%",
											width: "100%",
										}}
										topLeftRadius={0}
										topRightRadius={0}
										volume={25}
										width={"100%"}
										{...addPropertyOverrides(
											{
												CK5xGr26q: {
													playing: true,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</Image1>
						{isDisplayed() && (
							<motion3.div
								suppressHydrationWarning={true}
								className={"framer-1jjlnl7"}
								data-framer-name={"Inner Container"}
								layoutDependency={layoutDependency}
								layoutId={"dxxDWpiun"}
								style={{
									backgroundColor: "rgba(0, 0, 0, 0.29)",
									borderBottomLeftRadius: 10,
									borderBottomRightRadius: 10,
									borderTopLeftRadius: 10,
									borderTopRightRadius: 10,
								}}
							>
								<motion3.div
									suppressHydrationWarning={true}
									className={"framer-b5cfe8"}
									layoutDependency={layoutDependency}
									layoutId={"drTZx8cwR"}
								>
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={200}
										y={
											(componentViewport?.y || 0) +
											((componentViewport?.height || 672) * 0.5000000000000002 -
												((componentViewport?.height || 672) * 1) / 2) +
											24 +
											(0 +
												0 +
												(((componentViewport?.height || 672) * 1 - 48 - 250.4) /
													1) *
													0) +
											0
										}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-bh7rrx-container"}
											layoutDependency={layoutDependency}
											layoutId={"hWIKLqWJ8-container"}
											nodeId={"hWIKLqWJ8"}
											rendersWithMotion={true}
											scopeId={"TsqLduXf_"}
											style={{
												opacity,
											}}
										>
											{_jsx3(stdin_default, {
												suppressHydrationWarning: true,
												height: "100%",
												id: "hWIKLqWJ8",
												layoutId: "hWIKLqWJ8",
												variant: matchVariant("RJUbGDQfx"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1rwh3w0"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"i0apWJT8k"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-1ad0dd99-5aec-4e1d-804a-3c603649eb34, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={dZTeUFKhY2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion3.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-t7dvh9"}
												data-styles-preset={"vkgsOTgUD"}
												dir={"auto"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-1ad0dd99-5aec-4e1d-804a-3c603649eb34, rgb(255, 255, 255)))",
												}}
											>
												{"3/9"}
											</motion3.p>
										</React3.Fragment>
									</RichText>
								</motion3.div>
								<motion3.div
									suppressHydrationWarning={true}
									className={"framer-6r1h43"}
									data-framer-name={"Button"}
									layoutDependency={layoutDependency}
									layoutId={"zibQPIR17"}
									style={{
										borderBottomLeftRadius: 100,
										borderBottomRightRadius: 100,
										borderTopLeftRadius: 100,
										borderTopRightRadius: 100,
									}}
									transformTemplate={transformTemplate1}
								>
									<motion3.div
										suppressHydrationWarning={true}
										className={"framer-tuwh3e"}
										data-framer-name={"Icon Container"}
										layoutDependency={layoutDependency}
										layoutId={"y_hNH5FAi"}
										style={{
											backgroundColor:
												"var(--token-1ad0dd99-5aec-4e1d-804a-3c603649eb34, rgb(255, 255, 255))",
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
										}}
									>
										{_jsx3(stdin_default3, {
											suppressHydrationWarning: true,
											animated: true,
											className: "framer-tzfafl",
											layoutDependency,
											layoutId: "JVUxeNbJa",
											style: {
												"--1m6trwb": 1,
												"--21h8s6":
													"var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(10, 10, 10))",
												"--pgex8v": 2,
											},
										})}
									</motion3.div>
								</motion3.div>
								<motion3.div
									suppressHydrationWarning={true}
									className={"framer-x3j6o5"}
									data-framer-name={"Titles"}
									layoutDependency={layoutDependency}
									layoutId={"Aad4Bq6mM"}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-16wzpks"}
										data-framer-name={"Name"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"LYdih9uND"}
										style={{
											"--extracted-1w1cjl5":
												"var(--token-1ad0dd99-5aec-4e1d-804a-3c603649eb34, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={IydcDMIQg2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion3.h6
												suppressHydrationWarning={true}
												className={"framer-styles-preset-9d6j7p"}
												data-styles-preset={"Mk5Vgse8Z"}
												dir={"auto"}
												style={{
													"--framer-text-color":
														"var(--extracted-1w1cjl5, var(--token-1ad0dd99-5aec-4e1d-804a-3c603649eb34, rgb(255, 255, 255)))",
												}}
											>
												{"Sophie Turner"}
											</motion3.h6>
										</React3.Fragment>
									</RichText>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1i5pox1"}
										data-framer-name={"Role"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"XOpqLgMhk"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-e2a325f5-5d1b-4d4f-b9bb-f0704bd5c816, rgb(245, 245, 245))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={gA_EZ1eGO2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion3.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-26kq2w"}
												data-styles-preset={"zuIVYXLhn"}
												dir={"auto"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-e2a325f5-5d1b-4d4f-b9bb-f0704bd5c816, rgb(245, 245, 245)))",
												}}
											>
												{"Brand Strategist at Noora"}
											</motion3.p>
										</React3.Fragment>
									</RichText>
								</motion3.div>
							</motion3.div>
						)}
						{isDisplayed1() && (
							<motion3.div
								suppressHydrationWarning={true}
								className={"framer-e9sj9w"}
								data-framer-name={"Icon Container"}
								layoutDependency={layoutDependency}
								layoutId={"yesGFyYR9"}
								style={{
									backgroundColor:
										"var(--token-c71bcefb-0dff-4f5c-b804-6e877f58b297, rgb(10, 10, 10))",
									borderBottomLeftRadius: 100,
									borderBottomRightRadius: 100,
									borderTopLeftRadius: 100,
									borderTopRightRadius: 100,
								}}
								{...addPropertyOverrides(
									{
										jREmlOoXB: {
											"data-highlight": true,
											onTap: onTapblcuma,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								{isDisplayed1() &&
									_jsx3(stdin_default2, {
										suppressHydrationWarning: true,
										animated: true,
										className: "framer-1gyjgtz",
										layoutDependency,
										layoutId: "D76cqJzTn",
										style: {
											"--1m973uw":
												"var(--token-1ad0dd99-5aec-4e1d-804a-3c603649eb34, rgb(255, 255, 255))",
											"--js9iwy": 2,
										},
									})}
							</motion3.div>
						)}
					</motion3.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-eoHYw.framer-1ysemq4, .framer-eoHYw .framer-1ysemq4 { display: block; }",
	".framer-eoHYw.framer-1p1mah1 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 672px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1200px; will-change: var(--framer-will-change-override, transform); }",
	".framer-eoHYw .framer-1nv0vm { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-eoHYw .framer-gocojw-container { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 1; }",
	".framer-eoHYw .framer-11kahjc-container { flex: none; height: 103%; left: calc(50.00000000000002% - 103% / 2); position: absolute; top: calc(50.00000000000002% - 103% / 2); width: 103%; z-index: 0; }",
	".framer-eoHYw .framer-1jjlnl7 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; height: 100%; justify-content: space-between; left: calc(50.00000000000002% - 100% / 2); overflow: visible; padding: 24px; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 1; }",
	".framer-eoHYw .framer-b5cfe8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-eoHYw .framer-bh7rrx-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-eoHYw .framer-1rwh3w0 { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: auto; }",
	".framer-eoHYw .framer-6r1h43 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; left: 49%; overflow: hidden; padding: 0px; position: absolute; top: 50%; width: min-content; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-eoHYw .framer-tuwh3e { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 53px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 53px; will-change: var(--framer-will-change-override, transform); }",
	".framer-eoHYw .framer-tzfafl { flex: none; height: var(--framer-aspect-ratio-supported, 25px); position: relative; width: 26px; }",
	".framer-eoHYw .framer-x3j6o5 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-eoHYw .framer-16wzpks, .framer-eoHYw .framer-1i5pox1 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-eoHYw .framer-e9sj9w { align-content: center; align-items: center; bottom: 30px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 53px; justify-content: center; overflow: hidden; padding: 0px; position: absolute; right: 30px; width: 53px; will-change: var(--framer-will-change-override, transform); z-index: 4; }",
	".framer-eoHYw .framer-1gyjgtz { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
	".framer-eoHYw.framer-v-hechvv .framer-1nv0vm, .framer-eoHYw.framer-v-1po80ir .framer-1nv0vm { order: 1; }",
	".framer-eoHYw.framer-v-hechvv .framer-gocojw-container { z-index: 0; }",
	".framer-eoHYw.framer-v-hechvv .framer-e9sj9w { cursor: pointer; order: 0; }",
	".framer-eoHYw.framer-v-1po80ir .framer-e9sj9w { order: 0; }",
	...css,
	...css3,
	...css2,
	'.framer-eoHYw[data-border="true"]::after, .framer-eoHYw [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerTsqLduXf_ = withCSS3(Component3, css6, "framer-eoHYw");
var stdin_default4 = FramerTsqLduXf_;
FramerTsqLduXf_.displayName = "VideoPlayer";
FramerTsqLduXf_.defaultProps = {
	height: 672,
	width: 1200,
};
addPropertyControls3(FramerTsqLduXf_, {
	variant: {
		options: ["WcdHBaqr1", "jREmlOoXB", "CK5xGr26q"],
		optionTitles: ["Show", "Pause", "Transition"],
		title: "Variant",
		type: ControlType3.Enum,
	},
	frylILaN6: VideoControls?.["srcFile"] && {
		...VideoControls["srcFile"],
		__defaultAssetReference:
			"data:framer/asset-reference,CgpifLwkaSzY11xQBQlmxiLJcL0.mp4?originalFilename=double-chance-2.mp4",
		description: void 0,
		hidden: void 0,
		title: "File",
	},
	onfrylILaN6Change: {
		changes: "frylILaN6",
		type: ControlType3.ChangeHandler,
	},
	BwW1GaMTj: {
		__defaultAssetReference:
			"data:framer/asset-reference,paIdzlvthcrcqUnYgfbeT6wwc54.png?originalFilename=Delicate+White+Blossoms.png&width=1200&height=1000",
		title: "Poster",
		type: ControlType3.ResponsiveImage,
	},
	tGBHqOifb: {
		defaultValue: false,
		title: "Has Stars",
		type: ControlType3.Boolean,
	},
	ontGBHqOifbChange: {
		changes: "tGBHqOifb",
		type: ControlType3.ChangeHandler,
	},
	dZTeUFKhY: {
		defaultValue: "3/9",
		displayTextArea: false,
		title: "Badge",
		type: ControlType3.String,
	},
	ondZTeUFKhYChange: {
		changes: "dZTeUFKhY",
		type: ControlType3.ChangeHandler,
	},
	IydcDMIQg: {
		defaultValue: "Sophie Turner",
		displayTextArea: false,
		title: "Title",
		type: ControlType3.String,
	},
	onIydcDMIQgChange: {
		changes: "IydcDMIQg",
		type: ControlType3.ChangeHandler,
	},
	gA_EZ1eGO: {
		defaultValue: "Brand Strategist at Noora",
		displayTextArea: false,
		title: "Subtitle",
		type: ControlType3.String,
	},
	ongA_EZ1eGOChange: {
		changes: "gA_EZ1eGO",
		type: ControlType3.ChangeHandler,
	},
});
addFonts(
	FramerTsqLduXf_,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...VideoFonts,
		...StarsFonts,
		...PlayFonts,
		...PauseFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerTsqLduXf_.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:video-player
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "WcdHBaqr1",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders VideoPlayerFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e4fc90c95afaebc0cc327c83737dfc34700727f3bf116f33c77726f3bea83377"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var video_player_default = ComponentWithRoot;
export { video_player_default as default };
